### ISSUE TITLE
PHP 7.2

### ISSUE THREAD

**Issue by optimusprime338** [GenisysPro/GenisysPro#1028]
#### Issue description

Hey I am sorry idk where to report but php 7.2 for windows download doesn't work. Can you fix??

#### Platform information

* Git commit:

* PHP binary version:

* Server OS:

* Game client:

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by ivan691** [comment]
Facepalm

**Comment by Leo3418** [comment]
We have gone back to PHP 7.0.
