### ISSUE TITLE
Strange Black Texture

### ISSUE THREAD

**Issue by ChaostixZix** [GenisysPro/GenisysPro#103]
* Genisys: 1.1dev
* PHP:7.0.3
* Server OS:Mac Os X
* Game version: MC:Win10

There is An Error On The Texture, Pmmp Has Fixed It. I Hope GenisysPro Will Fix It Soon
![screenshot at jun 07 09-42-16](https://user-images.githubusercontent.com/19998246/26890261-d2b7ea46-4b65-11e7-86f3-ba6fb3af5b9c.png)

**Comment by SuperXingKong** [comment]
Try to fix it by yourself First.
It's bed time here xD.

**Comment by ChaostixZix** [comment]
@SuperXingKong i've tried, i merge it from pmmp.
still no fix :(

sorry to disturb

**Comment by DerddyDert** [comment]
@ChaostixZix He needs his sleep. I will test and troubleshoot with you.

**Comment by ChaostixZix** [comment]
@DerddyDert Thanks :D

**Comment by DerddyDert** [comment]
@ChaostixZix can you show me the commit what PMMP had which fixed this?

**Comment by ChaostixZix** [comment]
@DerddyDert Wait

**Comment by ChaostixZix** [comment]
[dab73d8](https://github.com/pmmp/PocketMine-MP/commit/dab73d895099e4c1c7d632711e204971cbbb0590)

i've tried to copy what they do with DiffuseLight, But still no fix

**Comment by DerddyDert** [comment]
Test server is up. Please come help with testing @ChaostixZix  genpro.derddy.com 19132

**Comment by ChaostixZix** [comment]
@DerddyDert Also, could you test the CommandSender $args? it seems to return noting
