### ISSUE TITLE
Not related to core, question

### ISSUE THREAD

**Issue by ivan691** [GenisysPro/GenisysPro#1031]
https://timings.pmmp.io/?url=25547119
What the problem?

**Comment by mal0ne-23** [comment]
Average Players: 81.88

High player count, and we're talking about GenisysPro here. It can't handle super high player counts.

**Comment by SuperXingKong** [comment]
GenisysPro is a feature-rich software. So it can't as fast as pmmp.

**Comment by SuperXingKong** [comment]
I will close this issue due to keep it clean. If you have other questions, you can @ me below ;)
