### ISSUE TITLE
Underfined property

### ISSUE THREAD

**Issue by armagadon159753** [GenisysPro/GenisysPro#104]
![_20170607_192212](https://user-images.githubusercontent.com/25569806/26891910-f07fab94-4bb6-11e7-985d-6246d441f7a4.JPG)
![screenshot_2017-06-07-19-21-41](https://user-images.githubusercontent.com/25569806/26891918-f4a23ffc-4bb6-11e7-871c-98c33eb33023.png)

**Comment by DerddyDert** [comment]
Please copy the debug info and paste it into your report.
