### ISSUE TITLE
Client crashes when player tries to open inventory 

### ISSUE THREAD

**Issue by SuperKali** [GenisysPro/GenisysPro#107]
* Genisys: 5421cff 
* PHP: 7.0.17
* Server OS: Debian 8 
* Game version: Minecraft Pocket Edition 1.1.0.55

soon as I open the inventory the game crash and No console error

```
(A note from Derddy) I am adding this note so the top comment has 
the result of clean official testing:

- If player clicks inventory, client crashes.
- If player re-joins server again after crash from inventory, the client crashes right away.
   - If player.dat is deleted then player may re-join. 
- Something is getting corrupt in the .dat once player touches the inventory button.
```
@SuperXingKong

**Comment by SamyR0** [comment]
do you use any plugins?

**Comment by DerddyDert** [comment]
@SamyR0 This was verified in #85 When player clicks inventory client crashes and player.dat becomes corrupt preventing future logins. If you delete the player.dat they can login but it will crash once inventory is clicked.

**Comment by SamyR0** [comment]
Hmmmm , i see.

**Comment by AppleDevelops** [comment]
Why was I tagged?

**Comment by AppleDevelops** [comment]
It’s a simple fix I do say but being tagged makes no sense

**Comment by DerddyDert** [comment]
@AppleDevelops we've been putting out feelers. You've helped before. Genisyspro has some potential in it. If you you feel like lending a hand, please do. Otherwise thanks for stopping by.

**Comment by DerddyDert** [comment]
The above applies to anyone else I've tagged. I've been trying to keep things organized with testing but @SuperXingKong  has been working so hard mostly by himself. I just thought some of the Genisyspro veterans may be interested in seeing where it's at and lending a hand. Thanks

**Comment by SuperXingKong** [comment]
I got it, wait for my commit.

**Comment by Sandertv** [comment]
Could I please stop being tagged. I don't care about this project.

**Comment by DerddyDert** [comment]
Appreciate the follow up! Thanks

**Comment by SuperXingKong** [comment]
I am sorry that I don't know why it happened. (I hate working on my phone) And Who can help ?

**Comment by poustmal** [comment]
pmmp seems that has fixed this problem

**Comment by TialKorea** [comment]
Crash Me too

**Comment by DerddyDert** [comment]
Good job @SuperXingKong and thanks Apple
