### ISSUE TITLE
2 weeks For the release of 1.2 mcpe

### ISSUE THREAD

**Issue by SuperKali** [GenisysPro/GenisysPro#1081]
Hi, I would like to know when you will start working on the new version of Minecraft Pocket Edition 
That is 1.2.

**Comment by zKoz210** [comment]
Uhhh... 19 release on 19 September

**Comment by ZackMCPE** [comment]
@SuperKali genisys pro copies pmmp , so when pmmp update we will update !

![thumb_colourbox1233940](https://user-images.githubusercontent.com/31971973/30524027-59a9a9ac-9bdb-11e7-84aa-ce0f8f7c1c0d.jpg)

**Comment by SuperXingKong** [comment]
I will create network-1.2 branch tommorrow. Thank you.

**Comment by LagHD** [comment]
MCPE 1.2 Official update released on XBOX today, and for all other platforms it'll release Wednesday 20th September
