### ISSUE TITLE
performance issue

### ISSUE THREAD

**Issue by ZackMCPE** [GenisysPro/GenisysPro#1083]
hey guys, genisyspro is currently the laggiest shit ouit here , we need a optimiation plan

i say we optimize chunk loading , it is very slow

any ideas on what we should optomize ?

we can remove timings if nessesary , it runs on doTick so it causes lag.

i think its world save ...

**Comment by ZackMCPE** [comment]
@dktapps @Intyre @SOF3 @JackNoordhuis @TheDiamondYT1 @thebigsmileXD @shoghicp may you help with issue ? -.-

thanks

@shoghicp

**Comment by TheDiamondYT1** [comment]
@shoghicp doesn't get involved with external server softwares
@intyre and @dktapps don't care
@SOF3 doesn't care either
I don't care, since i tried to help you earlier and you started shouting at me

**Comment by ZackMCPE** [comment]
@TheDiamondYT1 SHUT UP NO ONE LIKE YOU YOU SPAM STEADFAST2 !

I WILL TELL DKTAPPS WHAT YOU SAY AFTER INTERACTION LIMIT GO AWAY !

@DKTAPPS THEDIAMONDYT SAY YOU STUPID AND HE TELL ME TO SPAM PMMP !

**Comment by SOF3** [comment]
Several feasible solutions:
1. Change the tick rate to 1/minute
2. Never let any clients connecting; clients eat up a lot of performance
3. Multiply the reported CPU load with 0.01
