### ISSUE TITLE
GenisysPro needs a huge cleanup!!!

### ISSUE THREAD

**Issue by SuperXingKong** [GenisysPro/GenisysPro#1088]
## I want to revert GenisysPro to a stable version, because this version is so mess that I can't bear.
@DerddyDert @Leo3418 @MasterOfTheRealm

**Comment by SuperXingKong** [comment]
## Does anyone have a suggestion?
## Type 👍 means you agree with me.
## Type  👎 means you don't agree with me.

P.S. My bad English...

**Comment by MasterOfTheRealm** [comment]
What issues do we have now?

**Comment by MasterOfTheRealm** [comment]
I mean we have a lot of junk code due to people making commits implementing methods from other software. But overall i think this version isn't half bad. Not to mention a revert won't fix our chunk errors. We just need a code cleanup on everything.

**Comment by betty323** [comment]
@MasterOfTheRealm but genisys pro complete copy paste crap

**Comment by MasterOfTheRealm** [comment]
That's just your opinion. You're the real crap hear

**Comment by betty323** [comment]
@MasterOfTheRealm but u guys copy @dktapps for updates

**Comment by betty323** [comment]
and crap code, perform shit

**Comment by betty323** [comment]
Please dont revert genisys pro we worked hard and make many progresses

**Comment by betty323** [comment]
i will ask dertderrdy if nessesary to rwevert pmmp , and then will open issue there to inform @dktapps

**Comment by betty323** [comment]
DERTDERRDY SAY PMMP NEEDS REVERT !

**Comment by KenMizz** [comment]
agree :)

**Comment by DerddyDert** [comment]
I recommend individually reverting only prs with bad code and cleaning without reverting what we can.

**Comment by CortexPE** [comment]
Should I continue trying to update to 1.2 or clean-up GenisysPro instead? 😂

**Comment by MasterOfTheRealm** [comment]
1.2 lol... i'll help with the cleanup after i get some more free time from prisonwork...ehem... schoolwork.

**Comment by CortexPE** [comment]
We probably should use strict types, avoid typecasting, and add more type hints & even strict type hints.

**Comment by SuperXingKong** [comment]
@CortexPE You are not able to update 1.2 guy
