### ISSUE TITLE
Cannot place blocks

### ISSUE THREAD

**Issue by DerddyDert** [GenisysPro/GenisysPro#109]
Cannot place blocks **under any circumstance.** Cannot place in any game mode, as OP, outside of spawn protection. No possible way to place a block.

**Comment by SuperXingKong** [comment]
idk...
was BlockPlaceEvent called?

**Comment by DerddyDert** [comment]
Ill try to test again more thoroughly but it just acted like a non-OP trying to place blocks in a protected spawn.
