### ISSUE TITLE
Snowball error 雪球的错误

### ISSUE THREAD

**Issue by lowingly** [GenisysPro/GenisysPro#11]
1.在任意地图丢雪球，当雪球掉在地上时会报错。（我在创造模式下扔的，生存模式没试）
Throw snowball in any map, when the snowball fell to the ground will be given an error.

报错内容： [Server thread/CRITICAL]: 计算地图“world”时出现错误∶Call to undefined method stdClass::isClosed()

2.顺带一提，后台随机出现：某某行动可疑！
这是个常见问题，虽然不影响游戏，但是看着难受。希望早日修复。

本服务器正运行 GenisysPro-cf39116 (代号 "Starry")
 PHP 版本: 7.0.17
 API: 3.0.0-ALPHA4 (iTX API 版本 {%1})
客户端: Minecraft PE v1.0.5 (protocol 版本
Protocol version: 105

**Comment by lowingly** [comment]
Remember to fix the sound, the server no sound there..
记得修复声音，服务器没声音= =。

**Comment by xinghao2003** [comment]
某某行動可疑是因為你開啟了movement偵測，然後沒聲音是因為1.0.4開始的資源包更新，所以也影響了後面的版本，只要GenisysPro弄好在資源包的更新就會有聲音

**Comment by SuperXingKong** [comment]
Ahh~We will fix it as fast as possible.
我们将会尽快测试并修复
 Thx for your report!👍

**Comment by SuperXingKong** [comment]
Snowball will fix after a while...
I nust prepare for the mid-term exam lol 💯

**Comment by SuperXingKong** [comment]
Seems I forget sth...
Dont use the latest commit
I will fix it soon

**Comment by SuperXingKong** [comment]
现在我正在更新1.1.0,如果你能自己解决雪球问题,欢迎提交pull
或者等我完成1.1.0的基本更新 :)

**Comment by SuperXingKong** [comment]
你可以开启pocketmine.yml中的debug调试功能,并将它上传到这里,我将会尽可能修复 👍

**Comment by SuperXingKong** [comment]
Alread fix ;) @lowingly
