### ISSUE TITLE
ClientboundMapItemDataPacket is broken

### ISSUE THREAD

**Issue by FaigerSYS** [GenisysPro/GenisysPro#1100]
Are you thinking before copy-pasting code....? There is no method Color::toABGR() etc. in pocketmine\utils\Color .

**Comment by InspectorGadget** [comment]
😂 😂 😂

**Comment by InspectorGadget** [comment]
#BlameCopier

**Comment by SuperXingKong** [comment]
It is the origin code from Genisys....

**Comment by FaigerSYS** [comment]
@SuperXingKong , ,so what? This does not change the situation. Packet is broken
