### ISSUE TITLE
Plugin commands' permission issue

### ISSUE THREAD

**Issue by Norman300** [GenisysPro/GenisysPro#1101]
Players can't use /land command in EconomyLand after commit 8f1157e0 (Aug 07), but OPs can.
Commit cb61a69d (before 8f1157e0, Aug 05) doesn't have this issue.

Use centos7.2 and php7.0.3/7.0.6

在8f1157e0及之后的版本，玩家无法使用领地插件中的任何指令(提示指令不存在)，只有op可以。在之前的cb61a69d没有任何问题。我不知道在这中间发生了什么。

EconomyLand：https://jenkins.onebone.me/job/EconomyS/8/artifact/out/EconomyLand_v2.0.9-78a8e5f8.phar
EconomyAPI：https://jenkins.onebone.me/job/EconomyS/8/artifact/out/EconomyAPI_v2.0.9-78a8e5f8.phar

**Comment by SuperXingKong** [comment]
好的, 我将会在今明两天修复它

**Comment by optimusprime338** [comment]
tysm

**Comment by edwinyoo44** [comment]
在上一個月已經反映過了 #739 
謝謝 @SuperXingKong 願意將該行判斷刪除
