### ISSUE TITLE
InventoryContentPack

### ISSUE THREAD

**Issue by poteity** [GenisysPro/GenisysPro#1103]
#### Platform information

* Git commit:

* PHP binary version:

* Server OS:

* Game client:

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by poteity** [comment]
pls add InventoryContentPack in GenisysPro

**Comment by poteity** [comment]
@DerddyDert @MasterOfTheRealm

**Comment by Frago9876543210** [comment]
InventoryContentPacket added in 1.2. Use ContainerSetContentPacket if you want change chest inventory.
