### ISSUE TITLE
server can't start up

### ISSUE THREAD

**Issue by tomhawks** [GenisysPro/GenisysPro#1105]
Hi guys

Using the latest src, my server cannot start up and I am getting after
https://github.com/GenisysPro/GenisysPro/pull/1097

got merged. How can I fix it?
`Fatal error: Using $this when not in object context in, cannot extend class AddEntityPacket to Original at line`

I don't use plugins

**Comment by SuperXingKong** [comment]
I have reverted it. Are you using the latest src?

**Comment by tomhawks** [comment]
@SuperXingKong thanks works with new src !

**Comment by SuperXingKong** [comment]
Ok, thanks for your report!
