### ISSUE TITLE
UPDATED: Shading/Lighting issue

### ISSUE THREAD

**Issue by DerddyDert** [GenisysPro/GenisysPro#111]
Lighting needs work.

- There is either no shade or 100% darkenss. Not just from blocks but grass snow flowers etc

- If something caused shade but is removed, the shade remains.(compare pics)

![screenshot_20170607-201156](https://user-images.githubusercontent.com/18636275/26908010-df69a4d6-4bc5-11e7-9dda-1c9340d0b5a7.jpg)
![screenshot_20170607-201233](https://user-images.githubusercontent.com/18636275/26908018-ed0b43d8-4bc5-11e7-89e8-b62a7b7aa342.jpg)

**Comment by caspervanneck** [comment]
yea that strange i came desert and it wash black

**Comment by caspervanneck** [comment]
if you set glowstone then its get normal

**Comment by caspervanneck** [comment]
@DerddyDert

**Comment by DerddyDert** [comment]
Cannot place blocks? You can attempt to place any block and it resets the shading.

**Comment by SuperXingKong** [comment]
Now let's try to fix it

**Comment by DerddyDert** [comment]
Some
![screenshot_20170618-010742](https://user-images.githubusercontent.com/18636275/27258261-757fff5a-53c4-11e7-97e7-44ddf4813ff5.jpg)
![screenshot_20170618-010233](https://user-images.githubusercontent.com/18636275/27258265-7e12ba5e-53c4-11e7-869d-d5f9c3e06b8c.jpg)
![screenshot_20170618-010354](https://user-images.githubusercontent.com/18636275/27258267-862bc00a-53c4-11e7-9e02-7399d32ab95c.jpg)

**Comment by caspervanneck** [comment]
Trying to fixt this @DerddyDert i do my best

**Comment by DerddyDert** [comment]
@caspervanneck @MasterOfTheRealm @lightda104530 Whats the latest on this? Do you guys need help?

**Comment by Crypt97** [comment]
Please fix :|

**Comment by DerddyDert** [comment]
This was fixed by @Frago9876543210  Get latest src.
