### ISSUE TITLE
Crash?!

### ISSUE THREAD

**Issue by LewBr** [GenisysPro/GenisysPro#115]
#### Issue description
Crash ;-;

#### Steps to reproduce the issue
When i join the server whit Windows 10 it crashes wtf..
#### OS and versions

* Genisys: latest
* PHP: latest (MultiCraft)
* Server OS: Multicraft
* Game version: 1.1.0 (Windows10)

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
08.06 08:41:38 [Server] Server thread/INFO LewBr[/201.6.230.87:20183] logged out due to timeout
08.06 08:41:55 [Connect] User LewBr, IP unknown
08.06 08:41:55 [Multicraft] LewBr ran command Message of the Day
08.06 08:42:05 [Server] Server thread/INFO LewBr[/201.6.230.87:20193] logged out due to timeout
08.06 08:42:30 [Disconnect] User LewBr has disconnected, reason: unknown
08.06 08:43:39 [Connect] User LewBr, IP unknown
08.06 08:43:39 [Multicraft] LewBr ran command Message of the Day
08.06 08:43:53 [Server] Server thread/INFO LewBr[/201.6.230.87:20216] logged out due to timeout
08.06 08:44:14 [Disconnect] User LewBr has disconnected, reason: unknown
```

**Comment by xinghao2003** [comment]
Its not fully support 1.1

**Comment by DerddyDert** [comment]
Can you delete the player .dat file and try again? Also can you try to log on our test server at genpro.derddy.com Default port? Let me know the results, thanks.

**Comment by DerddyDert** [comment]
This looks related to MOTD? I cannot replicate this issue. What plugins do you use if any?

**Comment by LewBr** [comment]
I use only my Core, 1 plugin for the my Servers, they have changes like motd, but i tested whitout my plugin, and i deleted .dat of all players on the Hub, still crashing.
IP: 
pe.leohardu.net
19132

**Comment by LewBr** [comment]
At genpro.derddy.com, it's not crashing! Lmao

**Comment by DerddyDert** [comment]
genpro has the latest src.
