### ISSUE TITLE
Can't open inventory.

### ISSUE THREAD

**Issue by ParkChanSol** [GenisysPro/GenisysPro#117]
#### Issue description

I can't open inventory
#### Steps to reproduce the issue

Open Inventory 
#### OS and versions

* Genisys:1d38f48
* PHP:7.0.4
* Server OS:Linux
* Game version: 1.1.0.55

**Comment by Leo3418** [comment]
Thanks for reporting. We are sorry to inform you that we have known this issue because we have discovered it, or there has already been an issue reporting the same problem.

**Comment by SuperXingKong** [comment]
Will fix.
