### ISSUE TITLE
New GenisysPro

### ISSUE THREAD

**Issue by Sinner168** [GenisysPro/GenisysPro#120]
Open the bag Client Flash back
Win10 android ios
最新版的核心 6月8日
打开背包后直接无响应闪退Win10 安卓 苹果都是直接闪退

**Comment by DerddyDert** [comment]
Ok but I don't understand "Flash" Do you mean crash? 你的意思是关闭？

**Comment by Leo3418** [comment]
@DerddyDert he did a *literal* translation of "force close" from Chinese. In Chinese the word "force close" consists of 2 characters, the first one has the same meaning to "flash", and "back" as the second one has.
