### ISSUE TITLE
Cannot join

### ISSUE THREAD

**Issue by erkam2002** [GenisysPro/GenisysPro#121]
#### Issue description

Cannot join
#### Steps to reproduce the issue

Join
#### OS and versions

* Genisys: Newest
* PHP: 7.0.3
* Server OS: Debian 8
* Game version:  1.1

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by DerddyDert** [comment]
This is not enough info. Our testing server joins just fine at genpro.derddy.com 19132.

**Comment by erkam2002** [comment]
Sry wrong report
