### ISSUE TITLE
Plugin error

### ISSUE THREAD

**Issue by erkam2002** [GenisysPro/GenisysPro#122]
#### Issue description

I have errors
#### OS and versions

* Genisys: Newest
* PHP: 7.0.3
* Server OS: Debian 8
* Game version:  1.1 Windows 10

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
[Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'Core-DimensionsPE v1.0.0': Call to undefined method pocketmine\Player::getDeviceModel() on Core\DPE
[17:32:55] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\Player::getDeviceModel()" (EXCEPTION) in "/plugins/Core/src/Core/DPE" at line 85
[17:32:56] [Server thread/CRITICAL]: Could not execute task Core\Title: Undefined class constant 'TYPE_SET_ANIMATION_TIMES'
[17:32:56] [Server thread/CRITICAL]: Error: "Undefined class constant 'TYPE_SET_ANIMATION_TIMES'" (EXCEPTION) in "/src/pocketmine/Player" at line 3658
```

**Comment by DerddyDert** [comment]
Will you please list your plugins? Keep in mind they may need to be updated to work with mcpe 1.1. On the other hand once Genisyspro is stable they may work.

**Comment by erkam2002** [comment]
You can join 84.200.106.80 Port default

**Comment by erkam2002** [comment]
And inventory open causes crash this sucks :(

**Comment by erkam2002** [comment]
I write my plugins self i used before https://github.com/ExtraCorePE/ExtraCorePE

**Comment by DerddyDert** [comment]
Thanks. You can help genisyspro by forking and doing pull requests.

**Comment by DerddyDert** [comment]
I will test and help ya out later when I get time.

**Comment by DerddyDert** [comment]
@erkam2002 You have been helpful so far. Please join us on [Discord](https://discord.gg/WrKzRNn): https://discord.gg/WrKzRNn

**Comment by DerddyDert** [comment]
What's the status of this @erkam2002

**Comment by erkam2002** [comment]
idk i need to test it

**Comment by erkam2002** [comment]
I test it now

**Comment by erkam2002** [comment]
LOL it works GenisysPro is now very stable good job within 1,5 weeks
