### ISSUE TITLE
DKTAPPS SELLING PUCKET MEIN FOR PROFITS ! ITS HUGE SCAM !

### ISSUE THREAD

**Issue by betty3829** [GenisysPro/GenisysPro#1258]
DKTAPPS IS SELL PMMP FOR PROFITS !

FIRST , HE STEAL PROJECT FROM CREATOR, PERCATX ! HE FORCE EVERYONE SWITCH TO THE PMMP !

THIS CAUSE PMMP SUPPLY DECREASE AND DEMAND INCREASE !!

NOW HE SELL PMMP STOCKS TO APPLE ! OMG ! WE ARE BEING TRICKED !

WE MUST RESTORE POWER BACK TO THE GENISYS PRO , OUR LEAD DEVELOPER DERTDERRDY & SUPERXOINGKONG WILL HELP ! NO USE PMMP ! SCAM! NO !

GENISYSPRO WILL WIN !

@shoghicp our core team , is consistent .

Our team:

Masterofreleans
dertderrdy
pockkiller
leo
AppleDeveloper (helps with the optimization tips and typehints)
fracsis
frago
together , we have discovered a secret math that give us stratigic advantage overthe pmmp . this secret math dertderrdy discover genisyspro pmmp 35%

GENISYSPRO WILL WIN !

**Comment by InspectorGadget** [comment]
Ah? How can he sell an open source project for money?

**Comment by optimusprime338** [comment]
@betty3829 believe me or not but are ass whole dude.. let him sell if he wants too :') .. whats ur problem lmao

**Comment by Ultie0** [comment]
this issue tracker is so cringey

**Comment by MasterOfTheRealm** [comment]
This kid Betty is brain dead... how sad...
