### ISSUE TITLE
玩家可以使用重叠的水桶刷取多桶水/岩浆

### ISSUE THREAD

**Issue by lowingly** [GenisysPro/GenisysPro#13]
这是一个可以在服务器刷水/岩浆的作弊方法，我想应该是服务器bug。

生存模式下：
在地上捡起多个水桶，或者在商店买多个水桶，水桶就会重叠。（比如：6个水桶重叠，仅占一格空间）
使用重叠的水桶点击一格水会获得“6个重叠且装满水的水桶”。（依然只占一个空间）
如果使用“6个重叠且装满水的水桶”直接点击地面，水桶会空，且只会放出一格水。
但是，
如果将“6个重叠且装满水的水桶”放进箱子或者展物栏，就可以将重叠水桶分开（分成6桶装水的水桶，占6个空间）。
这意味着，玩家可以使用这个方法将一格水或岩浆，使用重叠的桶刷成很多格水或者岩浆。（也就是一次获取多格液体）

如果在单机模式就不会有这个bug，因为单机下：使用重叠空水桶（比如6个）点击一格水，会变成5个重叠空水桶和一个装满水的水桶。 

我不太清楚这个是不是服务器可以修的范围，如果可以，就修复一下吧。如果不是服务器的错，那就当我没说= =！

**Comment by SuperXingKong** [comment]
我不太清楚怎么解决这个bug...最近忙于更新1.1.0分支
@LunacyZeus @lightda104530 也许能帮助你 👍

**Comment by lowingly** [comment]
这个问题我有一个想法。让桶和水瓶一致。
你用3个桶打一次水会获得3个装水的桶。
但是你用3个水瓶打一次水只会获得一个装水的水瓶。。
所以把桶改成和水瓶一样。。大概就可以了吧。。

单机的时候水桶和水瓶也是一样的呀。。

**Comment by lightda104530** [comment]
很難說
不過可以試試看

**Comment by SuperXingKong** [comment]
@lightda104530 Thx😄

**Comment by SuperXingKong** [comment]
Nobody wants to fix this?>_<

**Comment by DerddyDert** [comment]
This is complicated. I have seen this in other forks...
