### ISSUE TITLE
点开物品栏服务器客户端崩溃

### ISSUE THREAD

**Issue by baoanony** [GenisysPro/GenisysPro#130]
进入服务器之后点开状态栏客户端直接崩溃 以确认不是客户端的原因

**Comment by erkam2002** [comment]
Took a look at existing issues...

**Comment by DerddyDert** [comment]
I dont know, this one sounds a little different. Ill look into it.

**Comment by Leo3418** [comment]
感谢您的报告，但我们已发现此问题、或其他人已经报告过此问题。(#107)
