### ISSUE TITLE
Client crash when you try to open inventory

### ISSUE THREAD

**Issue by poustmal** [GenisysPro/GenisysPro#131]
Console doesn't give errors and I'm using latest version and I downloaded genisyspro today.

**Comment by caspervanneck** [comment]
dublicate

**Comment by caspervanneck** [comment]
we know you shult first look at issues then make a bug report

**Comment by poustmal** [comment]
I didn't see this issue here.

**Comment by caspervanneck** [comment]
#107

**Comment by poustmal** [comment]
well ok,close
