### ISSUE TITLE
进服还是客户端卡退

### ISSUE THREAD

**Issue by bdeh0** [GenisysPro/GenisysPro#136]
用最新的核心（b902109）进服，显示生成地形中，然后就卡退了
后台没有显示错误

**Comment by bdeh0** [comment]
English：
(I'm using an automatic translator on the Internet. It probably doesn't translate well.)
Client service or client card refund
With the latest core (b902109) into the service, display the generated terrain, and then the card back
There is no error in the background

**Comment by SuperXingKong** [comment]
你的地图是用GenisysPro生成的吗

**Comment by SuperXingKong** [comment]
试试这个
IP: genpro.derddy.com
PORT: 19132
我们的测试服务器

**Comment by bdeh0** [comment]
现在最新的版本 c1cda41 已经没有这个bug了
谢谢！
