### ISSUE TITLE
Client Crash when oping Creative inventory

### ISSUE THREAD

**Issue by alexbgameson** [GenisysPro/GenisysPro#138]
The  Client Crashes every time opening Creative inventory.

**Comment by SuperXingKong** [comment]
What about Survivor inventory?

**Comment by DerddyDert** [comment]
Ill run tests as soon as my schedule allows me. I got big issues going on right now, sorry

**Comment by SuperXingKong** [comment]
Don't be worried. We are all here and ready to help you xD

**Comment by AppleDevelops** [comment]
Very simple fix

**Comment by SuperXingKong** [comment]
We will be happy if you help us. Cloud you please point out where the mistake is or create a request to us? @AppleDevelops

**Comment by SuperXingKong** [comment]
Thank you for your help!

**Comment by SuperXingKong** [comment]
Fixed!
