### ISSUE TITLE
Player Invetory Button Click a Crash Out (Not Server Error)

### ISSUE THREAD

**Issue by TialKorea** [GenisysPro/GenisysPro#139]
#### OS and versions

* Genisys: Latest Build
* PHP: 7.0.3
* Server OS: Linux
* Game version: 1.1.0.x

#### Crashdump, backtrace, memory dumps, plugins list or other files

``` Not Server Error
``` Invetory Button Click Error

**Comment by SuperXingKong** [comment]
Are you using the lastest src?

**Comment by DerddyDert** [comment]
#107
