### ISSUE TITLE
Console warning: Invalid arguments in Server.php on line 382

### ISSUE THREAD

**Issue by armagadon159753** [GenisysPro/GenisysPro#140]
![screenshot_2017-06-15-00-37-11](https://user-images.githubusercontent.com/25569806/27157645-f54d1eb6-5162-11e7-8594-8a6959b4e373.png)

**Comment by DerddyDert** [comment]
On server start and every few seconds this warning is showing in console:
`
Warning: implode(): Invalid arguments passed in /home/genpro/testservers/19132/src/pocketmine/Server.php on line 382
`
