### ISSUE TITLE
Player Server Connection a Server Console Error

### ISSUE THREAD

**Issue by TialKorea** [GenisysPro/GenisysPro#142]
#### Issue description

bug

#### OS and versions

* Genisys: latest build
* PHP: 7.0.6
* Server OS: Linux
* Game version: 1.1.0.x

#### Crashdump, backtrace, memory dumps, plugins list or other files

``` Warning: implode(): Invalid arguments passed in /home/tial/pm/src/pocketmine/Server.php on line 382
``` No Plugin
    No World Name Set
    No Server Start php Re build
No Server Config Set

Server Location Dect Error

**Comment by SuperXingKong** [comment]
Already fixed;)
