### ISSUE TITLE
MobsAIProblem

### ISSUE THREAD

**Issue by aabbcc872** [GenisysPro/GenisysPro#145]
请求添加生物AI开关(包括掉落，移动，自动攻击计算)，或删除未完善的生物AI。经常出现生物AI插件与核心争夺实体控制权的情况，AI插件不能用，核心AI又不好用，实在进退两难。

**Comment by lightda104530** [comment]
We're still working on MobsAI system.
我們正在處理MobsAI系統

**Comment by xinghao2003** [comment]
可以暫時使用PureEntitiesX只需要修改API和些代碼即可使用

**Comment by lightda104530** [comment]
雖然個人不推薦XD但是目前所知沒有更好的AI了

**Comment by aabbcc872** [comment]
@lightda104530 我自己写AI，但是核心计算的重力掉落，动不动卡虚空，我想自己写，只能删核心代码。但核心一直在更新我总不可能每更新一下删一次吧。。。

**Comment by aabbcc872** [comment]
@lightda104530 我自己写AI，但是核心计算的重力掉落，动不动卡虚空，我想自己写，只能删核心代码。但核心一直在更新我总不可能每更新一下删一次吧。。。

**Comment by lightda104530** [comment]
我正在加AI進核心，我會再做修正，但是等我明天畢典完XD

**Comment by lightda104530** [comment]
基本上目前的核心根本沒加上AI

**Comment by jdongel2004** [comment]
Use EntityManager.

**Comment by lightda104530** [comment]
I didn't use t before

**Comment by aabbcc872** [comment]
加了的，在Creative类里面有掉落计算，那玩意在一层方块上移动实体的时候特别容易卡方块然后掉虚空。

**Comment by aabbcc872** [comment]
然后还有一僵尸类里面有点AI。。。不说别的，浪费资源

**Comment by SuperXingKong** [comment]
将会在核心稳定后完善此功能;)

**Comment by DerddyDert** [comment]
@lightda104530 @caspervanneck  Any breakthroughs on this guys?

**Comment by BajanVlogs** [comment]
You can close this for now since this is a work in progress
