### ISSUE TITLE
Any items you cannot craft or un-craft please post here

### ISSUE THREAD

**Issue by CookieCode** [GenisysPro/GenisysPro#147]
i can't craft : Sticks and more...
i can't uncraft : Diamond, Emerald, Redstone, lapis, gold, iron blocks and more...

please fix it :(

**Comment by SuperXingKong** [comment]
Are you using the latest src?

**Comment by CookieCode** [comment]
I have found the solution, i send a commit.

**Comment by SuperXingKong** [comment]
Resolved
