### ISSUE TITLE
PopSound

### ISSUE THREAD

**Issue by LewBr** [GenisysPro/GenisysPro#153]
#### Issue description
PopSound error

#### Steps to reproduce the issue
Why the fuck in 1.1.x are coming some bugs like PopSound? wtf men

#### OS and versions

* Genisys: latest
* PHP: 7
* Server OS: MultiCraft
* Game version: 1.1.0

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
16.06 16:15:16 [Server] Server thread/CRITICAL Could not execute task pg\TimeTask: Undefined class constant 'EVENT_SOUND_POP'
16.06 16:15:16 [Server] Server thread/CRITICAL Error: "Undefined class constant 'EVENT_SOUND_POP'" (EXCEPTION) in "/src/pocketmine/level/sound/PopSound" at line 29
```

**Comment by LewBr** [comment]
This too: 16.06 16:17:34 [Server] Server thread/CRITICAL Error: "Undefined class constant 'EVENT_CAULDRON_EXPLODE'" (EXCEPTION) in "/src/pocketmine/level/sound/ExplodeSound" at line 29

**Comment by SuperXingKong** [comment]
#blame Tesseract 
They changed some constants in LevelEventPacket. I will fix it right now.
