### ISSUE TITLE
Issue:All items build after create is under shadow.

### ISSUE THREAD

**Issue by Ferouden** [GenisysPro/GenisysPro#154]
- Core Ver.: master tag:28d9foa5
- Client Ver.: MCPE V1.1.0.55
- Device: iPhone7 iOS10.3.1
- Server: Windows10 and CentOS7
- Issue Detail: After create the world, all items in the world is under shadow, or being "dark". And the item created by player is in normal.
- Pic: 
![img_0428](https://user-images.githubusercontent.com/19651619/27249493-7329c702-5349-11e7-8947-7931739eb9e4.PNG)
![img_0429](https://user-images.githubusercontent.com/19651619/27249495-7620459e-5349-11e7-936e-737b3a6aa536.PNG)

**Comment by DerddyDert** [comment]
#111
