### ISSUE TITLE
Can not download resource packet

### ISSUE THREAD

**Issue by ldliuzhen** [GenisysPro/GenisysPro#156]
![qq 20170617124438](https://user-images.githubusercontent.com/28777444/27250205-e37919f2-535a-11e7-9377-79684c53b51d.jpg)
![qq 20170617124501](https://user-images.githubusercontent.com/28777444/27250207-e393beec-535a-11e7-8aef-a9c623a9fd0b.jpg)
![qq 20170617124517](https://user-images.githubusercontent.com/28777444/27250206-e3812200-535a-11e7-91b1-6dd2663e7ecd.jpg)

**Comment by DerddyDert** [comment]
Delete old one on server, clear cache and storage on client then update src worked for me.

**Comment by DerddyDert** [comment]
This issue is resolved using steps mentioned and latest src. reopen if you have more trouble.
