### ISSUE TITLE
Error with my plugin about entity and EventEntity

### ISSUE THREAD

**Issue by armagadon159753** [GenisysPro/GenisysPro#158]
![screenshot_2017-06-17-15-34-15](https://user-images.githubusercontent.com/25569806/27253345-fcd6ea1a-5372-11e7-8637-4038b10044de.png)

**Comment by SuperXingKong** [comment]
Send part of your plugin. new PrimedTNT(??)

**Comment by armagadon159753** [comment]
https://youtu.be/OahSAPKGqSY
https://pastebin.com/47ga6NiR

**Comment by SuperXingKong** [comment]
Check line 110. it should be $snowball = Entity::createEntity("PrimedTNT", $player->getlevel(), $nbt);

**Comment by SuperXingKong** [comment]
Check line 110. it should be $snowball = Entity::createEntity("PrimedTNT", $player->getlevel(), $nbt);

**Comment by armagadon159753** [comment]
I test it ^•^ thank you

**Comment by armagadon159753** [comment]
Its working but i dont have explosion sound THANK YOU 👌👍

**Comment by SuperXingKong** [comment]
I will add explosion sound. Thank you for your report xD

**Comment by SuperXingKong** [comment]
I will add explosion sound. Thank you for your report xD

**Comment by DerddyDert** [comment]
Closed this due to #171 was opened as its own issue. Thanks
