### ISSUE TITLE
Lags TPS Low On My Server

### ISSUE THREAD

**Issue by SuperKali** [GenisysPro/GenisysPro#159]
Extreme Lag On My Server By TPS Low
![screenshot_20170617-215422](https://user-images.githubusercontent.com/19473898/27256252-b802bb02-53af-11e7-80fb-75e08fa462c3.jpg)

**Comment by SuperXingKong** [comment]
There may be a memory leak in the core. Can you find them? (Use timings)

**Comment by SuperKali** [comment]
yes

**Comment by SuperKali** [comment]
http://mcpetimings.com/?url=24884422

**Comment by SuperXingKong** [comment]
I will change timings to timings.pmmp.io. Plz wait xD

**Comment by SuperXingKong** [comment]
https://timings.pmmp.io/?url=24884422
Here is your server's status. Try again with the latest src.

**Comment by DerddyDert** [comment]
@SuperKali please update src and close this issue if it is resolved. Thanks!

**Comment by SuperKali** [comment]
Ok

**Comment by SuperKali** [comment]
[Server thread/CRITICAL]: Could not tick level "SkyWarsLast": Call to a member function addSound() on null 
and
[Server thread/CRITICAL]: Could not tick level "SkyWarsLast": Call to undefined method stdClass::isClosed()

**Comment by DerddyDert** [comment]
What's the latest on this @SuperKali ?

**Comment by SuperKali** [comment]
@DerddyDert Yes i use the latest version

**Comment by DerddyDert** [comment]
I hope you get this sorted. We had 0 lag on the test server but maxed at 5 people on at once.

**Comment by SuperKali** [comment]
With pmmp I did not have lag problems. I had only problems loading the chuck

**Comment by MrSmileCH** [comment]
I would like to know the name of the plugin you used?

**Comment by DerddyDert** [comment]
This has to be plugin related. I can't replicate

**Comment by SuperXingKong** [comment]
Similar to #199

**Comment by DerddyDert** [comment]
@SuperXingKong I thought u found the leak? @SuperKali can we get one more test on latest src? Sorry

**Comment by SuperKali** [comment]
ok

**Comment by SuperKali** [comment]
http://timings.pmmp.io/?url=25013902

**Comment by DerddyDert** [comment]
@SuperKali which src did you use? Just give the commit link. Thanks

**Comment by SuperKali** [comment]
the latest version @DerddyDert

**Comment by XDqrkneZ** [comment]
any fix?

**Comment by SuperKali** [comment]
@XDqrkneZ Still not confirmed but I'm testing

**Comment by XDqrkneZ** [comment]
oh good. All they need to fix it Memory Leak and this'll be perfect

**Comment by XDqrkneZ** [comment]
fixed?
