### ISSUE TITLE
音乐盒没声音

### ISSUE THREAD

**Issue by sdochong** [GenisysPro/GenisysPro#16]
音乐盒没声音

**Comment by SuperXingKong** [comment]
我将会尝试修复...这可能需要一段时间的测试和调试😄

**Comment by SuperXingKong** [comment]
@lightda104530 @chadigos @LunacyZeus Can you help test add Noteblock sound😉

**Comment by lightda104530** [comment]
@chadigos  gogo lolol

**Comment by chadigos** [comment]
ok

**Comment by lightda104530** [comment]
@SuperXingKong  Chadigos don't have admin so I just gave him

**Comment by SuperXingKong** [comment]
@lightda104530 Well😄

**Comment by SuperXingKong** [comment]
@sdochong @lightda104530 Chadigos has already fixed this bug, now it is debugging!
@chadigos Wonderful work!

**Comment by chadigos** [comment]
nice😀 fix music box

**Comment by lightda104530** [comment]
If music was fixed, we'll going to close this issues:D

**Comment by SuperXingKong** [comment]
@sdochong Aliready fixed😄Thx for your report

**Comment by aojiaojb** [comment]
iOS听不见...

**Comment by SuperXingKong** [comment]
Really?I test it in my android phone and it works well.
Now reopen this issue and wait for others' test.

**Comment by SuperXingKong** [comment]
@sdochong Don't use plugin like ZMusicBox

**Comment by SuperXingKong** [comment]
音乐盒工作正常🎵
有可能是你安装了不支持的插件

**Comment by xinghao2003** [comment]
正常来说如果核心成功修复声音问题，ZMusicBox插件就能成功运行，某核心修复声音问题然后这个插件也能用

**Comment by SuperXingKong** [comment]
@xinghao2003 ZMusicBox是不支持的插件,它目前只能播放音符(无声音),与核心无关.至于你说的ZMusicBox可能是别人修复的.我测试无插件的服务器音符盒谁正常的.
P.S.感谢您的提醒.如果您觉得仍存在问题,请确保为核心问题并自行测试后回复.欢迎提交issues.

**Comment by xinghao2003** [comment]
@SuperXingKong 我測試下ZMusicBox的確能運行，並且是在這個的核心

**Comment by SuperXingKong** [comment]
@xinghao2003
然而我测试了ZMusicBox,只能发出bass音
虽然这很容易修复,但ZMusicBox目前并不支持

**Comment by xinghao2003** [comment]
怎样说呢，什么是Bass音，但ZMusicBox的确能播放音乐
