### ISSUE TITLE
CookieSoftware stole GenisysPro

### ISSUE THREAD

**Issue by SuperXingKong** [GenisysPro/GenisysPro#160]
# Please don't use shit  SHIT TSP
# No.1 ResourcePack
## PROOF: https://github.com/CookieSoftware/TSP/commit/208768c9ee193c30d051afed4c4927fe0956c7a2#diff-aaee4f21778267b6cafc6c388a281966L15

# No.2 BinarySteam
## All packets handle were copid from old GenisysPro, But you didn't mention it

# No.3 Folder-Plugin-Loader
## PROOF: https://github.com/CookieSoftware/TSP/commit/208768c9ee193c30d051afed4c4927fe0956c7a2#diff-68274b6a783228c83631aaf9dee49327R33

**Comment by SuperXingKong** [comment]
Them even edit my issues

**Comment by DerddyDert** [comment]
What the heck?

**Comment by WadeHandlebar** [comment]
I just want to say MMP！

**Comment by Him188** [comment]
Interesting, emm

**Comment by caspervanneck** [comment]
@SuperXingKong REALY ? they its open soarce

**Comment by SuperXingKong** [comment]
## @caspervanneck They blocked and adused me. 
## They didn't Admit their stealing!!

**Comment by caspervanneck** [comment]
@SuperXingKong i hope they listen to me

https://github.com/CookieSoftware/TSP/issues/46

**Comment by MasterOfTheRealm** [comment]
*sigh*

**Comment by CookieCode** [comment]
Shut up -_- really... I explain me with my language.

J'ai fork Tesseract et c'esr eux qui avait fork GenisysPro, continuez cette embrouille chez eux.

**Comment by caspervanneck** [comment]
@CookieCode wow i cant read speak eng

**Comment by caspervanneck** [comment]
shut up @CookieCode

**Comment by caspervanneck** [comment]
@CookieCode your a big noob

**Comment by DerddyDert** [comment]
Apparently tesseract had the genisyspro code.

**Comment by DerddyDert** [comment]
@CookieCode said he will close his spoon and work with GenisysPro
