### ISSUE TITLE
Noteblock doesnt work right

### ISSUE THREAD

**Issue by DerddyDert** [GenisysPro/GenisysPro#163]
As of Latest commit 3eb0aea  
When hitting note block only one color note works and the sound is the same as picking up a broken block or item from the ground.

**Comment by SuperXingKong** [comment]
Good job (⑉°з°)-♡

**Comment by SuperXingKong** [comment]
This is a sound issue, including #158

**Comment by DerddyDert** [comment]
@SuperXingKong I didnt do any work except testing and thats kinda like playing :-p
