### ISSUE TITLE
Bad Software lagg / Bugs code not optimized.

### ISSUE THREAD

**Issue by wiligangster** [GenisysPro/GenisysPro#169]
Please Read My Title .

**Comment by RateekMCPE** [comment]
@wiligangster Sorry but we will optimize it as soon as possible.

**Comment by caspervanneck** [comment]
@wiligangster shut upp no need to optimise its your plugins

**Comment by wiligangster** [comment]
@caspervanneck skids stop rage and stop say sh"t

**Comment by caspervanneck** [comment]
@wiligangster stop calling me a skids

**Comment by caspervanneck** [comment]
wand jij bent en kanker mogol

**Comment by lightda104530** [comment]
You just talk too much...
If you want to use wait for us we'll finish it as quick as possible
If you don't just leave turn left is the way to exit

**Comment by lightda104530** [comment]
Close issue#169
reason:issue don't need help:P
