### ISSUE TITLE
Bug stairs

### ISSUE THREAD

**Issue by MrSmileCH** [GenisysPro/GenisysPro#173]
Hi, I have a bug, I do not know if it's me, but I can not climb stairs in the game.

**Comment by DerddyDert** [comment]
Stairs or ladders?

**Comment by DerddyDert** [comment]
I think you mean ladder #164  reopen if you have more info please.

**Comment by caspervanneck** [comment]
@DerddyDert  its if you have the player movement cheat on

if you try run on stairs your get a mesage
