### ISSUE TITLE
Lava/water enhancement idea

### ISSUE THREAD

**Issue by DerddyDert** [GenisysPro/GenisysPro#179]
As of, Latest commit 5a79031
Level generated Lava and Water doesnt flow. Place lava/water will flow.

**Comment by MasterOfTheRealm** [comment]
That's weird... the files i changed has no relation with these issues

**Comment by DerddyDert** [comment]
Not related. This is just an enhancement idea. Perhaps an option to enable/disable water flow?

**Comment by caspervanneck** [comment]
@DerddyDert maby some plugins
