### ISSUE TITLE
Sign is glitchy

### ISSUE THREAD

**Issue by DerddyDert** [GenisysPro/GenisysPro#181]
As of Latest commit 5a79031

When using colors, especially 2 colors the sign gets very glitchy.

![screenshot_20170619-023400](https://user-images.githubusercontent.com/18636275/27272768-edb54400-5499-11e7-8366-5d15e5ce2974.jpg)
![screenshot_20170619-023411](https://user-images.githubusercontent.com/18636275/27272784-018b849e-549a-11e7-8cd4-b0cfd59eb33c.jpg)

**Comment by MasterOfTheRealm** [comment]
#BlameMojang

**Comment by DerddyDert** [comment]
Of course it's their fault. Maybe it can be fixed as it works in MCPE?

**Comment by Leo3418** [comment]
This is a client bug.
<img width="567" alt="untitled" src="https://user-images.githubusercontent.com/14175175/29008577-e776934a-7b4b-11e7-8a02-a92ff58b677d.png">
