### ISSUE TITLE
Boats

### ISSUE THREAD

**Issue by DerddyDert** [GenisysPro/GenisysPro#182]
As of Latest commit 5a79031

Player isn't positioned in boat correctly.

![screenshot_20170619-015645](https://user-images.githubusercontent.com/18636275/27272888-8b41bbfe-549a-11e7-88af-58203f7b928a.jpg)
![screenshot_20170619-023824](https://user-images.githubusercontent.com/18636275/27272891-928cc41c-549a-11e7-82a1-917f569febc6.jpg)

**Comment by erkam2002** [comment]
haha lol

**Comment by erkam2002** [comment]
What is the server ip?

**Comment by MasterOfTheRealm** [comment]
genpro.derddy.com
