### ISSUE TITLE
Lose players backpack玩家丢失物品

### ISSUE THREAD

**Issue by hzy2003** [GenisysPro/GenisysPro#19]
#### Issue description

玩家丢失物品，不丢失盔甲
#### OS and versions

* Genisys:latest
* PHP:php7
* Server OS:CentOS7.2
* Game version: 1.0.5-1.0.7

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```nothing in log

**Comment by hzy2003** [comment]
@SuperXingKong

**Comment by Leo3418** [comment]
感谢您的报告，但您提供的信息不足，无法帮助我们确定或解决此问题。请提供更多与此问题相关的细节，例如您安装的插件、可复现此 bug 的操作步骤、等等。否则，我们可能会关闭此 issue。

**Comment by hzy2003** [comment]
插件：simpleauth
Essentials 
Economy 
WorldProtect
Taptodo
此bug在1.0.5-1.0.7均可重现
随机在登录完成后清空背包(不包括盔甲栏物品)

**Comment by lightda104530** [comment]
@chadigos  @SuperXingKong  只有我覺得登入之類的封包壞掉嗎lol

**Comment by lowingly** [comment]
说真的不只这个核心，我用的其他核心也出现了这个问题，比如进服后玩家背包物品消失或掉在地上。
很难重现，因为是偶尔发生。

**Comment by SuperXingKong** [comment]
问题原因暂时无法确定，我们需要一段时间的测试

**Comment by SuperXingKong** [comment]
You can test it and report to us @hzy2003 
Remember use the lastest commit😄

**Comment by SuperXingKong** [comment]
And If it works well, don't forget to close this issue and @me😄
Thx for your report! @hzy2003

**Comment by hzy2003** [comment]
It's seems well now.
Thx
@SuoerXingKong
I close this issue.

**Comment by chadigos** [comment]
0.0

**Comment by chadigos** [comment]
这应该是插件的问题

**Comment by lightda104530** [comment]
@chadigos 我說過了XD

**Comment by hzy2003** [comment]
sorry to reopen this issue
Someone had same problem again.
The latest GenisysPro and simpleauth.

**Comment by SuperXingKong** [comment]
I have no thought
Can you help @lightda104530

**Comment by Norman300** [comment]
是这样的。而且一旦一个玩家出现过一次物品消失就没完了，重复消失物品
只有0次和n次

**Comment by xinghao2003** [comment]
@lightda104530 我也認為是封包問題

**Comment by chadigos** [comment]
@hzy2003 一进服背包清空？？

**Comment by hzy2003** [comment]
@chadigos
登录之后，背包清空

**Comment by SuperXingKong** [comment]
@lightda104530 @chadigos 也许重写背包保存系统可以解决这个问题

**Comment by SuperXingKong** [comment]
暑假我会尝试解决,目前由于手机被没收无法更新（#笑）

**Comment by hzy2003** [comment]
听到这个消息很是悲伤
因为我也是这样被没收手机
也许中考过后回来吧
@SuperXingKong

**Comment by lightda104530** [comment]
@SuperXingKong  I'll try:D

**Comment by SuperXingKong** [comment]
这不是一个bug,而是由于服务器丢包引起.
如果您的服务器经常丢包,请编辑pocketmine.yml设置更高的压缩程度.同时我们也会对核心功能做一些优化.
