### ISSUE TITLE
Update README.md to add French Dutch and Russian

### ISSUE THREAD

**Issue by armagadon159753** [GenisysPro/GenisysPro#190]
https://pastebin.com/e27Hds4n

**Comment by DerddyDert** [comment]
can you send it in discord then someone with access can update. thanks @armagadon159753

**Comment by Bruno99** [comment]
https://pastebin.com/TwcdvLMf - Support Russian language

**Comment by DerddyDert** [comment]
Awesome. Thanks

**Comment by SuperXingKong** [comment]
Great 👍 @lightda104530 Can you help merge these changes? I don't have a computer beside~

**Comment by DerddyDert** [comment]
And dutch @caspervanneck

**Comment by lightda104530** [comment]
?

**Comment by caspervanneck** [comment]
@DerddyDert  @lightda104530  dutch translate done

**Comment by DerddyDert** [comment]
@caspervanneck thanks buddy. Can you take those French and Russian links and add them as well?

**Comment by Frago9876543210** [comment]
@Bruno99 I corrected some shortcomings
https://pastebin.com/6ipk3wQc

**Comment by BajanVlogs** [comment]
think this was added close this issue plz
