### ISSUE TITLE
Chunks not loading

### ISSUE THREAD

**Issue by Prisane** [GenisysPro/GenisysPro#197]
#### Issue description

Chunks are not loaded when after respawn you die. And sometimes chunks are not loaded on world.
Teleport to another world in to correct and it is necessary to go back again world

#### OS and versions
* Genisys: [5d3e165](https://github.com/GenisysPro/GenisysPro/commit/5d3e165851680a7a9bd06826116b383c109f07b3)
* PHP: 7 
* Server OS: lunix
* Game version: 1.1.0.52

#### Crashdump, backtrace, memory dumps, plugins list or other files
It's what happens when I die. 
![ekran alintisi](https://user-images.githubusercontent.com/13530796/27353202-e0402d30-560b-11e7-843d-e4ae4b050188.PNG)

**Comment by erkam2002** [comment]
Its an client bug https://bugs.mojang.com/browse/MCPE-22739

**Comment by Prisane** [comment]
Is there any temporary solution?

**Comment by DerddyDert** [comment]
@Prisane hey buddy, did you by chance not preload the worlds in pocketmine.yml? I cannot replicate this issue on the official test server.

**Comment by Prisane** [comment]
i think originated from genisys pro @DerddyDert

**Comment by Prisane** [comment]
I also suggest you do some research. This bug is separate with the client bug because client bug does not have chunk installed just in some part of the world.

**Comment by Prisane** [comment]
I have disabled all plugins, but the problem still persists! @DerddyDert

**Comment by Prisane** [comment]
I think this is an anvil bug.

**Comment by DerddyDert** [comment]
we got another of the identical issue posted closer to the top. I will close this one and we will work from #235
