### ISSUE TITLE
 Does it affect these warnings at all?

### ISSUE THREAD

**Issue by MrSmileCH** [GenisysPro/GenisysPro#198]
20.06 16:51:52 [Server] INFO Notice: Undefined offset: 2 in phar:///custom-phar.phar/src/pocketmine/network/protocol/LoginPacket.php on line 153
20.06 16:51:52 [Server] INFO Notice: Undefined offset: 1 in phar:///custom-phar.phar/src/pocketmine/network/protocol/LoginPacket.php on line 153
20.06 16:51:52 [Server] INFO Warning: unpack(): Type V: not enough input, need 4, have 0 in phar:///custom-phar.phar/src/pocketmine/utils/Binary.php on line 237
20.06 16:51:52 [Server] INFO Notice: Trying to get property of non-object in phar:///custom-phar.phar/src/pocketmine/network/protocol/LoginPacket.php on line 70

**Comment by SuperXingKong** [comment]
Not hack properly >_<

**Comment by DerddyDert** [comment]
@SuperXingKong I havent seen this. Latest src on test server now

**Comment by DerddyDert** [comment]
This may be fixed or is now invalid. Open and elaborate your issue if you continue to have issues using the latest src.
