### ISSUE TITLE
 Too lag on server

### ISSUE THREAD

**Issue by MrSmileCH** [GenisysPro/GenisysPro#199]
![sin titulo](https://user-images.githubusercontent.com/27845246/27361464-1bc00732-55ed-11e7-805c-0c1614a5ee33.png)
![sin titulo1](https://user-images.githubusercontent.com/27845246/27361468-21bdf5cc-55ed-11e7-8df4-62f6634dc568.png)

**Comment by SuperXingKong** [comment]
Do you know where the memory leak is:? @DerddyDert @MasterOfTheRealm @lightda104530 @caspervanneck @Frago9876543210

**Comment by SamyR0** [comment]
what's your cpu and how many plugins do you have?

**Comment by SamyR0** [comment]
try disable all the maps and see if it from them , or maybe because are too many players on a current world, i dont know.

**Comment by SamyR0** [comment]
It can be a lots of reasons , that's why it is a pretty hard. I see that he also has 70 players and if he doesnt have an good hardware support, also with that maps , it can be a pretty laggy.

**Comment by SuperKali** [comment]
i have this problem #159 

I do not think it's the server issue but the software side itself
![12](https://user-images.githubusercontent.com/19473898/27380539-c60ef526-567f-11e7-8d41-d8376cf734b8.PNG)

**Comment by SuperKali** [comment]
@MrSmileCH 
Try using these settings on pocketmine.yml


[pocketmine.zip](https://github.com/GenisysPro/GenisysPro/files/1091265/pocketmine.zip)

**Comment by SamyR0** [comment]
kvm is better for mcpe btw ;)

**Comment by SuperKali** [comment]
nope

**Comment by MrSmileCH** [comment]
10 GB
RAM
Unlimited Slots
Unlimited Storage
Unlimited Bandwidth
+ Dedicated IP

My server has 85 slots and 44 plugins is always full, in the previous version 1.0.9 I was going perfectly, but in this new version goes too lag with either genisyspro or tesseract

**Comment by SuperKali** [comment]
@MrSmileCH I agree, even in the old version I had no problems

**Comment by DerddyDert** [comment]
Test with new src and reopen if you are still the same. Also how many cores do you have?
