### ISSUE TITLE
多个登录插件使用mysql登录时报错并无法正常运行

### ISSUE THREAD

**Issue by Norman300** [GenisysPro/GenisysPro#20]
包括Simpleauth，HereAuth，PiggyAuth，MyAuth
 配置文件输入完全正确，刚开服时进服可以正常注册登录，数据库中也储存了信息，过一段时间后再进服就无法操作并后台报错，以MyAuth最新版为例：
**Warning:mysqli::query(): Error reading result set's header in phar://服务器路径/plugins/MyAuth.phar/src/MyAuth/Datanase/.php on line 69**
**[Server thread/CRITICAL]:: "Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to MyAuth vv1.2.1 ':Call to a member function fetch_assoc() on boolean on MyAuth\EventListener**
**[Server thread/CRITICAL]:: Error: "Call to a member function fetch_assoc() om boolean" (EXCEPTION) in "MyAuth.phar/src/MyAuth/Database/MySQLDatabase" at line 70**

**Comment by Norman300** [comment]
在这之前还有一条
Warning: mysqli::query(): MySQL server has gone away in pha
://服务器路径/plugins/MyAuth.phar/src/MyAuth/Databas
/MySQLDatabase.php on line 69

**Comment by lightda104530** [comment]
那基本上是插件內部的問題
如果是使用本核心才出現的問題我們會嘗試進行修復作業

**Comment by SuperXingKong** [comment]
请尝试该解决方案

> 解决方案:
修改端口为3306
