### ISSUE TITLE
Bug DisconnectPacket

### ISSUE THREAD

**Issue by SuperKali** [GenisysPro/GenisysPro#205]
* Genisys: latest
* PHP: 7.0.16
* Server OS: Debian 8 x86_64
* Game version: WINDOWS 10 EDITION

 Just use the /stop command not check the message "server closed"

* https://youtu.be/2g1nI3ZUwFY

**Comment by caspervanneck** [comment]
yes thats a bug

**Comment by SuperKali** [comment]
Not fixed
![screenshot_20170626-111245](https://user-images.githubusercontent.com/19473898/27532452-a9c9f886-5a60-11e7-8170-053d653aa5c1.jpg)
![screenshot_20170626-111245](https://user-images.githubusercontent.com/19473898/27532453-a9cba82a-5a60-11e7-9478-82d28be5e3ff.jpg)

**Comment by caspervanneck** [comment]
its your hosting and wifi @SuperKali

**Comment by SuperKali** [comment]
Check out my @Speedtest result! How fast is your internet? http://www.speedtest.net/my-result/a/2934489472
My hosting have 1 gigabit

**Comment by RateekMCPE** [comment]
https://github.com/GenisysPro/GenisysPro/pull/243 
Fix @SuperKali

**Comment by caspervanneck** [comment]
@SuperKali @erkam2002  @RateekMCPE its working for me and i have a bad vps wel little bit good

**Comment by caspervanneck** [comment]
i tested on windows 10 and android and ios

**Comment by erkam2002** [comment]
lol

**Comment by amirabas** [comment]
Please find a solution to this problem
It's not just Stops, Kick and Bunnies, but also plugins similar to WhitelistReason
