### ISSUE TITLE
1.1.1 version bug please fix , hurry

### ISSUE THREAD

**Issue by SuperAdam47** [GenisysPro/GenisysPro#206]
https://youtu.be/aHG3EuuYphA

**Comment by MasterOfTheRealm** [comment]
@SuperAdam47 disable all your plugins and try

**Comment by SuperAdam47** [comment]
Add plugin support

**Comment by MasterOfTheRealm** [comment]
@SuperAdam47 was the bug there after you removed the plugins?

**Comment by DerddyDert** [comment]
Can't support a plugin till you find out which plugin has an issue

**Comment by SuperAdam47** [comment]
Yes removed @MasterOfTheRealm

**Comment by MasterOfTheRealm** [comment]
@SuperAdam47 Find the plugin which causes the issue so we can perhaps support it

**Comment by SuperAdam47** [comment]
Ok finding.. @MasterOfTheRealm
