### ISSUE TITLE
Resource Packs not work

### ISSUE THREAD

**Issue by SuperKali** [GenisysPro/GenisysPro#207]
* Genisys: latest
* PHP: 7.0.16
* Server OS: Debian 8 x86_64
* Game version: Android 

* i have tested on my server and not work, with pmmp works

![photo_2017-06-21_17-57-46](https://user-images.githubusercontent.com/19473898/27394071-311f4eb2-56ab-11e7-8151-b8a2b08c8f65.jpg)

**Comment by caspervanneck** [comment]
How to anable them @SuperKali  idk how

**Comment by SuperKali** [comment]
Error On Loading Texture In Format .mcpack

[11:02:38] [Server thread/CRITICAL]: InvalidStateException: "无法加载材质包 C:\Users\super\Documents\GenisysPro\resource_packs\\803_dandelion4.mcpack: 找不到主类" (EXCEPTION) in "/src/pocketmine/resourcepacks/ZippedResourcePack" at line 7

**Comment by erkam2002** [comment]
facepalm

**Comment by SuperXingKong** [comment]
I created a branch to resolve it.

**Comment by SuperKali** [comment]
ok @SuperXingKong

**Comment by SuperXingKong** [comment]
The branch's network-issues-fixing xD

**Comment by SuperKali** [comment]
@SuperXingKong https://giphy.com/gifs/3oKIPowDvPHkeE3wCA
