### ISSUE TITLE
方块有几率不被破坏(The box has a chance to destroy)

### ISSUE THREAD

**Issue by bdeh0** [GenisysPro/GenisysPro#212]
如果挖方块，创造和生存都是，有几率不被破坏(If you dig box, create and live are likely not destroyed)
那个方块不会显示了，但如果重新进服，或者在那个位置再放一个方块，就又显示了(The box is not displayed, but if back into the service, or in that position and then put a box, it shows)
用的是ce69f74的核心(Use the ce69f74 core)

**Comment by TDMidkwhatisxd** [comment]
i don't understand ...

**Comment by lightda104530** [comment]
那是回朔吧@@

**Comment by TDMidkwhatisxd** [comment]
Can you tell me what he is saying? If u put a box, it glich and if relogin is fixed? And what is box? xd

**Comment by bdeh0** [comment]
I'm using an automatic translator on the Internet. It probably doesn't translate well.

**Comment by bdeh0** [comment]
@TDMidkwhatisxd box should be block

**Comment by bdeh0** [comment]
@TDMidkwhatisxd "box" should be "block"

**Comment by SuperXingKong** [comment]
服务器延迟？

**Comment by SuperXingKong** [comment]
服务器延迟？

**Comment by xinghao2003** [comment]
这通常是延迟，这经常发生在我的伺服器，破化方块后等于没被破坏或者破坏后会延迟发出破坏的声音和粒子，通常后者经常发生

**Comment by bdeh0** [comment]
经常是破坏了一个方块，然后过了好长时间，退出之后再进，结果再进的时候发现那个方块还在那

**Comment by DerddyDert** [comment]
@lightda104530 can we get a good English description of this issue so more people can try to fix it? thanks

**Comment by bdeh0** [comment]
这个好像是我的服务器主机的问题，现在版主已经给解决了
谢谢
