### ISSUE TITLE
传送到别的世界时出生点附近不加载(Sent to other world born near the point of loading)

### ISSUE THREAD

**Issue by bdeh0** [GenisysPro/GenisysPro#213]
传送到别的世界时，出生点附近的方块还是原来的世界的，但只是显示方块的样子，就是说，你能穿透它(Transfer to another world, was born near the square or the original world, but only show square appearance, that is to say, you can go through it)
如果在那里放一个方块，方块周围大概10格的地方就正常了(If you put a box in a box around there, about 10 local normal lattice)
用的是ce69f74的核心(Use the ce69f74 core)

**Comment by bdeh0** [comment]
I'm using an automatic translator on the Internet. It probably doesn't translate well.

**Comment by SuperXingKong** [comment]
这是一个发包问题

**Comment by SuperXingKong** [comment]
我还没来的及处理 '_'

**Comment by xinghao2003** [comment]
这个会不会是渲染出错？记得官方MOJANG的BUG汇报那边有说1.1多世界CHUNK渲染有问题

**Comment by SuperXingKong** [comment]
应该是少了一个发包吧...具体要等暑假试试xD

**Comment by DerddyDert** [comment]
Is this the same as #235 @SuperXingKong @lightda104530

**Comment by bdeh0** [comment]
这个bug已经不存在了，谢谢
