### ISSUE TITLE
怎么只有白色的床？(How is the only white bed?)

### ISSUE THREAD

**Issue by bdeh0** [GenisysPro/GenisysPro#214]
创造模式的物品栏里有16个白色的床，全都是白色的(Create 16 white bed model items, are all white)
用/give指令也得不到彩色的床，只有355:0的白床，输入355:1也是白床(To use the /give command to the color of the bed, only 355:0 of the white bed, the input 355:1 is also a white bed)
生存也合成不了彩色的床，白床跟染料合成的话得到的还是白床(Life is not a bed of synthetic color, white or white bed with bed if the synthesis of dyes)
用的是ce69f74的核心(Use the ce69f74 core)

**Comment by bdeh0** [comment]
I'm using an automatic translator on the Internet. It probably doesn't translate well.

**Comment by lightda104530** [comment]
我們正在努力嘗試修復這個問題:D

**Comment by XxParkerGamesxX** [comment]
ill be fixing this today

**Comment by DerddyDert** [comment]
Whats the status of this @XxParkerGamesxX @lightda104530

**Comment by SuperXingKong** [comment]
Wait for my commit

**Comment by Prisane** [comment]
@SuperXingKong 
`Fatal error: Declaration of pocketmine\block\Bed::getDrops(pocketmine\item\Item $item) must be compatible with pocketmine\block\Block::getDrops(pocketmine\item\Item $item): array in C:\Users\Baybars\Desktop\www\src\pocketmine\block\Bed.php on line 0
`

**Comment by SuperKali** [comment]
![photo_2017-06-28_16-32-37](https://user-images.githubusercontent.com/19473898/27642558-7452b3ee-5c1f-11e7-93b6-8848bc16c11c.jpg)
