### ISSUE TITLE
cant join server

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [GenisysPro/GenisysPro#216]
Just migrated from pmmp to genysispro, but nobody, even me cant join game.
It say loading, then game crash, and in console, all timeout. 

On pmmp works fine btw... Imma check other forks, if no work , I'm back to pmmp :/

I use latest version from circle.

**Comment by Prisane** [comment]
Your pureperms update.

**Comment by TDMidkwhatisxd** [comment]
ohh, thanks. Imma check

**Comment by TDMidkwhatisxd** [comment]
I use 1.40  is there a new version?

**Comment by TDMidkwhatisxd** [comment]
i have latest pureperms, what version should i use?

**Comment by TDMidkwhatisxd** [comment]
thanks
