### ISSUE TITLE
Please add 'transferserver' command

### ISSUE THREAD

**Issue by jdongel2004** [GenisysPro/GenisysPro#22]
#### Issue description
 add transferserver command plz.

#### Steps to reproduce the issue
 GenisysPro has transfer command. But It has not transferserver command. Please add this command.

#### OS and versions

* Genisys: GenisysPro lastest version ( I don't know how I can find this?)
* PHP: 7.0.18
* Server OS: Ubuntu 16.10
* Game version: 1.0.7

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Leo3418** [comment]
Thanks for the suggestion. SuperXingKong has now implemented it in commit e824635d9be4851b141ecec8b2d8b3c81e2c5ea0.
