### ISSUE TITLE
Chests not working in game

### ISSUE THREAD

**Issue by TestV2** [GenisysPro/GenisysPro#221]
Hi
When playing at Skywars Team or SurvivalGames, the chest will not open when the game starts
But ops can be easily opened
Is there a problem with Genisys.yml?
Of course, limited-creative is false

**Comment by MasterOfTheRealm** [comment]
This must be a plugin issue

**Comment by MasterOfTheRealm** [comment]
Oh i just remembered something when i used to make skywars games.
Please set spawn protection in server properties to 0.
else it blocks chests being opened by normal players.
