### ISSUE TITLE
1.1.1无法进服(1.1.1 cannot enter service)

### ISSUE THREAD

**Issue by bdeh0** [GenisysPro/GenisysPro#222]
1.1.1进服时，会一直显示“正在与服务器同步资源包”
如果一直等的话，会显示“正在从服务器断开连接”
核心版本：0261678
1.1.1 into the service, will always show "is synchronization with the server resource kit"
If so, will show "disconnecting from server"
The core version: 0261678

**Comment by SuperXingKong** [comment]
Use network-issues-fixing branch

**Comment by SuperXingKong** [comment]
Try again and report it xD
