### ISSUE TITLE
Slab glitch, Block Breaking Animation & Bucket of Lava Glitch

### ISSUE THREAD

**Issue by TacosYum** [GenisysPro/GenisysPro#229]
For some reason I get teleported a block back when stepping on a slab and there's no breaking animation for breaking blocks and furnaces take your bucket when you put a bucket of lava as fuel

**Comment by XxParkerGamesxX** [comment]
@TacosYum can u maybe make a video of the problem then post it on yt and upload the link here thanks :)

**Comment by DerddyDert** [comment]
First one to fix, enable movement cheat. Use a third part plugin or wait until we add that feature. Second one, please list which blocks have no animation. (I cannot recreated on test server using latest src) Im going to close and rewrite this clearly
