### ISSUE TITLE
Chunks do not load when the world changes

### ISSUE THREAD

**Issue by SuperAdam47** [GenisysPro/GenisysPro#235]
![screenshot_20170625-195008](https://user-images.githubusercontent.com/16169771/27518077-0a426e72-59e0-11e7-9b2d-86ba83f82b68.png)

AND

![screenshot_20170625-192913](https://user-images.githubusercontent.com/16169771/27518080-1858a2a6-59e0-11e7-93f6-65f20a75f5c9.png)

**Comment by erkam2002** [comment]
Serverin ips ne? yaz bi buraya

**Comment by SuperAdam47** [comment]
Facebook: @MineDogsPE serverin ip si yakinda vericez

**Comment by erkam2002** [comment]
Tmm

**Comment by SuperAdam47** [comment]
Twitterde etme oraya bişeyler pek atmiyoruz facebook tan gel

**Comment by SuperAdam47** [comment]
Can you fix this @SuperXingKong

**Comment by erkam2002** [comment]
tmm

**Comment by DerddyDert** [comment]
Are these worlds preloaded in the yml?

**Comment by SuperXingKong** [comment]
I will try

**Comment by SuperAdam47** [comment]
@dktapps has fixed this error for PocketMine.

**Comment by SuperAdam47** [comment]
https://github.com/pmmp/PocketMine-MP/commit/1dd8fc008bfb3d5a6b8d67291e5ecb34c7797fe9

**Comment by SuperXingKong** [comment]
@SuperAdam47 Thanks!!

**Comment by SuperAdam47** [comment]
or https://github.com/pmmp/PocketMine-MP/commit/71302b230c551af4151cdb9995a8603964393c02 @SuperXingKong

**Comment by SuperAdam47** [comment]
can you fix it? @SuperXingKong

**Comment by SuperAdam47** [comment]
waiting for fix...

**Comment by SuperXingKong** [comment]
Great. I need a computer...(I will try use mobile phone to fix it)

**Comment by SuperAdam47** [comment]
You can use this program to write code https://play.google.com/store/apps/details?id=com.henrythompson.quoda&hl=en

**Comment by SuperAdam47** [comment]
İts new https://github.com/pmmp/PocketMine-MP/commit/394f4200597f6061bf5b92e748532531ae2479a7 @SuperXingKong  @DerddyDert

**Comment by BajanVlogs** [comment]
still an issue this needs to be fixed

**Comment by SuperAdam47** [comment]
I guess this teleportation bug

**Comment by SuperAdam47** [comment]
See https://github.com/pmmp/PocketMine-MP/pull/1100/files

**Comment by SuperXingKong** [comment]
@SuperAdam47 Thanks, I am trying to fix it.

**Comment by Leo3418** [comment]
#623 duplicates this issue, but since that issue was opened more recently, this issue is being closed.
