### ISSUE TITLE
player stuck

### ISSUE THREAD

**Issue by StormCraftMCPE** [GenisysPro/GenisysPro#24]
#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by MCNationPE** [comment]
Are you using the latest version?

**Comment by SuperXingKong** [comment]
@MCNationPE It is caused by anti-MovementCheat. I recommend to remove it.
If you accept it, please type 👍
If you against it, please type 👎
@chadigos @lightda104530 @Leo3418

**Comment by MCNationPE** [comment]
👍 because he say to me he stuck when flying

**Comment by Leo3418** [comment]
I don't think the anti-MovementCheat actually works.
