### ISSUE TITLE
ResourcePacket can download but no effect

### ISSUE THREAD

**Issue by ldliuzhen** [GenisysPro/GenisysPro#240]
#### Issue description

Server can send resourcepacket to player,but when player into the server...There is not change ,the resourcepacket seems doesn't work

#### OS and versions

* Genisys: 1.1
* PHP: 7
* Server OS: WindowsServer 2008
* Game version: 1.1.1

**Comment by DerddyDert** [comment]
So the player gets the resource pack but its not being used?

**Comment by ldliuzhen** [comment]
@DerddyDert yes, the resource packet already into the player's download buffer memory

**Comment by DerddyDert** [comment]
Ok seems like its just not being applied in the server. Unfortunately I know nothing about resource packs. Others will help when they get online.

**Comment by SuperXingKong** [comment]
Packets handle...

**Comment by DerddyDert** [comment]
I'm closing this because to many duplicates and a solution is already discovered by @SuperXingKong
