### ISSUE TITLE
mobs are floating

### ISSUE THREAD

**Issue by caspervanneck** [GenisysPro/GenisysPro#249]
-----Server information-----
This server is running GenisysPro-1.1dev LlamaSpit
 PHP version: 7.0.20
API: 3.0.1
Minecraft PE v1.1.0.9,v1.1.0.55,v1.1.1,v1.1.2
Protocol version: 113

no erors or crashing its strange

**Comment by SuperXingKong** [comment]
What?

**Comment by erkam2002** [comment]
Rejoin server client bug

**Comment by caspervanneck** [comment]
aaa
