### ISSUE TITLE
Respawn bug

### ISSUE THREAD

**Issue by andris155** [GenisysPro/GenisysPro#251]
#### Issue description

Respawn bug

#### Steps to reproduce the issue

https://www.youtube.com/watch?v=5cgq4UgCnnY

#### OS and versions

* Genisys: https://github.com/GenisysPro/GenisysPro/tree/af429cc344cc100cee8a55e9172f33e1b20d48ab
* PHP: 7.0.18
* Server OS: Ubuntu 16
* Game version: 1.1.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
none
```

**Comment by DerddyDert** [comment]
Which src are you using?

**Comment by andris155** [comment]
https://github.com/GenisysPro/GenisysPro/tree/af429cc344cc100cee8a55e9172f33e1b20d48ab

**Comment by DerddyDert** [comment]
This happens if you die while flying or die in void.

**Comment by DerddyDert** [comment]
@SuperXingKong you fixed this before I thought but it happens under some other conditions.

**Comment by SuperXingKong** [comment]
idk. I cannot conntect to YOUTUBE <_<. Chinese GTW...

**Comment by DerddyDert** [comment]
Using the latest commit 0510ed1  I cannot replicate this under any circumstance. This is a plugin issue perhaps. Please find out which plugin is causing this and make a new issue.
