### ISSUE TITLE
卡生成地形(Still generating worlds)

### ISSUE THREAD

**Issue by azon0320** [GenisysPro/GenisysPro#257]
#### Issue description

客户端进去后一直生成地形, 除了这个没有其他异常现象

#### OS and versions

* Genisys: 1.1dev
* PHP: 7.0.3
* Server OS: Linux
* Game version: 1.1.0.55

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by DerddyDert** [comment]
#235
