### ISSUE TITLE
Resource pack

### ISSUE THREAD

**Issue by majovec** [GenisysPro/GenisysPro#258]
How to add resource pack on server please help

**Comment by SuperKali** [comment]
similiar #240

**Comment by SuperXingKong** [comment]
Read /resourcepacks/resource_packs.yml
P.S. It's Chinese so it need to translate later. And resourcepacks can DownloadBut no effect as #240. I will Handle it.

**Comment by DerddyDert** [comment]
@SuperXingKong if it only needs to be translated can you assign someone like @lightda104530 to translate it and commit if you don't get a chance to do this soon? Im sure many server owners patiently waiting for this to work :) Thanks

**Comment by majovec** [comment]
Add resourcepacky.yml and all resourcepack protocol from pmmp and nice work

Dne 2. 7. 2017 0:02 napsal uživatel "DerddyDert" <notifications@github.com>:

**Comment by majovec** [comment]
No is resource pack work ?

**Comment by DerddyDert** [comment]
@SuperXingKong did you finish this yet?

**Comment by majovec** [comment]
for work add all resource pack source form pmmp src/pocketmine/network/mcpe/protocol/ 

 and resource pack.yml from pmmp ....
