### ISSUE TITLE
World Generator bug

### ISSUE THREAD

**Issue by Crypt97** [GenisysPro/GenisysPro#259]
#### Issue description
World generation generates dark grass.

#### Steps to reproduce the issue
- start server
- look at world

#### OS and versions

* Genisys: https://github.com/GenisysPro/GenisysPro/tree/af429cc344cc100cee8a55e9172f33e1b20d48ab
* PHP: 7.0.18
* Server OS: Ubuntu 16
* Game version: 1.1.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

![27253999-5b5ca28a-537f-11e7-9863-c33dbfc397df](https://user-images.githubusercontent.com/28710769/27639449-846c7d22-5c16-11e7-9157-42c259c391ad.png)

**Comment by andris155** [comment]
*light bug

**Comment by SuperKali** [comment]
similar #111

**Comment by SuperXingKong** [comment]
Known issue

**Comment by DerddyDert** [comment]
I love the added arrows!
