### ISSUE TITLE
Items drop after crafting and possible duplication.

### ISSUE THREAD

**Issue by armagadon159753** [GenisysPro/GenisysPro#265]
When i have wood in  m'y hand( 10blocks) and  go craft stick on Crafting table other items drops

**Comment by DerddyDert** [comment]
I've seen this but I didn't count. We need to get items to stop dropping after crafting.

**Comment by BajanVlogs** [comment]
was this on Windows 10 or PE

**Comment by armagadon159753** [comment]
I tested several times on PE 
The bug is not systematic

Idk for w10

**Comment by Pizzahaet** [comment]
Sounds like the bug with enchanting caused by mcpe not sending enchant table and anvil packets. I am going to take a look, I may be wrong but I feel like there is something missing for crafting I am not sure 100% though...

**Comment by MasterOfTheRealm** [comment]
Does this happen on both Pocket and Classic GUI?

**Comment by DerddyDert** [comment]
@MasterOfTheRealm people dont understand that. Haha ill test it out more
