### ISSUE TITLE
Tile

### ISSUE THREAD

**Issue by oGalatico** [GenisysPro/GenisysPro#266]
#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by oGalatico** [comment]
createTile erro help ;-;

**Comment by erkam2002** [comment]
Error code?

**Comment by oGalatico** [comment]
Yes

**Comment by erkam2002** [comment]
Send it

**Comment by oGalatico** [comment]
What ?

**Comment by DerddyDert** [comment]
@oGalatico we need error codes and crash dumps

**Comment by DerddyDert** [comment]
Reopen if you can provide error codes our crash dump

**Comment by caspervanneck** [comment]
@oGalatico yes i open it fi give a eror or a crashdump

**Comment by oGalatico** [comment]
![screenshot_20170629-144033](https://user-images.githubusercontent.com/18704329/27702046-27ceb6f2-5cd9-11e7-8a33-ab6f10cca590.png)

**Comment by DerddyDert** [comment]
Can u upload crash dump?

**Comment by oGalatico** [comment]
Is not crush I can not open any chest Tile in this API and I do not know why it can help me?

**Comment by SuperXingKong** [comment]
Outdated plugin. createTile must be an instance of Level, not Chunk
