### ISSUE TITLE
Make devtools compatible with genisys pro

### ISSUE THREAD

**Issue by poustmal** [GenisysPro/GenisysPro#268]
I can't make a pocketmine.phar file with pocketmine devtools,I tried to changed \network\mcpe\protocol to \network\protocol but devtools was like before.I want to change software.

**Comment by poustmal** [comment]
I can't use src file in the host Im using

**Comment by erkam2002** [comment]
Download .phar

**Comment by erkam2002** [comment]
https://gitlab.com/GenisysPro/GenisysPro/-/jobs/19729520/artifacts/download

**Comment by poustmal** [comment]
Ok works,but on my normal server I have puperms and this version from gitlab hasn't the fix update for pureperms and I will have sure crash when I will try to join

**Comment by DerddyDert** [comment]
If someone can't getyou a phar ill get you one tonight after work

**Comment by SuperXingKong** [comment]
DevTools functions alreay include in the SRC

**Comment by SuperXingKong** [comment]
You can use /makeserver to get a phar file
