### ISSUE TITLE
HELP WTF 

### ISSUE THREAD

**Issue by RateekMCPE** [GenisysPro/GenisysPro#269]
What server lag with 25players? help me...
![image](https://user-images.githubusercontent.com/21282002/27737115-43c9000a-5da7-11e7-83df-cddf1092daac.png)

![image](https://user-images.githubusercontent.com/21282002/27737143-5a6c4b6e-5da7-11e7-92b2-c4bc4140b001.png)

And the tps goes from 20 to 18 for no reason

**Comment by AndreySK4** [comment]
You're using Hydracon :))

**Comment by RateekMCPE** [comment]
It for all software @AndreySK4

**Comment by RateekMCPE** [comment]
![image](https://user-images.githubusercontent.com/21282002/27741846-b383860e-5db6-11e7-99db-854aa4110dbb.png)

**Comment by Pizzahaet** [comment]
It is your computer probably what is you computers specs, how many cores does your cpu have, what is it's clock speed, what is your hdd write speed?

**Comment by andris155** [comment]
Use timings and optimize your server. My server works perfectly 40 players and 20 TPS. (Kingston SSD, Xeon 2,8 Ghz, 6 GB DDR3 RAM)

**Comment by andris155** [comment]
And you use GenisysPro no Hydracon!

**Comment by Pizzahaet** [comment]
Php uses the CPU not ram, you probably have a good stable CPU with a good amount of cores

**Comment by DerddyDert** [comment]
Feel free to keep this conversation going but I'm closing this as an issue.
