### ISSUE TITLE
Its 50-80% impossible to die wearing armor

### ISSUE THREAD

**Issue by poustmal** [GenisysPro/GenisysPro#272]
Just use diamond or iron idk chestplate and the other diamond things,and you won't lose damage easy or you won't lose any damage

**Comment by poustmal** [comment]
With diamond things you will sure not die,if you shot a player with bow or snow etc. you will lose heart,now for only iron armor(not mixed with gold and other) and other types of armor I'm not sure

**Comment by poustmal** [comment]
Genisys pro version:b5bed34
Game version:not important I think,but 1.0.5.5
Server OS:windows

**Comment by derddy** [comment]
1.0.5.5?

**Comment by DerddyDert** [comment]
Cannot replicate. Can you show me in your server? @poustmal

**Comment by poustmal** [comment]
![screenshot_2017-06-30-18-26-09](https://user-images.githubusercontent.com/22281205/27761625-97b6b858-5e68-11e7-8626-c61dade6bd78.png)

**Comment by poustmal** [comment]
![screenshot_2017-06-30-18-08-22](https://user-images.githubusercontent.com/22281205/27761630-ac251d3e-5e68-11e7-8345-bd7ed4351667.png)

**Comment by DerddyDert** [comment]
I confirmed damage works fine in latest src.
