### ISSUE TITLE
Genisys.phar pls

### ISSUE THREAD

**Issue by oGalatico** [GenisysPro/GenisysPro#273]
#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by oGalatico** [comment]
Hey, how can I get the .phar file for this api please just buy a host :)

**Comment by DerddyDert** [comment]
Ask in discord https://discord.gg/WrKzRNn

**Comment by poustmal** [comment]
I made the /makeserver command work on genisys pro forked devtools: https://github.com/GenisysPro/PocketMine-DevTools/pull/1
