### ISSUE TITLE
地狱让开服变慢-Get out of nether take slow

### ISSUE THREAD

**Issue by bdeh0** [GenisysPro/GenisysPro#274]
如果服务器地图里有地狱地图，或者genisys.yml里面的allow-nether是true的话，就需要十几分钟甚至几十分钟才能开服
我试过删掉地狱的话就几秒钟就开好了，应该就是地狱的问题
If there is a nether map on the server map, or the allow-nether in genisys.yml is true, it takes ten minutes or even minutes to open
I tried to cut out nether, it would take a few seconds to open, it should be nether

**Comment by DerddyDert** [comment]
nether works fine and loads as it should on test server using latest src. Any trouble you are experiencing may be due to a plugin or may be related to #235
