### ISSUE TITLE
Make maps work normally 地图无效

### ISSUE THREAD

**Issue by bdeh0** [GenisysPro/GenisysPro#275]
这里的地图指的是物品的那种地图-The map here refers to the map of the items
只有空地图，创建不了有图的地图-Only empty maps can not create maps with maps
我这有个插件必须要地图的-I have a plugin here. It needs map
ZXDA链接：https://pl.zxda.net/plugins/744.html
ZXDA interlinkage：https://pl.zxda.net/plugins/744.html

**Comment by DerddyDert** [comment]
Is there only an error when using the plugin?

**Comment by MasterOfTheRealm** [comment]
@bdeh0 you want maps to work like in vanilla minecraft?

**Comment by DerddyDert** [comment]
I never tried them. How do they work now?

**Comment by DerddyDert** [comment]
What are we doing with this?

**Comment by SuperXingKong** [comment]
Fixed
