### ISSUE TITLE
v1.0.8 protocol

### ISSUE THREAD

**Issue by jdongel2004** [GenisysPro/GenisysPro#28]
#### Issue description
  change the protocol please.

#### Steps to reproduce the issue
  Mojang didn't change the protocol. Minecraft 1.0.8 's protocol is 107! Change this please!

#### OS and versions

* Genisys: Genisys lastest update. (Fix the /transfer ~~~~)
* PHP: 7.0.18
* Server OS: Ubuntu 17.04
* Game version: 1.0.8

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by SuperXingKong** [comment]
Well, I will fix it right away.

**Comment by SuperXingKong** [comment]
Fixed,Thank you for your report

**Comment by SuperXingKong** [comment]
Fixed,Thank you for your report

**Comment by Leo3418** [comment]
My bad, I merged the commit which changed the protocol to 108... but it still works, right?

**Comment by SuperXingKong** [comment]
That's true 😄
