### ISSUE TITLE
Gameplay Issue

### ISSUE THREAD

**Issue by xinghao2003** [GenisysPro/GenisysPro#286]
#### Issue description
- Enchantment table isn't functional
- Anvil isn't functional

#### OS and versions
* Genisys: 8b91232
* PHP: 7.0.3
* Server OS: Ubuntu
* Game version: MCPE 1.1.0 above

#### Crashdump, backtrace, memory dumps, plugins list or other files
```
```

**Comment by DerddyDert** [comment]
Not possible for MCPE 1.1.2 as far as we know.
