### ISSUE TITLE
Block's breaking animation don't seeing

### ISSUE THREAD

**Issue by AydarTop** [GenisysPro/GenisysPro#290]

**Comment by caspervanneck** [comment]
you shult look at the genisys.yml

**Comment by caspervanneck** [comment]
@AydarTop

**Comment by AydarTop** [comment]
@caspervanneck Hunger is working. But block breaking animation don't seeng.
Steps to reproduce issue:
1) Select survival mode
2) Start breaking any block

**Comment by TestV2** [comment]
Hi
I also have trouble breaking
While the gameplay is Survival, it seems as if the Adventure has been stuck
When we are admin we can
In serverproperties, there is spawn-protection = 0
But when we use /gms, it gets true
The problem is not the plugins

**Comment by erkam2002** [comment]
-1

**Comment by DerddyDert** [comment]
This is user error. Come up with a single issue per post and repost if its something we can replicate.

**Comment by AydarTop** [comment]
@DerddyDert I'm recorded video: https://youtu.be/ydyXlrV4eH0
