### ISSUE TITLE
ShulkerBox

### ISSUE THREAD

**Issue by SerezhaIvanov** [GenisysPro/GenisysPro#293]
Add please working ShulkerBox.

**Comment by DerddyDert** [comment]
What src are u using??

**Comment by SerezhaIvanov** [comment]
Last

**Comment by BajanVlogs** [comment]
This issue is fixed @DerddyDert please close

**Comment by MasterOfTheRealm** [comment]
@SerezhaIvanov said Working Shulker Boxes

**Comment by Leo3418** [comment]
#617 duplicates this issue, but since that issue was opened more recently, this issue is being closed.
