### ISSUE TITLE
Blocks dont show crack as player mines it

### ISSUE THREAD

**Issue by AydarTop** [GenisysPro/GenisysPro#298]
#### Issue description
Block breaking animation don't seen in survival mode.

#### Steps to reproduce the issue
1) Select survival mode.
2) Start break any block.
Video: https://youtu.be/ydyXlrV4eH0

**Comment by DerddyDert** [comment]
Looks fine to me. I don't understand

**Comment by AydarTop** [comment]
@DerddyDert Tested on MCPE 1.1.2, Android device

**Comment by DerddyDert** [comment]
What bug? It looked normal.

**Comment by AydarTop** [comment]
@DerddyDert Missing block crack animation.

**Comment by MasterOfTheRealm** [comment]
Animate packets....

**Comment by DerddyDert** [comment]
OHHH the crack when breaking.

**Comment by AydarTop** [comment]
@DerddyDert See vanilla block breaking animation: https://youtu.be/l89f-nmmW-U

**Comment by DerddyDert** [comment]
@MasterOfTheRealm can you fix the blockcrack ? Hehe

**Comment by DerddyDert** [comment]
I'm sorry I just forgot about the blockcrack.

**Comment by Leo3418** [comment]
I'm closing this because although it hasn't been fixed, #637 duplicates this, and that issue was opened more recently.
