### ISSUE TITLE
Bed drop's bug

### ISSUE THREAD

**Issue by AydarTop** [GenisysPro/GenisysPro#299]
#### Issue description
Drop's only red colored bed item.

#### Steps to reproduce the issue
1) Place bed
2) Break bed block

![img_20170702_164226](https://user-images.githubusercontent.com/24245658/27796000-05667a9c-6011-11e7-84f2-f99c6822cd14.jpg)
![img_20170702_164244](https://user-images.githubusercontent.com/24245658/27796169-b1bd988e-6011-11e7-866b-655770b4ebf2.jpg)

**Comment by DerddyDert** [comment]
Interesting!

**Comment by DerddyDert** [comment]
Some beds turn red and some turn their normal color
![screenshot_20170703-102544](https://user-images.githubusercontent.com/18636275/27797030-16d74acc-5fda-11e7-8946-c0e0bf9539d5.jpg)

**Comment by MasterOfTheRealm** [comment]
Ok i did some further testing....its not random.
When you break bed from its head, it drops normal colors
but if you break from its feet, it drops only red color.

**Comment by erkam2002** [comment]
Bruh

**Comment by DerddyDert** [comment]
Makes sense @MasterOfTheRealm bed is 2 blocks l0ng.

**Comment by AydarTop** [comment]
@DerddyDert Still an issue.

**Comment by SuperKali** [comment]
not work Still the beds are dropped red @DerddyDert

**Comment by SuperKali** [comment]
reopen this issue

**Comment by DerddyDert** [comment]
@CookieCode

**Comment by CookieCode** [comment]
WTF

**Comment by DerddyDert** [comment]
@CookieCode fixed this. Use latest src.
