### ISSUE TITLE
Help me with this bug

### ISSUE THREAD

**Issue by alair069** [GenisysPro/GenisysPro#306]
![-c1govyy](https://user-images.githubusercontent.com/27539870/27811244-9756f188-603a-11e7-8dd5-e2dce93cfe36.jpg)

**Comment by DerddyDert** [comment]
Need more info. What plugins you using? What are you doing that causes this?

**Comment by alair069** [comment]
My server is skywars, Alas this happens, Chests do not open, Chests are fading ....

**Comment by CookieCode** [comment]
Templo, Is a mca world, mcr ... ?

**Comment by alair069** [comment]
mca

**Comment by CookieCode** [comment]
Lol read my question -_-...

**Comment by alair069** [comment]
MCA

**Comment by MasterOfTheRealm** [comment]
@alair069 Chests do not open - maybe because of your spawn protection

**Comment by alair069** [comment]
I do not have protection plugin for the other worlds, just for the lobby

**Comment by DerddyDert** [comment]
#317 Same?

**Comment by DerddyDert** [comment]
There have been some updates but I think the issue is here https://github.com/GenisysPro/GenisysPro/commit/bfec0eabb662ed777d4906a965f7cfbc1394a82a 	bfec0ea

**Comment by DerddyDert** [comment]
I'm closing this. Reopen if you can recreate
