### ISSUE TITLE
The grass will turn into black light

### ISSUE THREAD

**Issue by nishuo** [GenisysPro/GenisysPro#315]
#### Issue description

![Image of Yaktocat](http://i4.piimg.com/1949/62ff745bfdf80066.png)
#### Steps to reproduce the issue

Every blade of grass on the grass is black with light and shadow, unable to display properly.
#### OS and versions

* Genisys:1.1dev
* PHP:7.1.5
* Server OS:Centos7
* Game version: 1.1.2

**Comment by Crypt97** [comment]
#Duplicate #111

**Comment by nishuo** [comment]
ok
