### ISSUE TITLE
Control buttons are disappearing

### ISSUE THREAD

**Issue by Borduni** [GenisysPro/GenisysPro#316]
#### Issue description
Navigation buttons are vanished

#### Steps to reproduce the issue
Stay some time on your GenisysPro server and at one time, the control buttons disappear

#### OS and versions

* Genisys: newest build
* PHP: 7.0.6 ARM Raspberry
* Server OS:  Raspbian (32 bit)
* Game version: MCPE 1.1.2

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Borduni** [comment]
Link to my screen: https://ibb.co/iyo12v

**Comment by MasterOfTheRealm** [comment]
Remove all addons and texture packs and try replicate the issue

**Comment by xinghao2003** [comment]
I think it was a client issue, can the core control the button disappear?

**Comment by TDMidkwhatisxd** [comment]
It happens wen the client glich. I had this issue many times, no way to fix.
Set compression to 2, if that not help, blow the building that makes u glich :)
