### ISSUE TITLE
Could not tick level

### ISSUE THREAD

**Issue by poustmal** [GenisysPro/GenisysPro#317]
Console was spamming for hours I think or minutes for this:
![img_20170705_223056_192](https://user-images.githubusercontent.com/22281205/27881754-8a34eb88-61d2-11e7-8aa1-45c23da2c416.JPG)
![img_20170705_223115_033](https://user-images.githubusercontent.com/22281205/27881916-2cd52aba-61d3-11e7-83f3-04f65f05a77f.JPG)

For this that it says entity.php,I think it happens when using boat and for the other spam in picture idk

**Comment by poustmal** [comment]
I have updated the my genisys pro version these days for fixes and new items.

**Comment by DerddyDert** [comment]
Thanks for posting the issue. Have you fixed this in your src or did it happen after an update?

**Comment by DerddyDert** [comment]
#306 same?

**Comment by MrSmileCH** [comment]
That same mistake has pocketmine is cause to eat an apple of gold or notch begins to throw that mistake

**Comment by DerddyDert** [comment]
bfec0ea

**Comment by DerddyDert** [comment]
@poustmal please copy and past ALL errors. Every time it shows what line in entity.php the error was helps to locate the issue.

**Comment by DerddyDert** [comment]
@poustmal also I NEED you to update to CURRENT src because the error lines are not correct since it has been updated since the source you are using. Thanks

**Comment by poustmal** [comment]
The console was having a ton of this spam,It will not have an end if I paste errors I think

**Comment by DerddyDert** [comment]
@poustmal I understand. Just post as much as you can. But please update src.

**Comment by poustmal** [comment]
.fine but I have the latest src(I made it phar file of course) on my normal server,I'll see my console if this error is happening again

**Comment by DerddyDert** [comment]
The problem is the lines it says the errors were are blank or commented out.

**Comment by poustmal** [comment]
Now this <<movement distance>> spam doesn't exist now,the other error idk

**Comment by DerddyDert** [comment]
Because you have the latest src?
