### ISSUE TITLE
Boat is travelling

### ISSUE THREAD

**Issue by poustmal** [GenisysPro/GenisysPro#318]
When I use boat and I leave then,the boat is driving and it doesn't stop until it goes to a block or until you remove it.
-->
* Genisys: 5a87779
* PHP:idk but its 7
* Server OS:windows
* Game version:android
![img_20170705_223209_061](https://user-images.githubusercontent.com/22281205/27882993-a4dcff48-61d7-11e7-856a-0edddd418a05.JPG)

**Comment by DerddyDert** [comment]
Test on water?

**Comment by poustmal** [comment]
On water is fine,but if it goes on a waterfall without a player inside,it flies,lol
![img_20170705_232724_464](https://user-images.githubusercontent.com/22281205/27883595-c08a0176-61d9-11e7-8cf3-f19600f81fa4.JPG)

**Comment by DerddyDert** [comment]
Haha thats silly. Thanks.
