### ISSUE TITLE
Thorns duplication error

### ISSUE THREAD

**Issue by DerddyDert** [GenisysPro/GenisysPro#321]
Player keeps inventory when they die from thorns. The inventory also drops causing a duplication. What we need to do is force the player's inventory to drop after all their energy is taken from thorns but before they die.
See video for full explanation: https://youtu.be/ys1tWxBh9YA

**Comment by MasterOfTheRealm** [comment]
Note that the cactus isnt part of the dupe...its just used as a way to get down to half a heart.

**Comment by DerddyDert** [comment]
Yeah great point.

**Comment by HipsterAF** [comment]
https://github.com/GenisysPro/GenisysPro/blob/master/src/pocketmine/Player.php#L2932
