### ISSUE TITLE
Closed, thanks xinghao2003!

### ISSUE THREAD

**Issue by suslik1234** [GenisysPro/GenisysPro#323]
closed

**Comment by xinghao2003** [comment]
What world format that you using now

**Comment by suslik1234** [comment]
mcanvil

**Comment by xinghao2003** [comment]
Try using PMAnvil to generate the world and post the new timings link

**Comment by suslik1234** [comment]
ok

**Comment by suslik1234** [comment]
http://timings.pmmp.io/?url=25033240

**Comment by suslik1234** [comment]
it without the players. no load and plugins
