### ISSUE TITLE
LoL, PHPStorm Code inspection :D

### ISSUE THREAD

**Issue by Borduni** [GenisysPro/GenisysPro#327]
[Link to my screen](https://image.ibb.co/cJhcaF/Screenshot_12.png)

**Comment by Borduni** [comment]
GenisysPro needs a big code cleanup xD

**Comment by DerddyDert** [comment]
@Frago9876543210 @SuperXingKong

**Comment by Borduni** [comment]
But this takes hours...

**Comment by Borduni** [comment]
...Please fix the tag from enhancement to enchancement xD

**Comment by AppleDevelops** [comment]
@Borduni Never takes hours, takes a smart person.

**Comment by DerddyDert** [comment]
And some good software. I'm halfway done reviewing and every time I think I found an error I realize its just how github displays stuff.

**Comment by DerddyDert** [comment]
@Borduni haha I didn't know I added that tag but it fits.
