### ISSUE TITLE
Glide error judgment

### ISSUE THREAD

**Issue by nishuo** [GenisysPro/GenisysPro#330]
#### Issue description

It will land quickly from the top of the mucus, and it will glide along with the wing, and it will fall off midway through the air. Rapid vertical drop.
#### OS and versions

* Genisys:1.1dev
* PHP:7.0.17
* Server OS:Centos6
* Game version: 1.1.2

It's just updated with git pull.
The latest version.

**Comment by Gianluxx** [comment]
Antifly not checking if player isGliding. It has to be fixed in Player.php movement.
