### ISSUE TITLE
My server freezes

### ISSUE THREAD

**Issue by SuperKali** [GenisysPro/GenisysPro#331]
* Genisys: latest
* PHP: 7.0.19
* Server OS: Debian 9
* Game version: Minecraft Windows 10 Edition

* Virtually the server is online but on the servers menu that off, it's these days known the very high load that is caused by Memory leaks ie it highs and lows and frizs

**Comment by SuperKali** [comment]
I apologize for grammatical errors but I was in a hurry to go to work

**Comment by Borduni** [comment]
What plugins do you have installed?

**Comment by Borduni** [comment]
Maybe it's a plugin that is in a loop and cause big performance drops

**Comment by SuperKali** [comment]
@Borduni No This slowdown is caused by the last update because in the old version 1.0.9 I had no problem!

**Comment by MrSmileCH** [comment]
@SuperKali Do you still have lag problems?

**Comment by SuperKali** [comment]
Yes

**Comment by DerddyDert** [comment]
Do you use slapper?

**Comment by SuperKali** [comment]
@DerddyDert yes

**Comment by DerddyDert** [comment]
I had same problem until some slapper started disappearing...

**Comment by SuperKali** [comment]
I have never disappeared

**Comment by DerddyDert** [comment]
I'm fixing this now. I need to see your timings

**Comment by XDqrkneZ** [comment]
happens too, freeze randomly, only for a few second.. can't be my wifi. I only have 10 plugins on and my timings is great https://timings.pmmp.io/?url=25073936

**Comment by XDqrkneZ** [comment]
any fix?

**Comment by SuperKali** [comment]
![screenshot_20170712-105317](https://user-images.githubusercontent.com/19473898/28109864-d557faa6-66f0-11e7-8236-8213460a0edd.jpg)
https://timings.pmmp.io/?url=25074052
I use mcregion

**Comment by XDqrkneZ** [comment]
@SuperKali oh.. so your server was only lagging because you were using a .mca map?

**Comment by SuperKali** [comment]
Yes

On Jul 12, 2017 11:05 AM, "Otosaka Yu" <notifications@github.com> wrote:

@SuperKali <https://github.com/superkali> oh.. so your server was only
lagging because you were using a .mca map?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GenisysPro/GenisysPro/issues/331#issuecomment-314702029>,
or mute the thread

**Comment by XDqrkneZ** [comment]
oh nice 👍 maybe you should close this issue :3

**Comment by SuperKali** [comment]
Nope in the versione 1.0.9 Not i have many problem for memory leak

**Comment by SuperKali** [comment]
@XDqrkneZ 
![screenshot_20170521-123927](https://user-images.githubusercontent.com/19473898/28110819-cac204a8-66f3-11e7-908b-4d2234652f8a.jpg)

The old version status of version 1.0.9

**Comment by SuperKali** [comment]
This is caused by the memory leak of the current version still unresolved

**Comment by XDqrkneZ** [comment]
oh @SuperKali

**Comment by SuperKali** [comment]
@DerddyDert another timings ttp://timings.pmmp.io/?url=25074602

**Comment by XDqrkneZ** [comment]
@SuperKali remove BossAnnouncement,

**Comment by XDqrkneZ** [comment]
try removing LiveSigns, BossAnnouncements and TimeRanks.. and see changes

**Comment by SuperKali** [comment]
@XDqrkneZ I can not remove plugins are essential for my server

**Comment by XDqrkneZ** [comment]
but those 3 are causing the lag, just "try" removing them and see if anything improves. Bossbar isn't very useful unless it's needed for some type of gamemode.. LiveSigns? what is it for..? Those 2 use both tasks but idk

**Comment by SuperKali** [comment]
Live sign I need for flying texts

On Jul 13, 2017 4:54 AM, "Otosaka Yu" <notifications@github.com> wrote:

but those 3 are causing the lag, just "try" removing them and see if
anything improves. Bossbar isn't very useful unless it's needed for some
type of gamemode.. LiveSigns? what is it for..? Those 2 use both tasks but
idk

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GenisysPro/GenisysPro/issues/331#issuecomment-314956045>,
or mute the thread

**Comment by SuperKali** [comment]
And timerank is associated with pureperm

On Jul 13, 2017 9:11 AM, "Daniele Briguglio" <danychannel18@gmail.com>
wrote:

Live sign I need for flying texts

On Jul 13, 2017 4:54 AM, "Otosaka Yu" <notifications@github.com> wrote:

but those 3 are causing the lag, just "try" removing them and see if
anything improves. Bossbar isn't very useful unless it's needed for some
type of gamemode.. LiveSigns? what is it for..? Those 2 use both tasks but
idk

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GenisysPro/GenisysPro/issues/331#issuecomment-314956045>,
or mute the thread

**Comment by DerddyDert** [comment]
@MasterOfTheRealm your thoughts on this?

**Comment by SuperKali** [comment]
@DerddyDert http://timings.pmmp.io/?url=25104499
minecraft w10 edition lags when you are for a long time on a world

**Comment by XDqrkneZ** [comment]
is this fixed?

**Comment by SuperKali** [comment]
nope, help me 
![41](https://user-images.githubusercontent.com/19473898/28723277-8d1ae7ee-73b6-11e7-9f42-14ced257d501.PNG)

**Comment by erkam2002** [comment]
tnt?

**Comment by DerddyDert** [comment]
No he has a lot of people and to much ticking from genisyspro and plugins is dropping TPS.
