### ISSUE TITLE
Byte issue still happening

### ISSUE THREAD

**Issue by BajanVlogs** [GenisysPro/GenisysPro#333]
07.07 18:56:18 [Server] Server thread/EMERGENCY Please upload the "/crashdumps/CrashDump_Fri_Jul_7-22.56.18-UTC_2017.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can. 07.07 18:56:18 [Server] Server thread/EMERGENCY An unrecoverable error has occurred and the server has crashed. Creating a crash dump 07.07 18:56:17 [Server] INFO Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 131072 bytes) in /jar/pocketmine/src/pocketmine/Server.php on line 2078

Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 131072 bytes)
File: /src/pocketmine/Server
Line: 2078
Type: E_ERROR

Code:
[2069] 			if($p->isConnected()){
[2070] 				$targets[] = $this->identifiers[spl_object_hash($p)];
[2071] 			}
[2072] 		}
[2073] 
[2074] 		if(!$forceSync and $this->networkCompressionAsync){
[2075] 			$task = new CompressBatchedTask($str, $targets, $this->networkCompressionLevel);
[2076] 			$this->getScheduler()->scheduleAsyncTask($task);
[2077] 		}else{
[2078] 			$this->broadcastPacketsCallback(zlib_encode($str, ZLIB_ENCODING_DEFLATE, $this->networkCompressionLevel), $targets);
[2079] 		}
[2080] 
[2081] 		Timings::$playerNetworkTimer->stopTiming();
[2082] 	}
[2083] 
[2084] 	public function broadcastPacketsCallback($data, array $identifiers){
[2085] 		$pk = new BatchPacket();
[2086] 		$pk->payload = $data;
[2087] 		$pk->encode();
[2088] 		$pk->isEncoded = true;

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 0000000000000000000000000000000000000000 [Protocol 113; API 3.0.1]
uname -a: Linux vps 2.6.32-042stab094.8 #1 SMP Tue Dec 16 20:36:56 MSK 2014 x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 2 hours 19 minutes 20 seconds
Number of loaded worlds: 3
Players online: 14/1000

**Comment by DerddyDert** [comment]
Allowed memory size of 1073741824 ?? Where is that coming from?

**Comment by BajanVlogs** [comment]
idk i use other softwares and this doesnt happen

**Comment by BajanVlogs** [comment]
so you gonna fix it

**Comment by DerddyDert** [comment]
You said it doesn't happen on other software? That doesn't really help. Could be user error? I'm trying to figure out why it thinks you have over a million MB of ram? Can you list your plugins and send your ymls? You are the only one that gets this error. Also, tell your server to stop every hour and a half.

**Comment by G2PCraft** [comment]
I think this happen by your server use ram over that u have.

**Comment by G2PCraft** [comment]
that make server stop.

**Comment by BajanVlogs** [comment]
i fixed it myself but thanks for helping

**Comment by DerddyDert** [comment]
So what was it?

**Comment by BajanVlogs** [comment]
zlib_encode needed a cap Z

**Comment by DerddyDert** [comment]
Wow. Thanks for the fix.

**Comment by MasterOfTheRealm** [comment]
Any steps on how to reproduce this issue? @BajanVlogs
