### ISSUE TITLE
Please delete the red stone function.

### ISSUE THREAD

**Issue by shdudwns** [GenisysPro/GenisysPro#334]
Because of the red stone, the server of the server is severe.
If you don't, you'll get some better.

**Comment by MasterOfTheRealm** [comment]
Just disable redstone in genisys.yml, its there for a reason

**Comment by shdudwns** [comment]
@MasterOfTheRealm Isn't Stone the only function in 0.16.0? Shouldn't we be discussing it at 1.1?

**Comment by MasterOfTheRealm** [comment]
Can you please explain it a bit better?

**Comment by shdudwns** [comment]
@MasterOfTheRealm Even disabling the Red Stone feature disables the server rek. We need to get rid of it.

**Comment by Borduni** [comment]
?!

**Comment by shdudwns** [comment]
@Borduni why?
