### ISSUE TITLE
Out of memory in CompressBatchedTask.php on line 43

### ISSUE THREAD

**Issue by Takesikaityo** [GenisysPro/GenisysPro#336]
My server is restarting every 1h
But the task crashed.
What should I do?

Fatal error: Out of memory (allocated 10485760) (tried to allocate 131072 bytes) in C:\Users\takec\Downloads\GenisysPro-master\src\pocketmine\network\CompressBatchedTask.php on line 43
[23:18:09:2623] 危険> Could not execute asynchronous task CompressBatchedTask: Task crashed﻿

OS : Windows10 home
Bit : 64bit
Memory : 8GB
SSD : 525GB
CPU：Pentium N3710(Braswell)

**Comment by TDMidkwhatisxd** [comment]
This will stop the server when the limit is surpassed 
  main-hard-limit: 1024 ( change to 0)

In pocketmine.yml
