### ISSUE TITLE
Shadows

### ISSUE THREAD

**Issue by SerezhaIvanov** [GenisysPro/GenisysPro#341]
#### Issue description

The world is full of shadows, how to get rid of them?

#### Steps to reproduce the issue

Use world with PC servers.

#### OS and versions

* Genisys: 1.1
* PHP: 7.0.3
* Server OS: Ubuntu
* Game version: [1.1.0.55]
![screenshot_2017-07-09-19-37-07](https://user-images.githubusercontent.com/12472255/27995998-fdad6070-64e0-11e7-9185-5af663447d8e.png)

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Borduni** [comment]
I have the same problems

**Comment by Borduni** [comment]
Furthermore I cant break blocks fast and turning me around quickly

**Comment by MasterOfTheRealm** [comment]
@Borduni allow instabreak in pocketmine.yml

**Comment by DerddyDert** [comment]
This was fixed by @Frago9876543210  Get latest src.
