### ISSUE TITLE
Why is this happening?

### ISSUE THREAD

**Issue by MrSmileCH** [GenisysPro/GenisysPro#343]
![sin titulo](https://user-images.githubusercontent.com/27845246/28001384-a409e7d0-64f1-11e7-8975-e26485cfa1c8.png)

**Comment by DerddyDert** [comment]
Happened to me until I pulled slapper plugin out and configured cache and compression

**Comment by MrSmileCH** [comment]
As I do what you told me, I do not understand very well

**Comment by DerddyDert** [comment]
Yeah well I'm looking into all this. Do you use slapper?

**Comment by MasterOfTheRealm** [comment]
On respawn?

**Comment by MrSmileCH** [comment]
@DerddyDert @MasterOfTheRealm If I use slapper plugin, but what happens in the photo happens when you die do not load the map just breaking a block starts loading the map part

**Comment by DerddyDert** [comment]
Timings? @MrSmileCH

**Comment by DerddyDert** [comment]
This issue was created by your setup. Update your slapper to one that works. Or change to NPC. And if u have an imported world change it to anvil in yml and level.dat.
