### ISSUE TITLE
Hotbar

### ISSUE THREAD

**Issue by majovec** [GenisysPro/GenisysPro#356]
Hi i need help in consle me send this "Deprecated: Do not attempt to change hotbar links in plugins! in /root/bw/src/pocketmine/inventory/PlayerInventory.php on line 105" and i use this code 

for($i = 0; $i <= 8; $i++){
            $inv->setHotbarSlotIndex($i, 34);
        } 

AllCode is 👍 

public function openShop(Player $p){
        if($this->isShopping($p)){
            return;
        }
        $inv = $p->getInventory();
        $this->players[strtolower($p->getName())]['items'] = new VirtualInventory($p);
        $this->players[strtolower($p->getName())]['window'] = "main";
        $inv->clearAll();
        $inv->setContents($this->items['main']);
        for($i = 0; $i <= 8; $i++){
            $inv->setHotbarSlotIndex($i, 34);
        }
        $inv->sendContents($p);
        $p->sendMessage($this->plugin->plugin->getPrefix().TextFormat::GREEN."Open your inventory for shopping");
    }

**Comment by erkam2002** [comment]
Use this:

```
$player->getInventory()->setHeldItemIndex($count);
```

**Comment by majovec** [comment]
$count is ?

**Comment by majovec** [comment]
sorry im noobs

**Comment by erkam2002** [comment]
a number from 0-8

**Comment by Leo3418** [comment]
Yes, that is a deprecated method. If you want to get rid of that message, you should refrain from using it.  
Instead, you can use the following method. Suppose you want to give `$player` an `$item`, and you want that item to appear in the slot with index `slotIndex`:
```php
$player->getInventory()->setItem($slotIndex, $item);
```
BTW, next time when you have plugin developing questions, you should post them in Discord chat or GenisysPro forum.
