### ISSUE TITLE
Blocks don't drop

### ISSUE THREAD

**Issue by Norman300** [GenisysPro/GenisysPro#359]
When you break a block in survival mode(such as grass and dirt block), no items drop
With the latest GenisysPro and CentOS7.2

**Comment by Norman300** [comment]
MCPE version : 1.1.3.1
No warnings in console

**Comment by DerddyDert** [comment]
Whats your spawn protection set to? Are you experiencing any lag? Do you use slapper plugin? @Norman300

**Comment by MasterOfTheRealm** [comment]
Confirmed

**Comment by MasterOfTheRealm** [comment]
This is because a file is missing...i'll fix this

**Comment by MasterOfTheRealm** [comment]
Please try now with latest src @Norman300

**Comment by Norman300** [comment]
Blocks dropped. Thank you! @MasterOfTheRealm
