### ISSUE TITLE
The player entered the game for error

### ISSUE THREAD

**Issue by nishuo** [GenisysPro/GenisysPro#361]
#### Issue description

计算地图“world”时出现错误∶Call to undefined method pocketmine\level\Level::getHighestAdjacentBlockSkyLight()

#### OS and versions

* Genisys:1.1dev
* PHP: 7.0.17
* Server OS: Ubuntu16.04
* Game version: 1.1.3

**Comment by nishuo** [comment]
The latest git pull version

**Comment by DerddyDert** [comment]
Not anymore. Please update src and confirm. Thanks! @nishuo

**Comment by DerddyDert** [comment]
Is this fixed @Frago9876543210 @MasterOfTheRealm

**Comment by MasterOfTheRealm** [comment]
yes it was fixed

**Comment by MasterOfTheRealm** [comment]
The latest PR @Frago9876543210 made should be the last we ever hear about getHighestAdjacentBlockSkyLight()...hopefully xD.

**Comment by DerddyDert** [comment]
Great work team!

**Comment by nishuo** [comment]
Thank you
