### ISSUE TITLE
CompressBatchedTask: Task crashed﻿

### ISSUE THREAD

**Issue by DerddyDert** [GenisysPro/GenisysPro#362]
takesi - Last Saturday at 11:47 PM
Fatal error: Out of memory (allocated 10485760) (tried to allocate 131072 bytes) in C:\Users\takec\Downloads\GenisysPro-master\src\pocketmine\network\CompressBatchedTask.php on line 43
[23:18:09:2623] 危険> Could not execute asynchronous task CompressBatchedTask: Task crashed﻿
My server is restarting every 1h
What should I do?

**Comment by Frago9876543210** [comment]
You have too little RAM

**Comment by Frago9876543210** [comment]
For good server performance you need to have 2 or 4 GB.

**Comment by Takesikaityo** [comment]
My PC has 8GB RAM.
So I think that setting is bad in pocketmine.yml

**Comment by Takesikaityo** [comment]
OS : Windows10 home
Bit : 64bit
shell : Windows PowerShell
CPU : Intel® Pentium® Processor N3710
RAM : 8GB
ROM : 525GB(SSD)

**Comment by DerddyDert** [comment]
You put 0 for memory limit to disable it?

**Comment by Takesikaityo** [comment]
still
So I will put 0 for memory limit to disable it later.

**Comment by XDqrkneZ** [comment]
@Frago9876543210 how do you allocate more RAM?

**Comment by DerddyDert** [comment]
@Takesikaityo disable memory limit and repoen issue if you still have it.

**Comment by Takesikaityo** [comment]
okay
I disable memory limit and I don't see this error.
