### ISSUE TITLE
Dark shadows on grass, flowers and editing land

### ISSUE THREAD

**Issue by GDRGamingzz** [GenisysPro/GenisysPro#363]
#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by GDRGamingzz** [comment]
the grass and flowers have shadows when generating a world and also when using world edit it keeps showing the dark shadows

**Comment by Frago9876543210** [comment]
Your world with pc?

**Comment by DerddyDert** [comment]
I think the default in the yml needs to be set properly @Frago9876543210

**Comment by DerddyDert** [comment]
@GDRGamingzz which src are you using? This was just fixed around the time you posted this issue. Some fine tuning to do perhaps but I thought it was solved.

**Comment by GDRGamingzz** [comment]
the latest one bro.
still does the same thing

**Comment by DerddyDert** [comment]
So you updated your src?

**Comment by DerddyDert** [comment]
Anyway @Frago9876543210 is handling the shadow issue and will work with you on that. Feel free to join our discord chat if you can so we can sort this issue faster.

**Comment by GDRGamingzz** [comment]
the newest one like few hours ago.

**Comment by DerddyDert** [comment]
@GDRGamingzz Did you upload pre-generated/built worlds or just create the default world? Ill be looking into this as well shortly. Thanks

**Comment by Crypt97** [comment]
no dark ! :D Perfect fix ty GenesysPro

**Comment by Frago9876543210** [comment]
I wrote a simple plugin for fixing this. See https://github.com/GenisysPro/ChunkLightUpdate

**Comment by Frago9876543210** [comment]
@GDRGamingzz Write here if it helped you.

**Comment by andris155** [comment]
This plugin very laggy, but work.

**Comment by andris155** [comment]
How to update all chunk lights?

**Comment by DerddyDert** [comment]
The plugin is temporary and only to clean old chunks as they show up.

**Comment by DerddyDert** [comment]
I still think @GDRGamingzz may have downloaded the old src right before @Frago9876543210 did the last lighting update

**Comment by MasterOfTheRealm** [comment]
@DerddyDert Agreed, everything about it works fine now

**Comment by GDRGamingzz** [comment]
Hello @Frago9876543210 and @DerddyDert , the latest update fixed the shaded chunks it works fine now thanks! ill confirm this issue fixed thanks for helping out!

**Comment by DerddyDert** [comment]
@GDRGamingzz thanks for the followup man
