### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by SerezhaIvanov** [GenisysPro/GenisysPro#369]
#### Issue description

Why disappear all the objects which I have made created with ItemCase after a while, about 5 minutes. Previously, everything worked fine. I'm using the latest src.
#### OS and versions

* Genisys: 1.1
* PHP: 7.0.3
* Server OS: Ubuntu
* Game version: 1.1.3

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by Frago9876543210** [comment]
@SerezhaIvanov Try creating items when you turn on the plugin.

**Comment by DerddyDert** [comment]
They always disappeared. You need to run the command to refresh them every few min or so.
