### ISSUE TITLE
beacon error

### ISSUE THREAD

**Issue by mote166** [GenisysPro/GenisysPro#37]
#### Issue description

when u place a beacon this error pop-up in the console .
#### Steps to reproduce the issue

place a beacon and check the console
#### OS and versions

* Genisys: GenisysPro-1.0.0dev Starry
* PHP: 7.0.11
* Server OS: linux
* Game version: 1.0.8 (android)

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
[Server thread/CRITICAL]: Could not execute task pocketmine\tile\BeaconDelayedCheckTask: Call to a member function getName() on null 
[Server thread/CRITICAL]: Error: "Call to a member function getName() on null" (EXCEPTION) in "/src/pocketmine/tile/BeaconDelayedCheckTask" at line 42 
```

**Comment by lightda104530** [comment]
@SuperXingKong  We got lots of title...PMMP just a few,shall we change it?

**Comment by SuperXingKong** [comment]
@lightda104530 Well,you can just create a new branch and update it.

**Comment by SuperXingKong** [comment]
@mote166 Seems your level has Name(saved in level.dat) and FolderName different.
Run 

> /lvdat <LevelName> fixname

to confirm no error in your level.

**Comment by SuperXingKong** [comment]
Maybe I can enhance this code.

**Comment by mote166** [comment]
i don't know in which level it is . i have 13 loaded worlds

**Comment by SuperXingKong** [comment]
@mote166 Try the leastest commit.

**Comment by DerddyDert** [comment]
Please review your latest commit. I believe you deleted one to many `)`

**Comment by SuperXingKong** [comment]
@DerddyDert Yeah,it's my mistake xD
And @mote166 Has it fixed properly?

**Comment by SuperXingKong** [comment]
I try it and nothing wrong.It works well.Could you check your levels' folder name?It must be compatible with the name in level.dat.
