### ISSUE TITLE
lags

### ISSUE THREAD

**Issue by suslik1234** [GenisysPro/GenisysPro#370]
lags in the server. the tesseract was all good. here are my timings http://timings.pmmp.io/?url=25083054. help me please. I use the card format pmanvil.

**Comment by DerddyDert** [comment]
This is most likely a plugin issue. Please list your plugins.

**Comment by suslik1234** [comment]
![image](https://user-images.githubusercontent.com/26522277/28211132-bbcd77f0-68a3-11e7-9d36-3e02862fbf6d.png)

**Comment by IBochan** [comment]
Зачем установил 3 магазина на сервер?

**Comment by suslik1234** [comment]
Лучше помоги))

**Comment by suslik1234** [comment]
help please

**Comment by Varfalomey** [comment]
петушок

**Comment by IBochan** [comment]
# Нормальную сборку сделай!

**Comment by IBochan** [comment]
@suslik1234, # нормальную сборку сделай!

**Comment by BajanVlogs** [comment]
@suslik1234 There is your issue right there the Drugs plugin please list the code for it in here for i can see what is wrong with it since it uses particle effects it could be lagging the server

**Comment by DerddyDert** [comment]
Please review: https://github.com/pmmp/PocketMine-MP/issues/1161
