### ISSUE TITLE
Entity disappears

### ISSUE THREAD

**Issue by SerezhaIvanov** [GenisysPro/GenisysPro#372]
Entity disappears when I restart the server, what is the problem?

**Comment by DerddyDert** [comment]
What entity its disappearing??

**Comment by SerezhaIvanov** [comment]
All entities.

My code:
`						$nbt = new CompoundTag ("", [ 
							"Pos" => new ListTag( "Pos", [ 
								new DoubleTag("", $event->getPlayer()->x),
								new DoubleTag("", $event->getPlayer()->y),
								new DoubleTag("", $event->getPlayer()->z) 
							]),
							"Motion" => new ListTag ( "Motion", [ 
								new DoubleTag("", 0),
								new DoubleTag("", 0),
								new DoubleTag("", 0) 
							]),
							"Rotation" => new ListTag("Rotation", [ 
								new FloatTag("", $event->getPlayer()->yaw),
								new FloatTag("", $event->getPlayer()->pitch) 
							]) 
						]);
						$mob = Entity::createEntity(Villager::NETWORK_ID, $event->getPlayer()->level, $nbt);
						$mob->setMaxHealth(500);
						$mob->setHealth(500);
						$mob->setNameTag("swinfo");
						$mob->spawnToAll();`

**Comment by SerezhaIvanov** [comment]
How to fix it?

**Comment by BajanVlogs** [comment]
The problem is that your server automatically clears all mobs to reduce all lag when the server is restarted
so issue #372 can be closed
