### ISSUE TITLE
Inventory Issues

### ISSUE THREAD

**Issue by BajanVlogs** [GenisysPro/GenisysPro#374]
Step to get the same issue
Get Enchanted Golden Apples
And let someone kill
then tell them to open there inventory 
it will through all the items out 
and u have to keep picking them up
this happens when someone drops golden apples or some stuff
please fix this

**Comment by MasterOfTheRealm** [comment]
I think its because of the floating inventory a player has

**Comment by DerddyDert** [comment]
Kinda complicated to reproduce? Lol

**Comment by BajanVlogs** [comment]
well can someone fix this

**Comment by BajanVlogs** [comment]
this needs to be fixed ASAP

**Comment by TDMidkwhatisxd** [comment]
https://github.com/GenisysPro/GenisysPro/pull/386/commits/011f76e74a77e08952b4f2551de6b883307bb04c

Please someone test, and reformat the code, because it glitched for me.

**Comment by BajanVlogs** [comment]
This has been fixed please accept the pull request
