### ISSUE TITLE
Shovel doesn't work

### ISSUE THREAD

**Issue by poustmal** [GenisysPro/GenisysPro#378]
When you try to break any block with any type of shovel in survival mode,shovel doesn't break and block doesn't break.

**Comment by DerddyDert** [comment]
Works for me. Did you craft the shovel, or did you perhaps use economys plugin and buy it from a shop?

**Comment by BajanVlogs** [comment]
If you have over Haste 2-3 this happens this isn't a issue because its vanilla enchants on GenisysPro so please close your issue.
