### ISSUE TITLE
console assert warning 

### ISSUE THREAD

**Issue by mote166** [GenisysPro/GenisysPro#38]
#### Issue description

when this error comes the server freezes for no reason . when the server freeze i go to the console and the last thing on it is this error then after the freeze is gone the error goes too . but when this error comes back the server freezes until its gone again .
#### Steps to reproduce the issue

no idea
#### OS and versions

* Genisys: GenisysPro-1.0.0dev Starry
* PHP: 7.0.11
* Server OS: linux
* Game version: 1.0.8 (android)

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
Warning: assert(): Movement distance is excessive: dx=23.5808, dy=-2, dz=5.461 failed in phar:///jar/VERY/server17506-11.phar/src/pocketmine/entity/Entity.php on line 1485 14.05 02:27:35 [Server] INFO Warning: assert(): Movement distance is excessive: dx=24.0234, dy=-9, dz=-16.8258 failed in phar:///jar/VERY/server17506-11.phar/src/pocketmine/entity/Entity.php
```

**Comment by SuperXingKong** [comment]
Same as #36 ,blame Genisys' anti-cheat system

**Comment by RTGDaCoder** [comment]
We can't blame as some of the methods have been depriciated. I'll try to solve and enhance this in my free time.

**Comment by xinghao2003** [comment]
set zend.assertion to -1 in php.ini

**Comment by RTGDaCoder** [comment]
Indeed, this could actually fully disable once you've removed the php.ini check from the PHP bin itself.
