### ISSUE TITLE
Mob AI

### ISSUE THREAD

**Issue by G2PCraft** [GenisysPro/GenisysPro#380]
Many plugin that use function Entity don't support GenisysPro. but sopport PMMP. please fix

**Comment by G2PCraft** [comment]
Example 1 > if u use u will get this error [Server thread/CRITICAL]: TypeError: "Argument 2 passed to pocketmine\entity\Entity::createEntity() must be an instance of pocketmine\level\Level, instance of pocketmine\level\format\Chunk given, called in C:\Users\Administrator\Desktop\Murder\plugins\G2PCore\src\Core\Core.php on line 70" (EXCEPTION) in "/src/pocketmine/entity/Entity" at line 739
[16:19:06] [Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'G2P_Core v0.1': Argument 2 passed to pocketmine\entity\Entity::createEntity() must be an instance of pocketmine\level\Level, instance of pocketmine\level\format\Chunk given, called in C:\Users\Administrator\Desktop\Murder\plugins\G2PCore\src\Core\Core.php on line 70 on Core\Core

**Comment by Frago9876543210** [comment]
Argument 2 passed to pocketmine\entity\Entity::createEntity() must be an instance of pocketmine\level\Level! This is the plug-in's problem.

**Comment by Frago9876543210** [comment]
@G2PCraft You need to update the plug-in on api 3.0.0.

**Comment by BajanVlogs** [comment]
Instead of getChunk it needs to be getLevel since genisyspro uses Level's not Chunks

**Comment by G2PCraft** [comment]
@Frago9876543210 I will try and thank for helping

**Comment by G2PCraft** [comment]
@Frago9876543210 @BajanVlogs Thx you guys
