### ISSUE TITLE
Gitlab wont build

### ISSUE THREAD

**Issue by DerddyDert** [GenisysPro/GenisysPro#384]
Gitlab quit making builds. I dont know who set that up but can someone that has access fix it please.

**Comment by Leo3418** [comment]
SuperXingKong is responsible for the GitLab repository; I don't have write access.

**Comment by DerddyDert** [comment]
Thanks! I didn't know so I thought you might know.

**Comment by SuperXingKong** [comment]
My responsible... I will give you access

**Comment by DerddyDert** [comment]
Let me know in Discord please. Im closing this @SuperXingKong
