### ISSUE TITLE
This constant(Tile::DAY_LIGHT_DETECTOR) is undefined

### ISSUE THREAD

**Issue by ibookcc** [GenisysPro/GenisysPro#385]
> 问题描述：
> Tile::DAY_LIGHT_DETECTOR 这个常量没有定义
> 某些时候会导致奔溃，
> 也许是你们忘记了？
> 我在继承树中没有查到这个常量
> 翻查旧版本在 pocketmine/title/Title.php 中第55行加入
> const DAY_LIGHT_DETECTOR = "DLDetector";
> 后问题解决
> 不明所以，
> 是版本更新兼容还是忘记？（1.0.9版本也没有定义）
> 希望是我错了。

> Problem description：
> This constant(Tile::DAY_LIGHT_DETECTOR) is undefined
> Sometimes it can cause ulceration,
> Maybe you forgot?
> I didn't find this constant in the inheritance tree
> Check the old version and join the fifty-fifth line in pocketmine/title/Title.php
> Const DAY_LIGHT_DETECTOR = "DLDetector"";
> Post problem solving
> So unknown,
> Is the version updated, compatible or forgotten? (1.0.9 version is not defined)
> I hope I'm wrong.

GenisysPro Crash Dump Sun Jul 16 13:58:16 CST 2017

Error: Undefined class constant 'DAY_LIGHT_DETECTOR'
File: /src/pocketmine/tile/DLDetector
Line: 139
Type: notice

Code:
[130] 		}
[131] 		return true;
[132] 	}
[133] 
[134] 	/**
[135] 	 * @return CompoundTag
[136] 	 */
[137] 	public function getSpawnCompound(){
[138] 		return new CompoundTag("", [
[139] 			new StringTag("id", Tile::DAY_LIGHT_DETECTOR),
[140] 			new IntTag("x", (int) $this->x),
[141] 			new IntTag("y", (int) $this->y),
[142] 			new IntTag("z", (int) $this->z),
[143] 		]);
[144] 	}
[145] }
[146] 
[147] 
[148] 
[149] 

GenisysPro version: 0000000000000000000000000000000000000000 [Protocol 113; API 3.0.1]
uname -a: Linux iz8vb19op20ox1d6a6pmouz 3.10.0-514.21.2.el7.x86_64 #1 SMP Tue Jun 20 12:24:47 UTC 2017 x86_64
PHP version: 7.0.9
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 1 分 27 秒
Number of loaded worlds: 6
Players online: 1/2017

**Comment by MasterOfTheRealm** [comment]
What causes this to happen? im unable to reproduce the issue

**Comment by erkam2002** [comment]
You need a world with this block i reproduced this

**Comment by erkam2002** [comment]
Downloaded Map

**Comment by MasterOfTheRealm** [comment]
a downloaded map?  as in a pc generated world which has this block already placed?

**Comment by erkam2002** [comment]
Yes

**Comment by DerddyDert** [comment]
Wow. I love a clean informative report.

**Comment by ibookcc** [comment]
@MasterOfTheRealm Maybe i don't know how, but it's obviously syntax error (constant undefined). You check the source code, you can find

**Comment by chadigos** [comment]
可能是忘了

**Comment by chadigos** [comment]
以加上thanks!
