### ISSUE TITLE
Plugin support

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [GenisysPro/GenisysPro#387]
https://github.com/Muqsit/ChestShop
https://github.com/Muqsit/PlayerVaults

Please add support for these plugins, they work on PmmP.
ChestShop is not a priority.

**Comment by BajanVlogs** [comment]
Can you show us the errors your getting with PlayerVaults when u do /pv on GenisysPro

**Comment by TDMidkwhatisxd** [comment]
[Server thread/CRITICAL]: Unhandled exception executing command 'pv 1' in playervault: Call to undefined method pocketmine\Player::getLowerCaseName()
2017-07-16 [19:24:48] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\Player::getLowerCaseName()" (EXCEPTION) in "/PlayerVaults_v2.phar/src/PlayerVaults/Provider" at line 110

I didn't provide the issue, because I think there will be more after this is fixed.

**Comment by TDMidkwhatisxd** [comment]
I replaced all getlowercasename with substr() , and  bye errors, but vaults chest don't open, no errors in console. Ummmm

**Comment by Leo3418** [comment]
Please consider submitting this request at [GenisysProPlugins](https://github.com/GenisysProPlugins), an organization founded by some GenisysPro developers for resolving plugin-related issues. Thank you!

**Comment by MasterOfTheRealm** [comment]
We already fixed PlayerVaults, now will start on ChestShop
