### ISSUE TITLE
Enchanting Kits

### ISSUE THREAD

**Issue by BajanVlogs** [GenisysPro/GenisysPro#388]
16.07 14:47:35 [Server] Server thread/CRITICAL Error: "Call to undefined method pocketmine\item\enchantment\Enchantment::getEffectByName()" (EXCEPTION) in "/AdvancedKits-master/src/AdvancedKits/Kit" at line 105 16.07 14:47:35 [Server] Server thread/CRITICAL Unhandled exception executing command 'kit test' in kit: Call to undefined method pocketmine\item\enchantment\Enchantment::getEffectByName()

whats the solution

**Comment by erkam2002** [comment]
getEnchantmentByName

**Comment by BajanVlogs** [comment]
Fixed Thanks

**Comment by erkam2002** [comment]
:)
