### ISSUE TITLE
Efficiency No Effect

### ISSUE THREAD

**Issue by ldliuzhen** [GenisysPro/GenisysPro#391]
#### Issue description

Efficiency No Effect

#### Platform information

* GenisysPro version: 1.1

* PHP binary version:7

* Server OS:windows

* Game client:1.1.3

**Comment by MasterOfTheRealm** [comment]
Please elaborate

**Comment by ldliuzhen** [comment]
@MasterOfTheRealm For example: Diamond pickaxe efficiency V break block speed slower than normal diamond pickaxe...It doesn't work....

**Comment by XDqrkneZ** [comment]
bump

**Comment by GDRGamingzz** [comment]
Hi, this issue has been fixed few days ago. I would say this issue can be closed now.

**Comment by ldliuzhen** [comment]
@GDRGamingzz OK,thank you
