### ISSUE TITLE
Crops blockUpdata abnormal

### ISSUE THREAD

**Issue by ibookcc** [GenisysPro/GenisysPro#392]
# bug复现：

1. 在一块平坦的土地挖一格方块，
2. 然后在里面放置一桶水
3. 在这格水附近9X9范围内任意锄一块地
4. 种植作物，
5. 然后将水填平，
6. 过一段时间后
7. 锄过的地会变成普通土地
8. 但是作物依旧种植在这块普通土地上
9. 同样的bug也存在于甘蔗

# Bug replication:

1. Dig a square block over a flat ground,
2. Then place a bucket of water in it
3. Take a piece of land anywhere within the 9X9 range near the water
4. Plant crops,
5. Then fill up the water,
6. After a period of time
7. Hoe the land will become ordinary land
8. But crops are still planted on this common land
9. The same bug also exists in Sugarcane

# environment

- 2017 x86_64
- PHP version: 7.0.9
- Zend version: 3.0.0
- OS : Linux, linux

**Comment by ibookcc** [comment]
- # GenisysPro Crash Dump Sun Jul 16 13:58:16 CST 2017

**Comment by ibookcc** [comment]
- GenisysPro version: 0000000000000000000000000000000000000000 [Protocol 113; API 3.0.1]

**Comment by ibookcc** [comment]
GenisysPro版本：e6120fc @DerddyDert @MasterOfTheRealm

**Comment by ibookcc** [comment]
@DerddyDert I don understand. How you work? So this is ending, right?

**Comment by MasterOfTheRealm** [comment]
I tried to reproduce this and was not able to do so.
