### ISSUE TITLE
Message on Kick or Restart

### ISSUE THREAD

**Issue by FunnyBuddys** [GenisysPro/GenisysPro#395]
#### Issue description

The Message is Disconnected on Kick or Restart  and not kicked by admin or server closed

#### Platform information

* GenisysPro version: https://github.com/GenisysPro/GenisysPro/commit/e6120fc9f26e4879319985a61943b679a63ad0be

* PHP binary version: 7.0.12

* Server OS: Debian GNU/Linux 8 (jessie)

* Game client: Minecraft:PE v1.1.3 on Android

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by erkam2002** [comment]
Doch es funktioniert aber nur manchmal das ist glaube ein client bug.

Es works but only sometimes i think its an Client bug.

**Comment by VCraftMCPE** [comment]
its not a client bug works fine with pmmp

**Comment by FunnyBuddys** [comment]
Yep

**Comment by SuperKali** [comment]
#205 Reopen...

**Comment by MasterOfTheRealm** [comment]
No need for duplicate issues lol

**Comment by DerddyDert** [comment]
I dont understand? What exactly is the bug? Is it just giving the client the wrong feedback?

**Comment by chadigos** [comment]
怎样的kick  插件代码 $player->kick()有问题 还是游戏里/kick xxx

**Comment by sc00scoc** [comment]
I tried it on all platforms, this is a bug just on Genisys
