### ISSUE TITLE
Bug fix pls

### ISSUE THREAD

**Issue by SuperAdam47** [GenisysPro/GenisysPro#399]
https://youtu.be/vtgj2oJgN6M  
1. After a player throws an item in creative mode, the item won't disappear from player inventory. In an MCPE local game, it should disappear in this case.  
![screenshot_20170718-085154](https://user-images.githubusercontent.com/14175175/28295907-f82de6a8-6b96-11e7-9fd5-e3ef8baab2c0.png)
2. When a player's mode is changed from creative to survival, the UI shows water bubbles wrongly, as if the player is in water.  
![screenshot_20170718-084851](https://user-images.githubusercontent.com/14175175/28295922-1b20ef20-6b97-11e7-80f8-0a4c9a6a2aed.png)

**Comment by SuperKali** [comment]
@SuperAdam47 This is not a bug..... disable all plugin and test

**Comment by SuperXingKong** [comment]
And... i can't visit youtube... Chinese GTW...

**Comment by SuperKali** [comment]
@SuperXingKong this is not bug...

**Comment by SuperXingKong** [comment]
@SuperKali ~Thank you. Wait for @DerddyDert to confirm xD

**Comment by SuperKali** [comment]
Ok


On Jul 18, 2017 1:20 AM, "SuperXingKong" <notifications@github.com> wrote:

@SuperKali <https://github.com/superkali> ~Thank you. Wait for @DerddyDert
<https://github.com/derddydert> to confirm xD

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/GenisysPro/GenisysPro/issues/399#issuecomment-315912779>,
or mute the thread

**Comment by BajanVlogs** [comment]
@SuperAdam47 Ik this bug PR #386 fixes all this 

its the inventory bug 
and it needs to be fully tested and accepted ASAP

**Comment by Leo3418** [comment]
@SuperXingKong I've added text description and screenshots to issue description

**Comment by MasterOfTheRealm** [comment]
The Air Bubble glitch happens when you run on a 32bit system

**Comment by Leo3418** [comment]
@MasterOfTheRealm so I guess it's an issue related to PHP binary? Because PocketMine-MP will work on both 32-bit and 64-bit system, as long as you use the correct PHP binary for your system type.

**Comment by DerddyDert** [comment]
As soon as @Frago9876543210 or @SuperXingKong approves the #386  fix we can merge it. All are welcome to review and comment as well.  I've been working on my own server today so I didn't have a chance to test issues, sorry.

**Comment by MasterOfTheRealm** [comment]
@Leo3418 perhaps i just pointed it out for now

**Comment by SuperAdam47** [comment]
@SuperKali this is bug. 0 plugins loaded

**Comment by SuperAdam47** [comment]
@SuperKali 
There are the same water balloon error in the absence of attachments.

**Comment by SuperKali** [comment]
@SuperAdam47 i have old src

**Comment by SuperAdam47** [comment]
Sorry this is my plugin bug

**Comment by DerddyDert** [comment]
https://github.com/GenisysProPlugins/PluginRequests submit request for plugin fix/rewrite here. @SuperAdam47

**Comment by SuperAdam47** [comment]
No thanks im fixed the bug
