### ISSUE TITLE
Windows 10 Crashes

### ISSUE THREAD

**Issue by BajanVlogs** [GenisysPro/GenisysPro#401]
When typeing fast on windows 10 on GenisysPro servers like
/spawn 
and then u do a mistake like
/spanw
it will freeze ur client 
anyone else having this issue

**Comment by DerddyDert** [comment]
Try the same thing but slow. Maybe a bad command is causing this?

**Comment by BajanVlogs** [comment]
i do it slow same thing still

**Comment by TDMidkwhatisxd** [comment]
Ik bajang, it happens on all forks and even PMMP. Whats worse,  it leaks so much memory it use all 4gb ram I have on pc and pc freeze, until it crash xD.

**Comment by Pizzahaet** [comment]
@BajanVlogs This is the client, ever since 1.1.2 it has happenened

**Comment by DerddyDert** [comment]
So whats happening is when an invalid command is entered there is a memory leak? What feedback are you getting when you type the wrong command?

**Comment by Pizzahaet** [comment]
Remove the memory leak label as it is not that, it is the client that is doing it

**Comment by DerddyDert** [comment]
even so its leaking mem in the client. If we fix how it processes the invalid commands couldn't we avoid the issue?

**Comment by Pizzahaet** [comment]
@DerddyDert it is a client bug there isn't much you can do about it

**Comment by TDMidkwhatisxd** [comment]
My windows10 laptop use all 4gb ram on mcpe client and freeze until I restart.
Workaround: Wen mcpe is stuck for 2 seconds , alt+f4    xD

**Comment by GDRGamingzz** [comment]
its an application bug, ever since 1.1.0 update has been added for windows 10 users. this issue cannot be solved we need to report this to mojang hopefully they would fix it.

**Comment by Asuna-Yuuki** [comment]
its a client bug @DerddyDert  we need to wait for fix from mojang

**Comment by Asuna-Yuuki** [comment]
so redmove mamory leak tingie

**Comment by herojhjhLB** [comment]
Its client bug on 1.1
