### ISSUE TITLE
Plugin's load error

### ISSUE THREAD

**Issue by AydarTop** [GenisysPro/GenisysPro#403]
#### Issue description
Sometimes all plugin's not loaded after server restart. 

2017-07-17 [22:36:16] [Server thread/CRITICAL]: BadMethodCallException: "Phar error: Cannot retrieve contents, "plugin.yml" in phar "/srv/data/plugins/ServerAuth.phar": phar error: internal corruption of phar "/srv/data/plugins/ServerAuth.phar" (actual filesize mismatch on file "plugin.yml")" (EXCEPTION) in "/src/pocketmine/plugin/PharPluginLoader" at line 88

**Comment by DerddyDert** [comment]
Ahh.. What you say may be true but it looks like you have an issue specifically file related as well. Assume your phar is damaged and go get the src and run from src. Then let me know what happened. Thanks

**Comment by BajanVlogs** [comment]
I see your issue please update your SimpleAuth.phar and let me know what happens if any new errors just leave me a comment and I'll be sure to fix it.

**Comment by AydarTop** [comment]
@BajanVlogs This is not plugin issue, because all plugins not loaded  with this error and they loaded after second server restart.

**Comment by BajanVlogs** [comment]
'corruption of phar' read this that means it's the SimpleAuth.phar its causing the plugin.yml to crash please just update it and tell me

**Comment by DerddyDert** [comment]
Pull all your plugins then add them back one at a time until you get the error then let us know which plugin it is. All of everyone's plugins always load. This issue is with your server only.

**Comment by BajanVlogs** [comment]
When one plugin has this error you should update it

**Comment by AydarTop** [comment]
@DerddyDert This error happened with all plugins on my server, they load not always

**Comment by DerddyDert** [comment]
So you need to troubleshoot to see why. Follow my steps.

**Comment by TDMidkwhatisxd** [comment]
This plugin is bad compiled. I have no problems.

**Comment by DerddyDert** [comment]
Wait did you use the mp command in Genisyspro? That may need to get looked into. @AydarTop

**Comment by DerddyDert** [comment]
@TDMidkwhatisxd did you join our discord? You should stop by if you haven't yet.

**Comment by TDMidkwhatisxd** [comment]
done I'm asterw10, you were talking about some mmorpg setting in your server xd, and I told u to use kits xd

**Comment by AydarTop** [comment]
@DerddyDert No. I think it's Phar app issue. Phar app is bad compled all my plugins. I download this app from GooglePlay.

**Comment by AydarTop** [comment]
@DerddyDert I'll try compile plugins with DevTools(/makeplugin command) and test.

**Comment by Pizzahaet** [comment]
When you have plugins that aren't compiled the server will attempt to load them if you do /reload but it can't because there is no folder plugin loader loaded first so it just skips it most of the time it won't even show that it even tried
