### ISSUE TITLE
Particle Not work

### ISSUE THREAD

**Issue by Prisane** [GenisysPro/GenisysPro#41]
#### Issue description
addParticle function not working

#### Steps to reproduce the issue
```
$vec = new Vector3($player->x, $player->y, $player->z);
$player->getLevel()->addParticle(new ExplodeParticle($vec, 3));
```
#### OS and versions

* Genisys: [eec03ea](https://github.com/GenisysPro/GenisysPro/commit/eec03eae0442a70f84229fa6ee4bddaad96d6281)
* PHP: 7
* Server OS: lunix
* Game version: 1.0.8 W10

**Comment by SuperXingKong** [comment]
Try it again 😊

**Comment by Prisane** [comment]
Still same. Did you try?

**Comment by SuperXingKong** [comment]
Sorry, I am busy preparing exams and don't have time to test it.How about you?Can you help test it?If possible,plz fix it and pull it xD. @DerddyDert

**Comment by GdBai** [comment]
guys, multiple grammar mistakes in the chat above. and use space after punctuation

**Comment by SuperXingKong** [comment]
I am sorry for my bad grammer. Never too old to study, won't you?

**Comment by Prisane** [comment]
I tried every method. Particles do not appear.

**Comment by DerddyDert** [comment]
@Prisane please join our discord for more assistance.
