### ISSUE TITLE
Language problem

### ISSUE THREAD

**Issue by ibookcc** [GenisysPro/GenisysPro#410]
# 复现
1. 删除一切配置文件
2. 开启服务器
3. 在控制台中的配置文件初始化教程中设置除了英语的其他语言
4. 当服务器启动的时候显示的语言还是英语
5. 我检查了配置文件pocketmine.yml
```
settings:
 #Three-letter language code for server-side localization
 #Check your language code on https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes
 language: "eng"
```
这是一个十分古老的问题，很简单，但是一直没解决
我从0.10.0开始就发现存在这个问题了

# repetition
1. delete all configuration files
2. open server
3. in the setup wizard, choose a language other than English
4. when the server starts, the language displayed is still English
5. I checked the configuration file pocketmine.yml
```
settings:
 #Three-letter language code for server-side localization
 #Check your language code on https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes
 language: "eng"
```
This is a very old problem, very simple, but has not been resolved
I found this problem from the beginning of 0.10.0

# environment
- 2017 x86_64
- PHP：7.0.9
- Zend：3.0.0
- OS：Linux, CentOS7.2

**Comment by Leo3418** [comment]
如果*“很简单”*，欢迎您修复这个问题后直接给我们发送pull request。
If it IS *"very simple"*, we'd like you to fix this issue and send a pull request to us.

**Comment by ibookcc** [comment]
@Leo3418 i don't know how to use GitHub to edit code.And what pull is?
