### ISSUE TITLE
Inventory BUG ?

### ISSUE THREAD

**Issue by ldliuzhen** [GenisysPro/GenisysPro#411]
#### Issue description

In genisys.yml inventory:allow-cheats: false, player can not enchant.......All material has been returned
...........If allow-cheats choice true ,server can not prevent the cheater modify goods .....like use toolbox
#### Platform information

* GenisysPro version:1.1

* PHP binary version:7

* Server OS:windows

* Game client:1.1.3

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by MasterOfTheRealm** [comment]
well...its a problem with floating inventory that verifies items i think...

**Comment by DerddyDert** [comment]
Didnt we just have a PR for that?

**Comment by Leo3418** [comment]
@ldliuzhen sorry, no ETA could be provided.

**Comment by akaSnapy** [comment]
Thisnl will be fixed in 1.2, close the issue.

**Comment by ldliuzhen** [comment]
OK，thank you
