### ISSUE TITLE
Can you say me what's the problem?

### ISSUE THREAD

**Issue by ivan691** [GenisysPro/GenisysPro#413]
My server freezes very often after going to 1.1..
Here's timings: https://timings.pmmp.io/?url=25126655
Can someone help me?

**Comment by TDMidkwhatisxd** [comment]
hardware specs?

**Comment by ivan691** [comment]
I'm use hosting 24serv.pro

**Comment by MasterOfTheRealm** [comment]
All your plugins that uses tasks causes this.... hopefully we can come up with a solution for that

**Comment by DerddyDert** [comment]
Its on all spoons. Which plugins are you using? We may have a modified replacement already. @ivan691

**Comment by TDMidkwhatisxd** [comment]
hosting give only 1 cpu core, and some ram. I had so many troubles with hosters.
Vps is the way.

**Comment by akaSnapy** [comment]
You have to know genisyspro uses alot of resources also it needs a good internet speed, use digi-performance.net to handle a good server.

**Comment by DerddyDert** [comment]
Need lots of good cores

**Comment by akaSnapy** [comment]
@DerddyDert The internet speed is the most needed thing
