### ISSUE TITLE
closed player

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [GenisysPro/GenisysPro#415]
: InvalidStateException: "Trying to get permissions of closed player" 

What means if a player is closed?

**Comment by MasterOfTheRealm** [comment]
plugin problem... might be when a player is offline

**Comment by MasterOfTheRealm** [comment]
Test (ignore this)

**Comment by DerddyDert** [comment]
Oh wow this is gonna be nice

**Comment by MasterOfTheRealm** [comment]
Yep
