### ISSUE TITLE
Bone powder generation plant problem

### ISSUE THREAD

**Issue by nishuo** [GenisysPro/GenisysPro#44]
#### Issue description

Bone powder click on grass can not produce high grass and chrysanthemum and fern. Can only produce a single grass and rose and dandelion. Please perfect. Thank you
#### OS and versions

* Genisys:GenisysPro
* PHP:7.0.17
* Server OS:Linux
* Game version: 1.0.8

**Comment by SuperXingKong** [comment]
I will test and enhance it.@lightda104530 @Leo3418 @chadigos Need help!

**Comment by nishuo** [comment]
Thank you

**Comment by DerddyDert** [comment]
Can we add this to To-Do and close issue?

**Comment by lightda104530** [comment]
I think this is sloved..
