### ISSUE TITLE
 hotbar links error

### ISSUE THREAD

**Issue by mote166** [GenisysPro/GenisysPro#45]
#### Issue description

 im having this error for a while . i know this is a plugin issue but i know nothing in coding and this error is causing server lagg . please help me . whats the plugin that is causing this?
#### Steps to reproduce the issue

no idea
#### OS and versions

* Genisys: GenisysPro-1.0.0dev starry
* PHP: 7.0.11
* Server OS: linux
* Game version: 1.0.8 (android)

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
Deprecated: Do not attempt to change hotbar links in plugins! in phar:///jar/VERY/server17506-11.phar/src/pocketmine/inventory/PlayerInventory.php on line 105 13.05 22:54:54 [Server] INFO Deprecated: Do not attempt to change hotbar links in plugins! in phar:///jar/VERY/server17506-11.phar/src/pocketmine/inventory/PlayerInventory.php on line 105
```
heres my plugins list:

 Plugins (46): StatsPE v3.3.4, KillMoney v1.5, Broadcaster v1.16, 1vs1 v0.0.5, PurePerms v1.3.5, ServerAuth v2.13, ClearLagg v1.1.0, PassHack v1.2, TimeCommander v2.1, PvPWorlds v1, SlapperRotation v1.0.1, DevTools v1.11.0, BanWarn v1.2.1, MSpawns v1.4, Rotater v1.1.0, NoExplode v1, ColorMatch v1.1.2, CoreProtect v0.1.5, AntiSpam v1.3, WorldEdit+ v0.01, WorldFixer v1, EconomyAPI v2.0.9, NoAdvertisingPE v1.0.1, Whois v3, WorldProtect v2.2.0, SignChanger v1, TapToDo v2.2.1, FlyCommand v1.0.0, iProtector v3.1b, BBDoDo vNetherBox, SAC v3.2.1, AdvancedKits v5.0b1, ManyWorlds v2.0.3, Slapper v1.3.3, EssentialsPE v2.0.0, BlockCmdPE v1.0.0, PmChair v1.3, DisguiseMe v1.1, NobadWordsKHAV v1.0.3, EnderParkour v1.0.0, LiveTexts v1.4pre, SW_svile v0.6dev, EDB-Pro v, EconomyShop v2.0.7, PureChat v1.4.0, MyPlot v1.1.3

**Comment by SuperXingKong** [comment]
I will recheck the PlayerInventory in my spare time.

**Comment by SuperXingKong** [comment]
We hope you can check your plugin one-by-one and resolve it by yourself.Find the problem plugin and report it to us.It will be useful.😀

**Comment by mote166** [comment]
sorry im busy with exams i can't do it

**Comment by DerddyDert** [comment]
@mote166 can u zip all ur plugins and send them to me on discord? Ill thoroughly test them out for ya and report my findings here.

**Comment by DerddyDert** [comment]
@SuperXingKong Do we happen to have or would you like if I create the official Discord chat for GenisysPro? That way we can keep the Issues section a little more clean and efficient and offer better communication between GenisysPro developers, plugin developers and GenisysPro users.

**Comment by MCNationPE** [comment]
@DerddyDert I think is good idea

**Comment by lightda104530** [comment]
@DerddyDert  Great idea:D

**Comment by SuperXingKong** [comment]
@DerddyDert Yeah,It's such a good idea.But I don't know How to create it .Who can help me?

**Comment by DerddyDert** [comment]
Ill set it up and then post the link here then invite you guys and set your roles.

**Comment by DerddyDert** [comment]
GenisysPro discord link https://discord.gg/WrKzRNn I'm at work right now. Ill set everything up (mods admins owner channels) as soon as I get off.

**Comment by DerddyDert** [comment]
Most stuff is already setup now

**Comment by SuperXingKong** [comment]
You are using an old plugin.See #54 for how to resolve it.
