### ISSUE TITLE
GenisysPro Discord Chat

### ISSUE THREAD

**Issue by DerddyDert** [GenisysPro/GenisysPro#46]
Please use the following link to join the **GenisysPro** Discord chat: https://discord.gg/WrKzRNn

**Comment by Leo3418** [comment]
We can add this to README.

**Comment by MCNationPE** [comment]
yes

**Comment by DerddyDert** [comment]
Can the official GenisysPro developer team please post their whole discord username here so I can ensure I am handing over the roles to the correct people? E.g., `Derddy #9877` Thanks

**Comment by MCNationPE** [comment]
@DerddyDert  my nick name is herojhjh

**Comment by DerddyDert** [comment]
there is a number after the nick  ;) For 101% security...

**Comment by DerddyDert** [comment]
@Leo3418 as soon as you can log in I can go ahead and set your role. Thanks

**Comment by nishuo** [comment]
I love u ,bro

**Comment by Leo3418** [comment]
@DerddyDert thanks, I scarcely have much time to involve in this project, so I don't need mod, but I'm still pleased to join the conversation as a normal member.

**Comment by DerddyDert** [comment]
ill add you just in case

**Comment by Leo3418** [comment]
Leo3418#6467

**Comment by lightda104530** [comment]
My discord is lightda #2034

**Comment by SuperXingKong** [comment]
It is useful.My discord is SuperXingKong#2054.

**Comment by SuperXingKong** [comment]
Since you have already added this to README, I am going to close this issue.😄
