### ISSUE TITLE
Resource pack not downloading

### ISSUE THREAD

**Issue by Prisane** [GenisysPro/GenisysPro#47]
#### Issue description
Does not download resource pack when it join server

#### Steps to reproduce the issue
- enable resourcepacks
- set resource_stack
- join the server and click on the "download and join" button

#### OS and versions

* Genisys: [740c8a9](https://github.com/GenisysPro/GenisysPro/commit/740c8a9b587a2a32ab6b4922a80f5f19ec0a682b)
* PHP: 7
* Server OS: lunix
* Game version: 1.0.8 W10

![1](https://cloud.githubusercontent.com/assets/13530796/26274552/e9ee8112-3d54-11e7-9134-cc6a0f96ad1a.PNG)
![2](https://cloud.githubusercontent.com/assets/13530796/26274553/e9ee917a-3d54-11e7-9ca7-8e6afaab2a8f.PNG)

**Comment by SuperXingKong** [comment]
Did you install OpenSSL extension?

**Comment by Prisane** [comment]
No, do I have to install it?

**Comment by nishuo** [comment]
@Prisane Yes,Please install 

yum install openssl-devel -y

**Comment by Prisane** [comment]
@SuperXingKong now it is fixed but game crashes when i join the server

**Comment by Prisane** [comment]
Pmmp does not have such a problem
