### ISSUE TITLE
Resource pack crash

### ISSUE THREAD

**Issue by Prisane** [GenisysPro/GenisysPro#48]
#### Issue description
game crashes when i join the server

#### Steps to reproduce the issue
- enable resourcepacks
- set resource_stack
- join the server and click on the "download and join" button

#### OS and versions

* Genisys: [5692cf9](https://github.com/GenisysPro/GenisysPro/commit/5692cf97ed19d9031ff8b99cdb99ebe7360b8d66)
* PHP: 7
* Server OS: lunix
* Game version: 1.0.8 W10

**Comment by Leo3418** [comment]
Thanks for reporting. Unfortunately, you did not provide sufficient information that could help us pinpoint or solve this issue. Please provide more details to your issue, especially any error message or error log. Otherwise, we may close this issue.

**Comment by SuperXingKong** [comment]
I think it may be an issue with the pack itself.

According to my client, it downloads and verifies the pack just fine, but is for some reason unable to apply it. Will investigate.
