### ISSUE TITLE
Elytra Speed

### ISSUE THREAD

**Issue by Prisane** [GenisysPro/GenisysPro#49]
#### Issue description
I goes too fast when you flying with elytra. According to Vanilla, the speed must be reduced.

#### OS and versions
* Genisys: [5692cf9](https://github.com/GenisysPro/GenisysPro/commit/5692cf97ed19d9031ff8b99cdb99ebe7360b8d66)
* PHP: 7
* Server OS: lunix
* Game version: 1.0.8 W10

**Comment by SuperXingKong** [comment]
😀#50 Can you fix it by yourself?

**Comment by Prisane** [comment]
i don't know. Very absurd flying with elytra very fast. There is no such this problem in pmmp.

**Comment by SuperXingKong** [comment]
Anti-cheat system needs a big update.

**Comment by SuperXingKong** [comment]
Did you use a plugin for extra wings?If so, could you show it to me?

**Comment by SuperXingKong** [comment]
Strangely. I test this but it worked well.

**Comment by DerddyDert** [comment]
Im closing this as we have big replicatable issues and it cannot be replicated in official testing.
