### ISSUE TITLE
Redstone

### ISSUE THREAD

**Issue by ldliuzhen** [GenisysPro/GenisysPro#56]
后台警告如下

Warning: yaml_parse(): end of stream reached without finding document 0 in phar://D:/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/utils/Config.php on line 140

Warning: yaml_emit(): Invalid UTF-8 sequence in argument in phar://D:/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/utils/Config.php on line 192

顺便问一下,红石只能影响一格？？
#### OS and versions

* Genisys:1.1dev
* PHP:7
* Server OS:windows
* Game version: 1.0.9

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by SuperXingKong** [comment]
核心无问题, 检查你的 *Society* 插件

**Comment by SuperXingKong** [comment]
红石需要修复

**Comment by DerddyDert** [comment]
@SuperXingKong is this still an issue?

**Comment by SuperXingKong** [comment]
@DerddyDert Still a little bug

**Comment by PillarsZhang** [comment]
Hope this bug can be fixed early.

**Comment by BajanVlogs** [comment]
This was fixed close this

**Comment by DerddyDert** [comment]
Where was it fixed?

**Comment by BajanVlogs** [comment]
redstone was fixed awhile ago works ok for me atleast

**Comment by Pizzahaet** [comment]
Bajan please kill yourself godd

**Comment by PillarsZhang** [comment]
It is still a big problem.Because there is a lot of limits without normal redstones.
I think the point of GenisysPro is to make user feel like they are play on local mcpe with full functions,and they don't need to call about whether redstones can be use or not...whether a goods is allowed or not...
Thank you.

**Comment by PillarsZhang** [comment]
![screenshot_2017-07-25-13-48-26-319_com mojang min](https://user-images.githubusercontent.com/13759663/28557634-2d3263fc-7140-11e7-8b27-e706911bebb6.png)
It was fixed a lot in the lasted version.But there is still bugs if I do like this in the picture.A long road to walk!

**Comment by ldliuzhen** [comment]
Cool bro
