### ISSUE TITLE
Call to undefined method class@anonymous::handle()

### ISSUE THREAD

**Issue by ChaostixZix** [GenisysPro/GenisysPro#57]
* Genisys: GenisysPro-1.1dev Starry
* PHP: 7.0.3
* Server OS: Mac Os X Sierra 10.12.5
* Game version: 1.0.7

Hi, I Was Using GenisysPro For My MCPE Server

But, I Want To Ask Something

There Is A Function On  [Here](https://github.com/GenisysPro/GenisysPro/blob/89b950dbdd76f0e4865067a522fbb7de0a4007cf/src/pocketmine/network/protocol/ResourcePackDataInfoPacket.php)

> public function handle(NetworkSession $session) : bool{
		return $session->handleResourcePackDataInfo($this);
	}

But, I Cant Find NetworkSession Class On GenisysPro, Is It Not Implemented Yet?

And, One More Thing. Why There's No Handle() Function On [Here](https://github.com/GenisysPro/GenisysPro/blob/master/src/pocketmine/network/protocol/LoginPacket.php) ?
I Need It For Specter Plugins

Thats Why I Get This Error 

> Call to undefined method class@anonymous::handle()

**Comment by SuperXingKong** [comment]
We use another way to handle packets.
There's a function handleDataPacket() on Player.php.

**Comment by ChaostixZix** [comment]
thanks :D

**Comment by ChaostixZix** [comment]
@SuperXingKong 
Like This?

> $pk = new class() extends LoginPacket{
                public function decodeAdditional(){
                }
            };
            $pk->username = $username;
            $pk->gameEdition = 0;
            $pk->protocol = ProtocolInfo::CURRENT_PROTOCOL;
            $pk->clientUUID = UUID::fromData($address, $port, $username);
            $pk->clientId = 1;
            $pk->identityPublicKey = "key here";
            $pk->skin = str_repeat("\x80", 64 * 32 * 4);
            $pk->skinId = 1;

            $pk->handleDataPacket($player);

**Comment by ChaostixZix** [comment]
@SuperXingKong

**Comment by lightda104530** [comment]
Yep

**Comment by ChaostixZix** [comment]
@SuperXingKong I got this error

>Server thread/CRITICAL]: Unhandled exception executing command 'specter spawn h' in specter: Argument 1 passed to pocketmine\Player::handleDataPacket() must be an instance of pocketmine\network\protocol\DataPacket, instance of specter\network\SpecterPlayer given, called in /Users/chaostix/Desktop/PM/plugins/Specter-master/src/specter/network/SpecterInterface.php on line 166

**Comment by SuperXingKong** [comment]
You must use handleDataPacket($pk)
($pk is an instance of DataPacket)

**Comment by SuperXingKong** [comment]
Keep asking if you still don't understand.

**Comment by DerddyDert** [comment]
Awesome positive attitude.

**Comment by ChaostixZix** [comment]
How About $pk->canBeBatched()? @SuperXingKong
