### ISSUE TITLE
beacon error

### ISSUE THREAD

**Issue by Asuna-Yuuki** [GenisysPro/GenisysPro#593]
#### Issue description
 try open the beacon then you wil get a eror

#### Platform information

* GenisysPro version: 1.1dev liama spit latest

* PHP binary version: 7.0.21

* Server OS: windows 7

* Game client: 1.1.4

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```
 Error: "Call to a member function getInventory() on null" (EXCEPTION) in "/src/pocketmine/block/Beacon" at line 133

```

**Comment by Asuna-Yuuki** [comment]
i try it with no plugins

**Comment by MasterOfTheRealm** [comment]
I get no such error. Are you using the latest src?

**Comment by Asuna-Yuuki** [comment]
yes @MasterOfTheRealm

**Comment by armagadon159753** [comment]
@Asuna-Yuuki no error for. ^~^
