### ISSUE TITLE
Redstone Lamp Crash

### ISSUE THREAD

**Issue by BajanVlogs** [GenisysPro/GenisysPro#596]
GenisysPro Crash Dump Thu Jul 20 21:38:54 UTC 2017

Error: Undefined class constant 'INACTIVE_REDSTONE_LAMP'
File: /src/pocketmine/block/RedstoneWire
Line: 200
Type: notice

Code:
[191] 	/**
[192] 	 * @param array $ignore
[193] 	 *
[194] 	 * @return bool|void
[195] 	 */
[196] 	public function activate(array $ignore = []){
[197] 		if($this->canCalc()){
[198] 			$block = $this->getSide(Vector3::SIDE_DOWN);
[199] 			/** @var ActiveRedstoneLamp $block */
[200] 			if($block->getId() == Block::INACTIVE_REDSTONE_LAMP or $block->getId() == Block::ACTIVE_REDSTONE_LAMP) $block->turnOn();
[201] 
[202] 			$side = $this->getUnconnectedSide();
[203] 
[204] 			$sides = [Vector3::SIDE_WEST, Vector3::SIDE_EAST, Vector3::SIDE_SOUTH, Vector3::SIDE_NORTH];
[205] 			foreach($sides as $s){
[206] 				if(!in_array($s, $side[1])){
[207] 					$block = $this->getSide(Vector3::SIDE_DOWN)->getSide($s);
[208] 					$this->activateBlock($block);
[209] 				}
[210] 			}

Backtrace:
#0 /src/pocketmine/block/RedstoneSource(126): pocketmine\block\RedstoneWire->calcSignal(integer 15, integer 3)
#1 /src/pocketmine/block/RedstoneSource(175): pocketmine\block\RedstoneSource->activateBlock(pocketmine\block\RedstoneWire Block[Redstone Wire] (55:15))
#2 /src/pocketmine/block/PressurePlate(62): pocketmine\block\RedstoneSource->activate(boolean)
#3 /src/pocketmine/Player(1633): pocketmine\block\PressurePlate->onEntityCollide(pocketmine\Player Player(10703))
#4 /src/pocketmine/entity/Entity(1280): pocketmine\Player->checkBlockCollision(boolean)
#5 /src/pocketmine/entity/Living(211): pocketmine\entity\Entity->entityBaseTick(integer 1)
#6 /src/pocketmine/entity/Human(640): pocketmine\entity\Living->entityBaseTick(integer 1, integer 0)
#7 /src/pocketmine/Player(2025): pocketmine\entity\Human->entityBaseTick(integer 1)
#8 /src/pocketmine/Server(2519): pocketmine\Player->onUpdate(integer 90420)
#9 /src/pocketmine/Server(2726): pocketmine\Server->checkTickUpdates(integer 90420, double 1500586734.348)
#10 /src/pocketmine/Server(2446): pocketmine\Server->tick(boolean)
#11 /src/pocketmine/Server(2324): pocketmine\Server->tickProcessor(boolean)
#12 /src/pocketmine/Server(1922): pocketmine\Server->start(boolean)
#13 /src/pocketmine/PocketMine(488): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/minecraft/multicraft/servers/server6/jar/pocketmine/, string /home/minecraft/multicraft/servers/server6/, string /home/minecraft/multicraft/servers/server6/plugins/)

GenisysPro version: 0000000000000000000000000000000000000000 [Protocol 113; API 3.0.1]
uname -a: Linux vps 2.6.32-042stab106.4 #1 SMP Fri Mar 27 15:19:28 MSK 2015 x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 1 hours 50 minutes 57 seconds
Number of loaded worlds: 5
Players online: 31/100

This needs to be fixed this wasn't a issue before but since the new src its crashing my server

**Comment by DerddyDert** [comment]
@MasterOfTheRealm can you follow up on that?

**Comment by BajanVlogs** [comment]
Nvm its fixed

**Comment by BajanVlogs** [comment]
U can close the issue before mine too

**Comment by armagadon159753** [comment]
https://github.com/armagadon159753/GenisysPro-armagadon159753-
Check its
