### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by BajanVlogs** [GenisysPro/GenisysPro#598]
GenisysPro Crash Dump Thu Jul 20 23:46:46 UTC 2017

Error: Argument 1 passed to pocketmine\math\Vector3::getOppositeSide() must be of the type integer, array given, called in /home/minecraft/multicraft/servers/server6/jar/pocketmine/src/pocketmine/block/RedstoneWire.php on line 225
File: /src/pocketmine/math/Vector3
Line: 239
Type: notice

Code:
[230] 	/**
[231] 	 * Returns the Vector3 side number opposite the specified one
[232] 	 *
[233] 	 * @param int $side 0-5 one of the Vector3::SIDE_* constants
[234] 	 *
[235] 	 * @return int
[236] 	 *
[237] 	 * @throws \InvalidArgumentException if an invalid side is supplied
[238] 	 */
[239] 	public static function getOppositeSide(int $side) : int{
[240] 		if($side >= 0 and $side <= 5){
[241] 			return $side ^ 0x01;
[242] 		}
[243] 
[244] 		throw new \InvalidArgumentException("Invalid side $side given to getOppositeSide");
[245] 	}
[246] 
[247] 	/**
[248] 	 * @param Vector3 $pos
[249] 	 *

Backtrace:
#0 /src/pocketmine/block/RedstoneWire(382): pocketmine\block\RedstoneWire->activate(boolean)
#1 /src/pocketmine/block/RedstoneSource(126): pocketmine\block\RedstoneWire->calcSignal(integer 15, integer 3)
#2 /src/pocketmine/block/RedstoneSource(175): pocketmine\block\RedstoneSource->activateBlock(pocketmine\block\RedstoneWire Block[Redstone Wire] (55:15))
#3 /src/pocketmine/block/PressurePlate(62): pocketmine\block\RedstoneSource->activate(boolean)
#4 /src/pocketmine/Player(1633): pocketmine\block\PressurePlate->onEntityCollide(pocketmine\Player Player(16914))
#5 /src/pocketmine/entity/Entity(1280): pocketmine\Player->checkBlockCollision(boolean)
#6 /src/pocketmine/entity/Living(211): pocketmine\entity\Entity->entityBaseTick(integer 1)
#7 /src/pocketmine/entity/Human(640): pocketmine\entity\Living->entityBaseTick(integer 1, integer 0)
#8 /src/pocketmine/Player(2025): pocketmine\entity\Human->entityBaseTick(integer 1)
#9 /src/pocketmine/Server(2519): pocketmine\Player->onUpdate(integer 97890)
#10 /src/pocketmine/Server(2726): pocketmine\Server->checkTickUpdates(integer 97890, double 1500594406.1187)
#11 /src/pocketmine/Server(2446): pocketmine\Server->tick(boolean)
#12 /src/pocketmine/Server(2324): pocketmine\Server->tickProcessor(boolean)
#13 /src/pocketmine/Server(1922): pocketmine\Server->start(boolean)
#14 /src/pocketmine/PocketMine(488): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/minecraft/multicraft/servers/server6/jar/pocketmine/, string /home/minecraft/multicraft/servers/server6/, string /home/minecraft/multicraft/servers/server6/plugins/)

GenisysPro version: 0000000000000000000000000000000000000000 [Protocol 113; API 3.0.1]
uname -a: Linux vps 2.6.32-042stab106.4 #1 SMP Fri Mar 27 15:19:28 MSK 2015 x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 1 hours 54 minutes 31 seconds
Number of loaded worlds: 5
Players online: 31/100

**Comment by MasterOfTheRealm** [comment]
do you have redstone on your server enabled?

**Comment by BajanVlogs** [comment]
yes

**Comment by erkam2002** [comment]
@BajanVlogs how can i reproduce that?

**Comment by DerddyDert** [comment]
@armagadon159753

**Comment by armagadon159753** [comment]
@DerddyDert lest make pull request ^~^
