### ISSUE TITLE
A Question

### ISSUE THREAD

**Issue by ldliuzhen** [GenisysPro/GenisysPro#600]
#### Issue description

Warning: yaml_parse(): end of stream reached without finding document 0 in phar://D:/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/utils/Config.php on line 141

This warning wil appear when plugin use this code 
```
			if($this->Block->exists($pos_name))
			{
				$this->Block->remove($pos_name);
				$this->Block->save();
			}

```
Block is yml file

Is the code problem?Or genisyspro problem?

#### Platform information

* GenisysPro version:1.1

* PHP binary version:7

* Server OS:windows

* Game client:1.1.3

**Comment by MCNationPE** [comment]
config.yml error

**Comment by erkam2002** [comment]
It cant find Block.yml
