### ISSUE TITLE
Server Crash!

### ISSUE THREAD

**Issue by BexiPE** [GenisysPro/GenisysPro#603]
**Isue Description**
When I teleport to a map (higher than 10mb), Crashes the Server

**Error**
Error: Undefined class constant 'DAY_LIGHT_DETECTOR'
File: /src/pocketmine/tile/DLDetector
Line: 139
Type: notice

**Version**
GenisysPro version: 0000000000000000000000000000000000000000 [Protocol 113; API 3.0.1]
uname -a: Linux fireblaze 2.6.32-042stab112.15 #1 SMP Tue Oct 20 17:22:56 MSK 2015 x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

**Comment by armagadon159753** [comment]
can you send me you map

**Comment by BexiPE** [comment]
This is all maps Than higher 8mb... 10mb...  :(

**Comment by armagadon159753** [comment]
Can you send me you map.
I have test with 230MB map and Nothing

**Comment by BexiPE** [comment]
https://www.planetminecraft.com/project/climate-hope-city/
This is one of map.

**Comment by armagadon159753** [comment]
Inconfirmed 
No crash for me
![screenshot_2017-07-21-18-13-04](https://user-images.githubusercontent.com/25569806/28472314-64ccb68a-6e40-11e7-892e-195f1ea0c236.png)

**Comment by BexiPE** [comment]
I just tested it but the Server Crashes...

**Comment by erkam2002** [comment]
Use new src bexiii haha

**Comment by DerddyDert** [comment]
He did receive an error. We need to focus on why.

Error: Undefined class constant 'DAY_LIGHT_DETECTOR'
File: /src/pocketmine/tile/DLDetector
Line: 139
Type: notice

@BexiPE We need to know exactly which src you used. If you cannot provide that then download the current src.

**Comment by BexiPE** [comment]
It now work whit the new version ;D

**Comment by erkam2002** [comment]
-.-
