### ISSUE TITLE
Many World BUGS.

### ISSUE THREAD

**Issue by BexiPE** [GenisysPro/GenisysPro#608]
**Bugs**
• Some blocks are Black (wtf?)
• Some Wooden_Planks are Dispensers (id bug...)
• Some slabs are rails (id????)
• Blocks Invisible (Skulls Blocks Chests....)

**Version:**
• PHP version: 7.0.3
• Zend version: 3.0.0
• OS : Linux, linux

**Comment by erkam2002** [comment]
Was leberst du hast überhaupt gelernt alda xD

**Comment by BexiPE** [comment]
@erkam2002 Was soll ich gelernt haben? Wenn die software buggt wie scheisse

**Comment by MasterOfTheRealm** [comment]
PC to PE Block Id differences are not our responsibility. You should use MCEdit or a plugin to change them to the proper block for PE. As for rest we'll look into it. And next time please don't leave out the fact that you used a PC map because that is confusing when we check into it.
