### ISSUE TITLE
Server freezes at times for a few seconds

### ISSUE THREAD

**Issue by omgA4L** [GenisysPro/GenisysPro#610]
#### Issue description
Server freezes randomly for a few seconds and comes back.
Timings showed this:
       Pct Total      Pct Tick    Total             Avg         PerTick    Count             Events
       3.09%	  26.50%	  1.23 s	    13.25 ms	 0.1	       0.1k	    Player Send Chunks

After a few more minutes the Pct Tick reaches over %90

#### Platform information
* GenisysPro version: 45acd9c

* PHP binary version: 7.0.1

* Server OS: Ubuntu

* Game client :MCPE 1.1.4 on win10/ios

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by DerddyDert** [comment]
List your plugins

**Comment by omgA4L** [comment]
AlwaysSpawn,AntiSpam,Broadcaster,CombatLogger,CommandBlocked,DevTools,EconomyAPI,EconomySell,
EconomyShop,Iprotector, LeetBorder,LifeFly,ManyWorlds,MysteryCrates,VoteRewards,PureChat,PurePerms,RestartME,SimpleAuth,
SimpleAuthHelper,StatsPE

**Comment by omgA4L** [comment]
oh and slapper

**Comment by omgA4L** [comment]
the map is also using MC Anvil

**Comment by MasterOfTheRealm** [comment]
how many players are online when this happens?

**Comment by SuperKali** [comment]
@omgA4L your vps is? openvz and kvm?

**Comment by TDMidkwhatisxd** [comment]
I bet he have 1 processor. I run server with 75 players, mostly 50-70 online, and I can run no lag on a cheap vps.
My specs, x4 cores at 1.4ghz and 4gb ram 
+ I run 1 MCPc server on it beside pocketmine.

**Comment by SuperKali** [comment]
Your server is low for performance then lag

**Comment by omgA4L** [comment]
I'm using a dedicated server,
Processor: E3-1230v2 3.30Ghz
32gb ram
4 cores
-

**Comment by omgA4L** [comment]
this occurred when there's 2+ people on the server (This server isn't released, still in test mode)

**Comment by DerddyDert** [comment]
@omgA4L your CPU has 2 threads per core, 8 total siblings. Go in discord and we will help you configure your setup.

**Comment by omgA4L** [comment]
Alright I'm there

**Comment by xZeroMCPE** [comment]
@SuperKali  -  Shut up already, You don't know what the fuck is going on, your response is retarded.

As of for @DerddyDert 

A simple configuration to files will not help..... GenisysPro is just shitty and needs a LOT of work... 

Lastly,

Don't incorrect reply and making the OP think the problem is related to he/she dedicated server (or: vps).

**Comment by DerddyDert** [comment]
Just ignore @xZeroMCPE  he is just a kid and doesn't understand all this stuff. Anyways I have a huge server with 10+ worlds and it works just fine. We will get you squared away on discord.
