### ISSUE TITLE
Add a update.sh

### ISSUE THREAD

**Issue by xRazvan9** [GenisysPro/GenisysPro#614]
#### Issue description

Auto-update GenisysPro src/phar
#### Platform information

* GenisysPro version:

* PHP binary version:

* Server OS:

* Game client:

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by Leo3418** [comment]
This can be achieved by users themselves. Even if you have **auto**-update script, you still need to create a `crontab` task to let it run automatically.
