### ISSUE TITLE
MCPE 1.1 is already out

### ISSUE THREAD

**Issue by DerddyDert** [GenisysPro/GenisysPro#62]
@SuperXingKong 
#### Issue description
Since MCPE 1.1 is **already released**, please test and merge the _mcpe-1.1_ branch with the _master_ branch. Thanks 

#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by SuperXingKong** [comment]
Ok, just a moment.

**Comment by DerddyDert** [comment]
Man, you are so busy working hard today. Good job buddy. @SuperXingKong

**Comment by SuperXingKong** [comment]
Thanks. 😉

**Comment by SuperXingKong** [comment]
Finished, wait for testing. xD
