### ISSUE TITLE
[Server thread/CRITICAL]: Could not tick level "Lobby": Call to undefined method pocketmine\Player::asVector3()

### ISSUE THREAD

**Issue by erkam2002** [GenisysPro/GenisysPro#620]

**Comment by erkam2002** [comment]
Newest

**Comment by erkam2002** [comment]
https://github.com/GenisysPro/GenisysPro/commit/37441009bce0f4a5989b6e33d2b99e1f996db005#diff-e7946cb9b02a4dba1a3d5e627e31b2ccR1725

**Comment by DerddyDert** [comment]
Ah I see. @SuperXingKong  check your recent commit please.

**Comment by MasterOfTheRealm** [comment]
Removed That Part Of The Code, @SuperXingKong will have to do something about that
