### ISSUE TITLE
Chunks not loading properly

### ISSUE THREAD

**Issue by Antique233** [GenisysPro/GenisysPro#623]
![screenshot_2017-07-22-23-18-24](https://user-images.githubusercontent.com/21009992/28526056-efe00e86-704b-11e7-8285-e92c51379489.png)

#### Platform information

* GenisysPro version:#169

* PHP binary version:php7

* Server OS:Ubuntu Server

* Game client:MC:PE v1.1.3

chunks always not update when i teleport from a world to another world(i think their position are equally)
i can place a block or break a block near these chunk to update it
fix it please!
#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by SuperXingKong** [comment]
@DerddyDert  @MasterOfTheRealm Can you revert https://github.com/GenisysPro/GenisysPro/commit/37441009bce0f4a5989b6e33d2b99e1f996db005? It needs more test.

**Comment by MasterOfTheRealm** [comment]
will do @SuperXingKong

**Comment by Leo3418** [comment]
请上传您的 `pocketmine.yml` 文件。Please upload your `pocketmine.yml`.

**Comment by Antique233** [comment]
@Leo3418 
Many GenisysPro users in China also tell me they have this problem too

> # Main configuration file for PocketMine-MP
# These settings are the ones that cannot be included in server.properties
# Some of these settings are safe, others can break your server if modified incorrectly
# New settings/defaults won't appear automatically on this file when upgrading.

settings:
 #Three-letter language code for server-side localization
 #Check your language code on https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes
 language: "eng"
 #Whether to send all strings translated to server locale or let the device handle them
 force-language: false
 #When server shut down, the players will get kicked and this is what will show on there screen.
 shutdown-message: "§e服务器已关闭/重启"
 #Allow listing plugins via Query
 query-plugins: true
 #Show a console message when a plugin uses deprecated API methods
 deprecated-verbose: true
 #Enable plugin and core profiling by default
 enable-profiling: false
 #Will only add results when tick measurement is below or equal to given value (default 20)
 profile-report-trigger: 20
 #Number of AsyncTask workers.
 #Used for plugin asynchronous tasks, world generation, compression and web communication.
 #Set this approximately to your number of cores.
 #If set to auto, it'll try to detect the number of cores (or use 2)
 async-workers: auto
 #Enables use of non-production, development builds. WARNING: DO NOT enable this unless you are sure you know what you are doing.
 enable-testing: false

memory:
 #Global soft memory limit in megabytes. Set to 0 to disable
 #This will trigger low-memory-triggers and fire an event to free memory when the usage goes over this
 global-limit: 0

 #Main thread soft memory limit in megabytes. Set to 0 to disable
 #This will trigger low-memory-triggers and fire an event to free memory when the usage goes over this
 main-limit: 0

 #Main thread hard memory limit in megabytes. Set to 0 to disable
 #This will stop the server when the limit is surpassed
 main-hard-limit: 2048

 #Period in ticks to check memory (default 1 second)
 check-rate: 20

 #Continue firing low-memory-triggers and event while on low memory
 continuous-trigger: true

 #Only if memory.continuous-trigger is enabled. Specifies the rate in memory.check-rate steps (default 30 seconds)
 continuous-trigger-rate: 30

 garbage-collection:
  #Period in ticks to fire the garbage collector manually (default 30 minutes), set to 0 to disable
  #This only affect the main thread. Other threads should fire their own collections
  period: 36000

  #Fire asynchronous tasks to collect garbage from workers
  collect-async-worker: true

  #Trigger on low memory
  low-memory-trigger: true

 max-chunks:
  #Maximum render distance per player when low memory is triggered
  chunk-radius: 9

  #Do chunk garbage collection on trigger
  trigger-chunk-collect: false

  #Trigger on low memory
  low-memory-trigger: true

 world-caches:
  disable-chunk-cache: false
  low-memory-trigger: true


network:
 #Threshold for batching packets, in bytes. Only these packets will be compressed
 #Set to 0 to compress everything, -1 to disable.
 batch-threshold: 256
 #Compression level used when sending batched packets. Higher = Uses More CPU, Less = More Bandwidth Usage
 compression-level: 2
 #Use AsyncTasks for compression. Adds half/one tick delay, less CPU load on main thread
 async-compression: true
 #Experimental, only for Windows. Tries to use UPnP to automatically port forward
 upnp-forwarding: false

debug:
 #To enable assertion execution, set zend.assertions in your php.ini to 1
 assertions:
  #Warn if assertions are enabled in php.ini, due to assertions may impact on runtime performance if enabled.
  warn-if-enabled: true
  #Enable throwing exceptions when assertions fail, will allow obtaining more detailed information on the failed assertion, but may cause a server crash.
  #If set to false, a warning will be raised instead of throwing an exception.
  throw-exception: false
 #If > 1, it will show debug messages in the console
 level: 1
 #Enables /status, /gc
 commands: true

player:
 #Choose whether to enable player data saving.
 save-player-data: true
 anti-cheat:
  #If false, will try to prevent speed and noclip cheats. May cause movement issues with some blocks which are not yet properly implemented.
  allow-movement-cheats: false
  #If false, times block breaks to ensure players are not cheating. May cause issues with some blocks which are not yet properly implemented.
  allow-instabreak: false

level-settings:
 #The default format that levels will use when created
 default-format: pmanvil
 #Automatically change levels tick rate to maintain 20 ticks per second
 auto-tick-rate: false
 auto-tick-rate-limit: 20
 #Sets the base tick rate (1 = 20 ticks per second, 2 = 10 ticks per second, etc.)
 base-tick-rate: 1
 #Tick all players each tick even when other settings disallow this.
 always-tick-players: false

chunk-sending:
 #To change server normal render distance, change view-distance in server.properties.
 #Amount of chunks sent to players per tick
 per-tick: 1
 #Radius of chunks that need to be sent before spawning the player
 spawn-radius: 4
 #Save a serialized copy of the chunk in memory for faster sending
 #Useful in mostly-static worlds where lots of players join at the same time
 cache-chunks: true
 #Use AsyncTasks for serializing chunks for sending.
 async-chunk-request: false

chunk-ticking:
 #Max amount of chunks processed each tick
 per-tick: 32
 #Radius of chunks around a player to tick
 tick-radius: 6
 light-updates: false
 clear-tick-list: true
 #IDs of blocks not to perform random ticking on.
 disable-block-ticking:
  #- 2 # grass

chunk-generation:
 #Max. amount of chunks in the waiting queue to be generated
 queue-size: 2
 #Max. amount of chunks in the waiting queue to be populated
 population-queue-size: 8

ticks-per:
 animal-spawns: 400
 monster-spawns: 1
 autosave: 6000
 cache-cleanup: 900
spawn-limits:
  monsters: 70
  animals: 15
  water-animals: 5
  ambient: 15

auto-report:
 #Send crash reports for processing
 enabled: false
 send-code: true
 send-settings: true
 send-phpinfo: false
 host: crash.pocketmine.net

anonymous-statistics:
 #Sends anonymous statistics for data aggregation, plugin usage tracking
 enabled: true
 host: stats.pocketmine.net

commands:
 #Here you can customize server commands
 #Specify command names to override the default set here.
 #If no custom value is defined for a command, the default will be used.
 #NOTE: Some commands cannot be disabled here, such as the important ones like /stop, /reload, etc.
 default: true
 #Set override values per command here
 #For example, uncommenting the below will disable /plugins and /version
 #version: false
 #plugins: false

timings:
 #Choose the host to use for viewing your timings results.
 host: timings.pmmp.io

aliases:
 #Examples:
 #showtheversion: version
 #savestop: [save-all, stop]

worlds:
 #These settings will override the generator set in server.properties and allows loading multiple levels
 #Example:
 #world:
 # seed: 404
 # generator: FLAT:2;7,59x1,3x3,2;1;decoration(treecount=80 grasscount=45)

**Comment by Antique233** [comment]
And some chunks can't update it when you edit a block
if player in it he will hyperspasmia :(

**Comment by AppleDevelops** [comment]
It’s a client side bug 🤦‍♂️

**Comment by Antique233** [comment]
so...we can't fix it!?

**Comment by xISRAPILx** [comment]
load chunk in chunk loadevent

**Comment by KenMizz** [comment]
same problem here

**Comment by Antique233** [comment]
@xISRAPILx how to load chunk in chunkloadevent?we don't know how to do this😂

**Comment by Antique233** [comment]
Provide the codes to us,thanks for your help!

**Comment by xISRAPILx** [comment]
Soon... @Antique233

**Comment by BexiPE** [comment]
@AppleDevelops Wow, at Nukkit it works, not a Client bug...

**Comment by BexiPE** [comment]
When is the Bug fixed D:?

**Comment by Antique233** [comment]
chunk bug also make players in the void,you can move or see any blocks

**Comment by AppleDevelops** [comment]
@BexiPE are you stupid? They use a hack to prevent that from happening

**Comment by BexiPE** [comment]
@AppleDevelops Ehm to your Question I'm dont stupid, and I dont know that they use a Hack wtf... chill please your base xd

**Comment by SuperXingKong** [comment]
I am thinking whether merge Genpro-1.2dev branch. It may fix this issue. @DerddyDert

**Comment by DerddyDert** [comment]
@SuperXingKong why not? As long as there are no conflict and it's stable.

**Comment by BexiPE** [comment]
I think the bug never fixed lol D:

**Comment by erkam2002** [comment]
Wurde doch schon gefixt ist im test !

**Comment by Antique233** [comment]
how's it going now

**Comment by Antique233** [comment]
how's it going now

**Comment by Antique233** [comment]
lol i make a patch to fix it
