### ISSUE TITLE
Ender generation

### ISSUE THREAD

**Issue by DerddyDert** [GenisysPro/GenisysPro#629]
Ender generation looks great but it appears to cuttoff after the main area is generated. 

![screenshot_20170725-190215](https://user-images.githubusercontent.com/18636275/28598239-4b9c393c-7170-11e7-98bf-0369de73cd62.jpg)
![screenshot_20170725-190420](https://user-images.githubusercontent.com/18636275/28599243-e82ba52a-7176-11e7-9522-e4d0a41efaee.jpg)

**Comment by DerddyDert** [comment]
Well I flew far away and a lot more generated finally. Could have been the seed. How far are they supposed to spawn from each other?

**Comment by BajanVlogs** [comment]
it doesnt spawn for me just keeps saying building

**Comment by DerddyDert** [comment]
Umm. Did you rebuild your Genisys.yml?

**Comment by MasterOfTheRealm** [comment]
@BajanVlogs let it generate and close your client and relog back on then it will work for you

**Comment by DerddyDert** [comment]
@MasterOfTheRealm it generated fine in the test. Something messed up for Bajan with his setup but he will get to the bottom of it.

**Comment by MasterOfTheRealm** [comment]
@DerddyDert it's just a minor problem when it is generated on a device such as a mobile phone

**Comment by SuperXingKong** [comment]
How about the Normal generator?

**Comment by DerddyDert** [comment]
Umm it was ok. But we have been using ender generation on test.Genisys.pro 19132 way fun. Thanks to @Frago9876543210

**Comment by SuperXingKong** [comment]
Why not put the test server on our Github page or wiki? More players, more fun.

**Comment by DerddyDert** [comment]
@SuperXingKong  can you fix gitlab? I don't know what's wrong...

**Comment by SuperXingKong** [comment]
@DerddyDert Ok, I have given you MASTER permission. You can edit it or create a pipeline.

**Comment by Frago9876543210** [comment]
@DerddyDert read discord
