### ISSUE TITLE
Anti-Speed

### ISSUE THREAD

**Issue by GDRGamingzz** [GenisysPro/GenisysPro#630]
Hello fellow Developers, can I ask why I can't remove the anti-cheat system for speed cause it always making the players glitch out abit when running or sprinting on the staircase

**Comment by MasterOfTheRealm** [comment]
allow movement cheats on pocketmine.yml

**Comment by GDRGamingzz** [comment]
on what section?

**Comment by MasterOfTheRealm** [comment]
player:
 #Choose whether to enable player data saving.
 save-player-data: true
 anti-cheat:
  #If false, will try to prevent speed and noclip cheats. May cause movement issues with some blocks which are not yet properly implemented.
  allow-movement-cheats: true
  #If false, times block breaks to ensure players are not cheating. May cause issues with some blocks which are not yet properly implemented.
  allow-instabreak: true


Set allow-movement-cheats to true

**Comment by DerddyDert** [comment]
@GDRGamingzz  that should be default in latest src. I recommend latest src due to fine tuning and ender world

**Comment by DerddyDert** [comment]
@MasterOfTheRealm  we are so fast to respond haha

**Comment by MasterOfTheRealm** [comment]
@DerddyDert Discord Webhooks <3

**Comment by GDRGamingzz** [comment]
ok worked thanks xD
