### ISSUE TITLE
Warning when entering the nether/ender.

### ISSUE THREAD

**Issue by SuperAdam47** [GenisysPro/GenisysPro#631]
GenisysPro: lastest version

![screenshot_20170726-120954](https://user-images.githubusercontent.com/16169771/28613720-de3be220-71fb-11e7-8606-a0c38fd9f82e.png)

**Comment by MasterOfTheRealm** [comment]
@SuperAdam47 is this when you try entering the nether?

**Comment by SuperAdam47** [comment]
I am entered to ender world

**Comment by DerddyDert** [comment]
@Frago9876543210

**Comment by DerddyDert** [comment]
When I spawned in end world it threw me in void. I had to fly to land...

**Comment by SuperAdam47** [comment]
Why

**Comment by MasterOfTheRealm** [comment]
You shouldn't get the error anymore with the latest src

**Comment by MasterOfTheRealm** [comment]
yeah that too
