### ISSUE TITLE
Chest Bug?

### ISSUE THREAD

**Issue by ldliuzhen** [GenisysPro/GenisysPro#632]
#### Issue description

When player comeback The Large Chest prehaps become two small chest ....And the small chest is empty...

 ##
#### Platform information

* GenisysPro version:1.1

* PHP binary version:7

* Server OS:windows

* Game client:1.1.3

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by MasterOfTheRealm** [comment]
what are the plugins you are using?

**Comment by ldliuzhen** [comment]
ChestLocker v1.2, Oblockshop v2.0.5, EconomyAPI v2.0.9, EssentialsPE v2.0.0, Killme v1.0.0, lovt v1.0.0, MYServer v2.7.0, PureEntitiesX v0.2.2_dev, Status v2.0, WorldProtect v2.3.5-dev1, world_bancommand v1.0.0, XBanCheating v4.2.0, ZXDAKernel v5.1.3.0, island v2.2.9, TCEvents v1.2.8, TeleportPortal v2.6.0, Toxotes v1.6.0, TWorld v1.2.5, EasyMessages v1.0.0, Block_land v1.1.0, Survival_Relics v1.4.0

**Comment by ldliuzhen** [comment]
this problem is today appear

**Comment by MasterOfTheRealm** [comment]
Chestlocker might be causing these issues...or any plugin that uses chests...if this is a software issue I'm pretty sure we'll get more reports of something as common as chests malfunctioning.

**Comment by ldliuzhen** [comment]
Doesn't have this problem in three days ago genisyspro .......

**Comment by erkam2002** [comment]
Try it out without plugins

**Comment by ldliuzhen** [comment]
Ok
