### ISSUE TITLE
Player Join Glitch

### ISSUE THREAD

**Issue by GDRGamingzz** [GenisysPro/GenisysPro#635]
Hello fellow Developers,

I think there is a problem were your not in the default world and you quit then after server restart then you join you can only see the void.

**Comment by MasterOfTheRealm** [comment]
Were you in The Nether or The End by any chance?

**Comment by GDRGamingzz** [comment]
no sir, I'm on a different world. but not nether nor end

**Comment by MasterOfTheRealm** [comment]
And you use AlwaysSpawn or MSpawns to force the players onto the default world right?

**Comment by GDRGamingzz** [comment]
yep

**Comment by xISRAPILx** [comment]
It's a chunk bug. @MasterOfTheRealm

**Comment by DerddyDert** [comment]
@xISRAPILx are you able to isolate the problem?
