### ISSUE TITLE
Block Break animation & Elytra malfunction

### ISSUE THREAD

**Issue by GDRGamingzz** [GenisysPro/GenisysPro#637]
Hello fellow Developers, 
ill list the bugs that I have observed. in the past days.

**Issue Description**

- First is the Block break animation. there is no block break animation when you try to break any block.

- Second is the Elytra Malfunction. When you try to glide using an elytra it instantly falls you off for some reason

if you guys know how to fix it that would help a lot!

**OS and versions**
Genisyspro: 1.1
PHP: 7.0.3
Server OS: Ubuntu
Game version: 1.1.4
Crashdump, backtrace, memory dumps, plugins list or other files

**Comment by GDRGamingzz** [comment]
also increase the time when the title appear like 2,3-5 seconds.

**Comment by xISRAPILx** [comment]
assigne me @DerddyDert

**Comment by DerddyDert** [comment]
@xISRAPILx u are assigned

**Comment by xISRAPILx** [comment]
Thank's @DerddyDert @Leo3418 @shoghicp

**Comment by DerddyDert** [comment]
It's thus fixed yet?

**Comment by Leo3418** [comment]
The second problem has been fixed in #639.

**Comment by DerddyDert** [comment]
Issues like this need to be in separate issue reports.

**Comment by SuperXingKong** [comment]
@DerddyDert I will add it
