### ISSUE TITLE
A Memory Question 

### ISSUE THREAD

**Issue by ldliuzhen** [GenisysPro/GenisysPro#638]
#### Issue description

The genisyspro status show the server use 350M ,But the Task Manager show php.exe use 770M ..why?

#### Platform information

* GenisysPro version:1.1

* PHP binary version:7

* Server OS:windows

* Game client:1.1.3

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by Leo3418** [comment]
GitHub Issues is not a place for such question. Please feel free to ask your question in the Discord group or on our forum. Thank you.

**Comment by ldliuzhen** [comment]
OK,sorry
