### ISSUE TITLE
Nether portal stucks on building terrain screen

### ISSUE THREAD

**Issue by poustmal** [GenisysPro/GenisysPro#640]
Nether portal stucks on building terrain screen again and with the latest update:commit 6a35444
![screenshot_2017-07-27-22-23-35](https://user-images.githubusercontent.com/22281205/28688442-a72fba16-731a-11e7-8d8a-01f637dba899.png)

**Comment by DerddyDert** [comment]
@Frago9876543210 can you look into this please?

**Comment by erkam2002** [comment]
lol faillll

**Comment by xISRAPILx** [comment]
error in console exists?

**Comment by CortexPE** [comment]
HOW TO FIX: Send a PlayStatusPacket after the player gets Teleported.

**Comment by DerddyDert** [comment]
@MasterOfTheRealm if you get a chance, re-look into the code u added for nether/ender player spawning after you read the comment from cortex above. Thanks!

**Comment by DerddyDert** [comment]
Thanks @CortexPE

**Comment by MasterOfTheRealm** [comment]
@DerddyDert this issue confuses me because i'm unable to reproduce it

**Comment by DerddyDert** [comment]
Maybe he didn't get the src with your update. @poustmal use the latest phar and test again please. https://genisyspro.github.io/GenisysPro/GenisysPro.phar

**Comment by poustmal** [comment]
I downloaded the latest phar from the link,and I stuck on building terrain screen again,I need to join again to go on nether

**Comment by MasterOfTheRealm** [comment]
Ok i was able to replicate it somewhat... i have no problem when using my tab but this happens to me when i used my phone.

**Comment by Frago9876543210** [comment]
Need add
`
$pk1 = new PlayStatusPacket();
$pk1->status = PlayStatusPacket::PLAYER_SPAWN;
$this->dataPacket($pk1);
`
to `switchLevel` in `Player.php`
