### ISSUE TITLE
Chunks not Loading....

### ISSUE THREAD

**Issue by BexiPE** [GenisysPro/GenisysPro#641]
**Bug:**
When I teleporting to a world the Chunks not loading....

**Comment by Leo3418** [comment]
Duplicate of #623 
Before you submit any issue, please have a look at all other existing issue, and make sure this issue does not duplicate any other issue. Thank you!

**Comment by BexiPE** [comment]
wow, but it isnt fix...

**Comment by Leo3418** [comment]
We're aware of this issue. If you want to report more information about this issue, please post it in #623. Please do not open another issue reporting the same problem.
