### ISSUE TITLE
Problems with spawn players

### ISSUE THREAD

**Issue by MrSN-AG** [GenisysPro/GenisysPro#642]
Hello, I have a problem with spawn players after join. Some players after the entrance are under the map, and some do not

Info:

* PHP binary version: 7.0.6

* Server OS: Ubuntu Server 16.04 (64 bit)

* Game client: MC:Win10 v1.1.0, MC:PE v.1.1.4 on iOS

**Comment by SuperKali** [comment]
@MrSN-AG I also find the same problem

**Comment by DerddyDert** [comment]
I had the exact same problem. Use this mspawns and don't use alwayspawn. https://github.com/GenisysPro/MSpawns

**Comment by SuperKali** [comment]
@DerddyDert When a player dies, he remains caught in the hub
![screenshot_20170729-010432](https://user-images.githubusercontent.com/19473898/28739302-2d49924a-73fa-11e7-98d2-e3d7a527d52f.jpg)
I not have always spawn
