### ISSUE TITLE
Chunk Bug......

### ISSUE THREAD

**Issue by BexiPE** [GenisysPro/GenisysPro#643]
The Chunks not Loading..... wtf?, with nukkit it works......
Fix it...... lol..... GenisysPro...... Version.... i dont know but fix it plsss,,....

**Comment by Leo3418** [comment]
Please do not send these duplicate and helpless issues. If you want to assist us in solving this problem, please try to provide more helpful information in #623. We are attempting to fix this problem, so we have labeled #623 as "Priority". If you continue to send such issues, you might be **blocked** from GenisysPro organization on GitHub. You have been warned!
