### ISSUE TITLE
Some useful functions needed

### ISSUE THREAD

**Issue by TheAz928** [GenisysPro/GenisysPro#647]
I've noticed that in Inventory Transaction, there's no such function as "getSourceItem", It is very useful and needs to be added. PocketMine-MP has it. Many of you may say "It's not pmmp", so what? it's not pmmp but it can't have the feature? Although it's a fork of pmmp. Thanks..

**Comment by erkam2002** [comment]
Its a fork of Genisys!!

**Comment by TheAz928** [comment]
and Genisys is a fork of itself?

**Comment by erkam2002** [comment]
PMMP is a fork of PocketMine !

**Comment by erkam2002** [comment]
The main code is from shogi

**Comment by akaSnapy** [comment]
its getTargetItem

**Comment by akaSnapy** [comment]
@erkam2002 NO ITS NOT, when shogi leaved the project for mojang he didnt wanted to give the organization so he gave him permissions to continue it

**Comment by TheAz928** [comment]
@akaSnapy @erkam2002 Kindly don't reply when you don't know correct info...

**Comment by DerddyDert** [comment]
Genisyspro is a spoon of Genisys and Genisys is a spoon of pocketmine. PMMP is a spoon of Pocketmine. However, none of this has to do with what @TheAz928  pointed out which is a valid point. We will be moving more toward comparability as well as continuing to provide extended functionality. Feel free to make a PR to accomplish this.

**Comment by lightda104530** [comment]
pmmp and pocketmine not the same
GenisysPro and Genisys not the same too

**Comment by DerddyDert** [comment]
@TheAz928 feel free to make a PR for this or talk to some of the devs.

**Comment by DerddyDert** [comment]
@TheAz928 Im going to go ahead and close this as you can make a PR with the needed changes or discuss this on discord with the other devs. Trying to clean up here.
