### ISSUE TITLE
Splash Potions. Diffrent potions when thrown

### ISSUE THREAD

**Issue by optimusprime338** [GenisysPro/GenisysPro#648]
#### Issue description
 I am getting another spalsh potion effect when thrown  then the acutlly it is . for example . when I am throwing splash potion of instant health. I am getting effect of instant damage!
#### Platform information

* Git commit: d5465c2

* PHP binary version: 7.0.3

* Server OS: ubuntu 128*64 16.04

* Game client: Tired on win10 and MCPE . Happening on both

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by Leo3418** [comment]
Do you get this problem with any other type of potion, or only with Instant Health potion?

**Comment by Leo3418** [comment]
I've seen your screenshots in the Discord group and tried to reproduce this issue. Player **can** get Instant Health effect when they are hit by Slash Instant Health Potion, only the potion displayed is incorrect: it displays as Splash Water Bottle. Can you confirm this?

**Comment by optimusprime338** [comment]
No they get harm too

**Comment by Leo3418** [comment]
Sorry, I still can't reproduce this issue. Please download the latest version and try again, or upload a video demonstrating this bug.

**Comment by Leo3418** [comment]
Unconfirmed issues would be closed if the opener cannot provide more information.
