### ISSUE TITLE
Not able to logon with MCPE 1.1.x

### ISSUE THREAD

**Issue by DerddyDert** [GenisysPro/GenisysPro#65]
#### Issue description

Cannot login to server. Client jsut says syncing while console shows:
`Warning: zlib_decode(): data error in /home/TEST/src/pocketmine/network/protocol/LoginPacket.php on line 63

Warning: unpack(): Type V: not enough input, need 4, have 0 in /home/TEST/src/pocketmine/utils/Binary.php on line 232

Notice: Trying to get property of non-object in /home/TEST/src/pocketmine/network/protocol/LoginPacket.php on line 69

Warning: unpack(): Type V: not enough input, need 4, have 0 in /home/TEST/src/pocketmine/utils/Binary.php on line 232

Notice: Undefined offset: 1 in /home/TEST/src/pocketmine/network/protocol/LoginPacket.php on line 131

Notice: Undefined offset: 2 in /home/TEST/src/pocketmine/network/protocol/LoginPacket.php on line 131
[04:10:33] [Server thread/INFO]: [/IPADDRESSshh:56952] logged out due to timeout
`

#### OS and versions

* Genisys:
* PHP:
* Server OS:
* Game version: 

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by DerddyDert** [comment]
You labeled it "won'tfix" !? Hahaha

**Comment by SuperXingKong** [comment]
Forgive me lol

**Comment by DerddyDert** [comment]
I laughed and cried so hard. Lol  :-p

**Comment by SuperXingKong** [comment]
Can you test it again? Or I will label it "won't fix"😂

**Comment by DerddyDert** [comment]
I will test it as soon as it uploads. standby a couple minutes please.

**Comment by DerddyDert** [comment]
Umm please meet me on discord now

**Comment by DerddyDert** [comment]
Anyway, this problem is resolved.
