### ISSUE TITLE
Chest Disappear!

### ISSUE THREAD

**Issue by ldliuzhen** [GenisysPro/GenisysPro#650]
#### Issue description

The Chest disappear!!(Just like the bed problem.....)......This problem is Probability trigger.......and the invisible chest is nothing!!
the piicture in Discrod !

@SuperXingKong Know that

#### Platform information

* Git commit:

* PHP binary version:7

* Server OS:windows

* Game client:1.1.4

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by ldliuzhen** [comment]
Even me diden't use chestlock plugins..The problem still exist

**Comment by Norman300** [comment]
me too!!

**Comment by MasterOfTheRealm** [comment]
Chests disappear? please list all the plugins you use here @ldliuzhen and @Norman300

**Comment by junkdude** [comment]
i dont have this issue at all

**Comment by SuperXingKong** [comment]
I found it. Revert Apple's pull request...

**Comment by SuperXingKong** [comment]
@MasterOfTheRealm @DerddyDert There must be something broke Chest Tile

**Comment by DerddyDert** [comment]
Yeah I saw a chest disappear as well..

**Comment by MasterOfTheRealm** [comment]
@SuperXingKong @DerddyDert  let's check all the chest related code and try find it out

**Comment by DerddyDert** [comment]
I think its related to chunk issues

**Comment by SuperXingKong** [comment]
@DerddyDert Try to revert https://github.com/GenisysPro/GenisysPro/commit/acd065f99bb55549f56b43d2848f0198c125b230

**Comment by Leo3418** [comment]
@SuperXingKong that commit contains changes to several files. Which file(s) should be reverted?

**Comment by DerddyDert** [comment]
I can no longer recreate this issue.

**Comment by Leo3418** [comment]
@DerddyDert 
@SuperXingKong told me this issue may be caused by 196de12, f76b29f, f94bae7 and c32e66d. Could you investigate them and decide if we should revert them? Thanks

**Comment by MasterOfTheRealm** [comment]
196de12 is in the clear

**Comment by DerddyDert** [comment]
I tested latest src no issue

**Comment by Leo3418** [comment]
Today some player in my server complained about disappeared chests. This issue is still unresolved.
