### ISSUE TITLE
How to add simplexml extension GenisysPro php files?

### ISSUE THREAD

**Issue by andris155** [GenisysPro/GenisysPro#654]
The MineMarketPE plugin use $xml = simplexml_load_file($url); method, and not work GenisysPro php files.
How to add simplexml extension GenisysPro php files?

`29.05 00:00:12 [Server] Server thread/CRITICAL Could not execute task MineMarket\ScheduleTask: Call to undefined function MineMarket\simplexml_load_file()`

**Comment by SuperXingKong** [comment]
You need to COMPILE PHP again.
