### ISSUE TITLE
Zlib decode error in Network

### ISSUE THREAD

**Issue by Bombaasa** [GenisysPro/GenisysPro#658]
What it is?

Warning: zlib_decode(): data error in phar:///.../PocketMine-MP.phar/src/pocketmine/network/Network.php on line 274

Output more than 5-7 times in 3 minutes, when players are on server.

GenisysPro version https://github.com/GenisysPro/GenisysPro/commit/13ac3b3b70a60a1b1ae5c0c1ccef9dbc46a6c966

**Comment by DerddyDert** [comment]
@NycuRO made a fix for this but we didn't merge it.

**Comment by Leo3418** [comment]
Next time please provide the Git commit SHA of the GenisysPro version you're using. It would only consume little energy of yours.

**Comment by Leo3418** [comment]
Because this is an unconfirmed issue, and the opener cannot provide more information, this issue is being closed.
