### ISSUE TITLE
shutdown() in Server Erro

### ISSUE THREAD

**Issue by ibookcc** [GenisysPro/GenisysPro#661]
## 问题描述
将start.sh文件中自动重启的no改成yes
放入Liunx环境然后进行以下操作
当你使用Server里的函数shutdown产生重启服务器服务器
`Server::getInstance()->getPluginManager()->getPlugin("SWorld")->LoadAllLevels();`
就会出现
`Warning: require_once(phar:///root/20002/PocketMine-MP.phar/src/pocketmine/PocketMine.php): failed to open stream: phar error: internal corruption of phar "/root/20002/PocketMine-MP.phar" (actual filesize mismatch on file "src/pocketmine/PocketMine.php") in /root/20002/PocketMine-MP.phar on line 1

Fatal error: require_once(): Failed opening required 'phar:///root/20002/PocketMine-MP.phar/src/pocketmine/PocketMine.php' (include_path='.:') in /root/20002/PocketMine-MP.phar on line 1
To escape the loop, press CTRL+C now. Otherwise, wait 5 seconds for the server to restart.`
多个版本都出现了这个问题

**Comment by erkam2002** [comment]
English pls

**Comment by DerddyDert** [comment]
is the file readable and executable?? @ibookcc

**Comment by Leo3418** [comment]
如需使用循环，请使用命令`./start.sh -l`。请勿直接修改`start.sh`。

**Comment by ibookcc** [comment]
@DerddyDert Of course, I command stop in console, anything is right. but use shutdow, the server will be like it again and again.(is something isn't close enough?)

**Comment by ibookcc** [comment]
@Leo3418 Please check out the start.sh file.

**Comment by Leo3418** [comment]
@ibookcc start.sh没有问题，我自己的服务器之前用Linux的时候用-l参数循环，一直都可以运行。今天对start.sh的更改也只是改了识别核心时寻找的文件名。
请把start.sh中的yes改回no，一般不要轻易修改start.sh。
