### ISSUE TITLE
getTile returning null

### ISSUE THREAD

**Issue by VCraftMCPE** [GenisysPro/GenisysPro#667]
#### Issue description
tile is returning null:
var_dump($e->getBlock):
object(pocketmine\block\Chest)#17488 (7) {
  ["id":protected]=>
  int(54)
  ["meta":protected]=>
  int(0)
  ["boundingBox"]=>
  object(pocketmine\math\AxisAlignedBB)#17484 (6) {
    ["minX"]=>
    float(256.0625)
    ["minY"]=>
    int(67)
    ["minZ"]=>
    float(254.0625)
    ["maxX"]=>
    float(256.9375)
    ["maxY"]=>
    float(67.9475)
    ["maxZ"]=>
    float(254.9375)
  }
  ["level"]=>
  object(pocketmine\level\Level)#12250 (0) {
  }
  ["x"]=>
  int(256)
  ["y"]=>
  int(67)
  ["z"]=>
  int(254)
}
var_dump($e->getBlock()->getLevel()->getTile($e->getBlock()))):
NULL 
$e is BlockPlaceEvent

#### Platform information

* Git commit:
[20:53:32] [Server thread/INFO]: -----Server information-----
[20:53:32] [Server thread/INFO]: This server is running GenisysPro-1.1dev307d171 LlamaSpit
[20:53:32] [Server thread/INFO]: PHP version: 7.0.15
[20:53:32] [Server thread/INFO]: API: 3.0.1
[20:53:32] [Server thread/INFO]: Target client: Minecraft PE v1.1.0,v1.1.1,v1.1.2,v1.1.3
[20:53:32] [Server thread/INFO]: Protocol version: 113

* PHP binary version:
 7.0.21

* Server OS:Windows 10

* Game client:.....

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by DerddyDert** [comment]
You did not make it clear which source you used. Please download the latest phar and test again and follow up with the status. Thanks. @VCraftMCPE

**Comment by VCraftMCPE** [comment]
okay i will try

**Comment by VCraftMCPE** [comment]
same error in latest phar
Code:
public function BlockPlaceEvent(BlockPlaceEvent $ev){		
		$item = $ev->getBlock();
		var_dump($item);
		$Chest = $ev->getBlock()->getLevel()->getTile($ev->getBlock());
		var_dump($player);
	}
PS i placed a chest

**Comment by DerddyDert** [comment]
Is this plugin related? You are showing code but not a console error.

**Comment by VCraftMCPE** [comment]
yeah plugin related

**Comment by DerddyDert** [comment]
Which plugin? https://github.com/GenisysProPlugins use this repo.

**Comment by VCraftMCPE** [comment]
@DerddyDert  its my own plugin

**Comment by DerddyDert** [comment]
Ok go in our discord chat for more help.

**Comment by VCraftMCPE** [comment]
@DerddyDert erddyDert in pmmp its not returning null
