### ISSUE TITLE
Clock image bug

### ISSUE THREAD

**Issue by SuperAdam47** [GenisysPro/GenisysPro#669]
This is clock
![mcpemaster-2017-07-31-12-23](https://user-images.githubusercontent.com/16169771/28796930-204a9404-7648-11e7-9b3f-f6bf1cb0dca4.jpg)

#### Platform information

* Git commit:

* PHP binary version:

* Server OS:

* Game client:

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by DerddyDert** [comment]
Also does that for compass.

**Comment by VCraftMCPE** [comment]
@DerddyDert i this a client bug https://bugs.mojang.com/projects/MCPE/issues/MCPE-22977?filter=allopenissues

**Comment by MasterOfTheRealm** [comment]
looks like so

**Comment by SuperAdam47** [comment]
Ok
