### ISSUE TITLE
entity error

### ISSUE THREAD

**Issue by Antique233** [GenisysPro/GenisysPro#671]
#### Platform information

* Git commit:

* PHP binary version:

* Server OS:

* Game client:mcpe v1.1.0

wolf's height in GenisysPro is 1.8,i think it is wrong in Minecraft

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by MasterOfTheRealm** [comment]
Please Elaborate

**Comment by Antique233** [comment]
wolf's height isn't right in the code
it is lower than 1.8
you can edit it to right height,just change a number😂

**Comment by MasterOfTheRealm** [comment]
Yeah we'll be doing an entity rewrite soon correcting everything but first a few bugs need fixing
