### ISSUE TITLE
Server doesn't load chunks from other worlds

### ISSUE THREAD

**Issue by poustmal** [GenisysPro/GenisysPro#674]
When I updated my server to the latest version,server started having problems.

This when I'm trying to teleport to skywars and soupffa:
![screenshot_2017-08-01-12-02-40](https://user-images.githubusercontent.com/22281205/28820630-09e08c8c-76bb-11e7-9c34-a031fb7053bf.png)

![screenshot_2017-08-01-12-41-52](https://user-images.githubusercontent.com/22281205/28820575-d921d66e-76ba-11e7-9b0a-c7a4b5e13101.png)

**Comment by Leo3418** [comment]
Thanks for reporting. To help us resolve this issue, please provide the abbreviated Git commit SHA-1 of the GenisysPro copy you are using.  
You can find this information from two places:
1. The start-up prompt.
<img width="434" alt="Git commit hash in the start-up prompt" src="https://user-images.githubusercontent.com/14175175/28742546-3bfaee04-7465-11e7-9618-f47384d3ddeb.PNG">

2. Output of `/version` command.
<img width="527" alt="Git commit hash in output of `/version` command" src="https://user-images.githubusercontent.com/14175175/28742553-563c541a-7465-11e7-9ac6-8d941fa5b8f3.PNG">

**Comment by poustmal** [comment]
I have the latest commit

**Comment by Leo3418** [comment]
"Latest" is invalid. Please provide the specific commit ID. It won't take you so much time to check it in GenisysPro.

**Comment by poustmal** [comment]
I ll download the latest phar from site( should be  5f87ffe1 commit)but the issue won't be fixed

**Comment by poustmal** [comment]
Ok server now doesn't crash when I'm teleporting or when I'm going to soupffa but skywars still crash the server
