### ISSUE TITLE
Could not tick level "world": Call to a member function getAttribute() on null

### ISSUE THREAD

**Issue by sc00scoc** [GenisysPro/GenisysPro#675]
#### Platform information

* Git commit:

* PHP binary version:

* Server OS:

* Game client:

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by Leo3418** [comment]
Thanks for reporting. Unfortunately, you did not provide sufficient information that could help us pinpoint or solve this issue. Please provide more details to your issue, such as steps to replicate the issue. Otherwise, we may close this issue.

**Comment by MasterOfTheRealm** [comment]
this happened to me too. no backtrace, the console started spamming this error for 2 seconds and stopped. i wasn't able to find the source of this problem

**Comment by sc00scoc** [comment]
I think this problem may be due to the enchants but I'm not sure!

**Comment by Norman300** [comment]
it also happened to my server

**Comment by Norman300** [comment]
it also happened on my server

**Comment by d0048553** [comment]
me too!!

**Comment by poustmal** [comment]
Revert https://github.com/GenisysPro/GenisysPro/pull/655?

**Comment by DerddyDert** [comment]
@poustmal that commit is to big. The issue should be specifically addressed in a new PR @SuperXingKong

**Comment by Leo3418** [comment]
To help us resolve this issue, please provide debug messages shown in the console when this issue happens. In order to show debug messages in the console, you need to modify `debug.level: 1` to any number bigger than 1 in `pocketmine.yml`. For example:
```yaml
debug:
 #If > 1, it will show debug messages in the console
 level: 2
```

**Comment by Leo3418** [comment]
This issue is being closed due to insufficient information.
