### ISSUE TITLE
Slow world loading on new GenisysPro versions

### ISSUE THREAD

**Issue by andris155** [GenisysPro/GenisysPro#680]
#### Issue description

Slow world loading new versions

#### Platform information

* Git commit: https://github.com/GenisysPro/GenisysPro/tree/5f87ffe10c760267b7e123817bbead864792a913

The old version works perfectly world loading: https://github.com/GenisysPro/GenisysPro/tree/fa12ab5e6a88df1d8580f9a6782a441afbd6d6e9

* PHP binary version: 7.0.17 64 bit

* Server OS: Windows 10 1703 (64-bit),

* Game client: v1.1.4 on Windows 10 1703 (64-bit)

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```
none
```

**Comment by DerddyDert** [comment]
Ah, I believe he means generation which is different than loading. Default generation the way it is now has virtually no noticable effect on resources. While its slower than normal2 generation it is still faster than previous normal generation in the past. Now you can have 100s of players generating and not put a burden on your resources.

**Comment by DerddyDert** [comment]
@andris155 If you want the more resource hogging normal2 like before please change it in your level.dat from default to normal2 and let us know.
