### ISSUE TITLE
Pls add Spoon ^^

### ISSUE THREAD

**Issue by oGalatico** [GenisysPro/GenisysPro#683]
#### Platform information

* Git commit:

* PHP binary version:

* Server OS:

* Game client:

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by oGalatico** [comment]
Add spoon :")

**Comment by oGalatico** [comment]
Spoons

**Comment by MasterOfTheRealm** [comment]
Open an issue only when you are serious about something. You already made yourself a joke in front of us with this useless issue that makes no sense at all.
