### ISSUE TITLE
Could not protect Items in the frame

### ISSUE THREAD

**Issue by TeddyPE** [GenisysPro/GenisysPro#688]
**Issue description**
I can't protect Items in the frame.
The protection plugin could not protect it.
Even when I installed spawn-protection, things were broken.

(I'm not good at English. Sorry T_T)

**Platform information**

Git commit: https://github.com/GenisysPro/GenisysPro/commit/332f028dc5e5184da0ee6b2f680185303dcc6cd1

PHP binary version: 7.0.3 64bit Server 

OS: Linux / Ubuntu 17.04 (64-bit)

Game client: v1.1.4 on Windows 10 (64-bit), Minecraft Pocket Edition

**Comment by GODLIKE5** [comment]
Try a different plugin

**Comment by Leo3418** [comment]
Please consider submitting this request at [GenisysProPlugins](https://github.com/GenisysProPlugins), an organization founded by some GenisysPro developers for resolving plugin-related issues. Thank you!
