### ISSUE TITLE
Player Inventory Problem

### ISSUE THREAD

**Issue by ibookcc** [GenisysPro/GenisysPro#689]
### Before anything do
1.  use method setSize($int) to a Player Inventory
2.  code:
3. `$player->getInventory()->setSize($int);`
4. ($int biger than 36 number)
### Issue aggregate
1. Window10 Edition VERSION Client can not be Corrected response.
The Bag still 36 size.
2. PE(in mobile phone) VERSION Client can be Corrected response,
but, if you pick up the item and your items in bag is full of 36 size..pick up? no..no
the item will be not pick up by you(But create item can put into your bag)
3. PE(in mobile phone) VERSION Client.I try to use code to add item in bag and success .When client open other inventory, like Chest Inventory.Guess what?You bag still see to be 36 size. Other slots can not be seeing.And the other items can't too.So, Player can't handle more than 36 size slots Item to translate.Just only open player's themselves bag can see total size slots.

**Comment by DerddyDert** [comment]
Go to https://discord.gg/WrKzRNn for plugin dev support
