### ISSUE TITLE
网络问题？

### ISSUE THREAD

**Issue by aabbcc872** [GenisysPro/GenisysPro#690]
某些情况下会出现手持物品换不了，而且玩家发言严重卡顿。。。有时得30s后才能收到自己和别人发出的信息。。。感觉不像网络问题因为移动都是好的

**Comment by Leo3418** [comment]
请提供更多信息，例如您使用的插件列表，否则我们无法解决此问题，谢谢！

**Comment by DerddyDert** [comment]
Wut? :-p

**Comment by Antique233** [comment]
太强大了
