### ISSUE TITLE
Update To 1.2 Pls

### ISSUE THREAD

**Issue by ExplodingCraftPE** [GenisysPro/GenisysPro#697]
#### Issue description

JUST UPDATE IT 
#### Platform information

* Git commit:

* PHP binary version:

* Server OS:

* Game client:

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by TDMidkwhatisxd** [comment]
1.2 is just build1

**Comment by ExplodingCraftPE** [comment]
But You Can Update It In

**Comment by DerddyDert** [comment]
@ExplodingCraftPE  1.2 is not released yet. 1.1.5 was just released.

**Comment by ExplodingCraftPE** [comment]
Can You Update It Soon??

**Comment by DerddyDert** [comment]
@ExplodingCraftPE  1.2 Is not released yet.
