### ISSUE TITLE
FallingSand+Slime size

### ISSUE THREAD

**Issue by leolee3914** [GenisysPro/GenisysPro#698]

**Comment by leolee3914** [comment]
FallingSand spawnTo後沒有出現，TileID非0
（包括\pocketmine\block\Fallable::onUpdate()）

Slime大小無法修改，懷疑mcpe已經更改DATA_SLIME_SIZE的值

**Comment by Leo3418** [comment]
請詳細描述您的問題，并且為每個問題分別打開一個issue，謝謝！

**Comment by xISRAPILx** [comment]
@Leo3418 close it...There is no answer.
