### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by ArrowDCA** [GenisysPro/GenisysPro#702]
I'm having this issue with my server i cant join the server because 
of this 
[Server thread/CRITICAL]: ClassNotFoundException: "Class pocketmine\entity\Ilama not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
[22:42:58] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[22:42:58] [Server thread/EMERGENCY]: Please upload the "/root/LeverylServer/crashdumps/CrashDump_Fri_Aug_4-22.42.58-CEST_2017.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

**Comment by DerddyDert** [comment]
Yeah, can't place llamas anymore either. There are 2 spelling variations in the code. Sorry, we need to sort this.

**Comment by MasterOfTheRealm** [comment]
@DerddyDert what are the variations?

**Comment by Leo3418** [comment]
Thanks for reporting. To help us resolve this issue, please provide the abbreviated Git commit SHA-1 of the GenisysPro copy you are using.  
You can find this information from two places:
1. The start-up prompt.
<img width="434" alt="Git commit hash in the start-up prompt" src="https://user-images.githubusercontent.com/14175175/28742546-3bfaee04-7465-11e7-9618-f47384d3ddeb.PNG">

2. Output of `/version` command.
<img width="527" alt="Git commit hash in output of `/version` command" src="https://user-images.githubusercontent.com/14175175/28742553-563c541a-7465-11e7-9ac6-8d941fa5b8f3.PNG">
