### ISSUE TITLE
ArrayItens not Work in GenisysPro

### ISSUE THREAD

**Issue by RedstoneAlmeida** [GenisysPro/GenisysPro#708]
#### Issue description

I'm used ArrayItens from PMMP is work corretly, i'm moved to GenisysPro is stoped work, how to fix?

![image](https://user-images.githubusercontent.com/15146680/28998689-eab26772-7a07-11e7-9122-a8dff9af1557.png)

#### Platform information

* Git commit: #705 

* PHP binary version: 7.0.15

* Server OS: Windows 10 1703 (64-bit)

* Game client: MC:Win10

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

![image](https://user-images.githubusercontent.com/15146680/28998713-48c6d348-7a08-11e7-946d-f4d9d95664c1.png)

**Comment by G2PCraft** [comment]
Where is line 98

**Comment by xISRAPILx** [comment]
plugin ISSUE! use addItem($kit);

**Comment by GamakCZ** [comment]
This is a plugin error, probably the id you have written there are not in the ItemIds folder.

**Comment by Frago9876543210** [comment]
Hmm. May be `setLore` does not return a value.

**Comment by Frago9876543210** [comment]
@RedstoneAlmeida try ```php var_dump($kits);``` before foreach

**Comment by xISRAPILx** [comment]
@Frago9876543210 У него в массиве и так предметы, какого хуя он их получает снова по данным из предметов с массива?

**Comment by Frago9876543210** [comment]
@xISRAPILx idk

**Comment by xISRAPILx** [comment]
@Frago9876543210 закрой це, issue тут не создано для обсуждения плагинов и поиска ошибок в них

**Comment by RedstoneAlmeida** [comment]
in genisysPro item ->setLore not return $this

**Comment by RedstoneAlmeida** [comment]
@GamakCZ i have changed id to GenisysPro ID

**Comment by xISRAPILx** [comment]
@DerddyDert close it. Fixed.

**Comment by DerddyDert** [comment]
Great job guys
