### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by iagomcs** [GenisysPro/GenisysPro#709]
GenisysPro_1.1devcb61a69_2017-08-05

Fatal error: Cannot use pocketmine\level\generator\Void as Void because 'Void' is a special class name in phar:///jar/GenisysPro_1.1dev307d171_2017-07-18.phar/src/pocketmine/Server.php on line 63

**Comment by erkam2002** [comment]
lol

**Comment by ImSnowyy** [comment]
lol 👹
