### ISSUE TITLE
addTitle Function Not Found

### ISSUE THREAD

**Issue by ChaostixZix** [GenisysPro/GenisysPro#71]
Os : Mac Os X
Php : 7.0.3

Hi, I'm making a plugin. And i want to send title to player.
But, i think there is no addTitle function on Player.php

Thank You :D

**Comment by SuperXingKong** [comment]
Please check Player.php carefully. You can find addTitle() method.

**Comment by SuperXingKong** [comment]
Go here. *https://github.com/GenisysPro/GenisysPro/tree/master/Player.php#L3594*
