### ISSUE TITLE
Add always-day= true/false option in genisys.yml

### ISSUE THREAD

**Issue by SuperAdam47** [GenisysPro/GenisysPro#715]
#### Platform information

* Git commit:

* PHP binary version:

* Server OS:

* Game client:

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by DerddyDert** [comment]
Why not always night option too? And then make it per world? This would be a great plugin idea.

**Comment by erkam2002** [comment]
lul

**Comment by Leo3418** [comment]
Why don't you use `/time stop` command? Simply stop the time when it is daytime in game.

**Comment by SuperAdam47** [comment]
@Leo3418  Because the server restarts at the time it restarts
