### ISSUE TITLE
Plugin ServerAuth Lags on /register

### ISSUE THREAD

**Issue by SuperKali** [GenisysPro/GenisysPro#717]
https://github.com/EvolSoft/ServerAuth 
When a player registers the server for a while and then resumes running

**Comment by erkam2002** [comment]
Plugin issue ..

**Comment by SuperKali** [comment]
Where do I open this issue?

**Comment by erkam2002** [comment]
https://github.com/EvolSoft/ServerAuth

**Comment by SuperKali** [comment]
open issue!

**Comment by erkam2002** [comment]
https://github.com/EvolSoft/ServerAuth/issues/new

**Comment by xISRAPILx** [comment]
close it, pls...

**Comment by DerddyDert** [comment]
https://github.com/GenisysProPlugins/PluginRequests @SuperKali

**Comment by andris155** [comment]
I use this plugin, and not generate lag.

**Comment by andris155** [comment]
This plugin works perfectly with GenisysPro.
