### ISSUE TITLE
Chunk problem

### ISSUE THREAD

**Issue by Nolik20** [GenisysPro/GenisysPro#719]
#### Issue description
Chunk problem

#### Platform information
-----Server information-----
This server is running GenisysPro-1.1dev (0000000) LlamaSpit
PHP version: 7.0.15
API: 3.0.1
Target client: Minecraft PE v1.1.0,v1.1.1,v1.1.2,v1.1.3,v1.1.4,v1.1.5
Protocol version: 113

* PHP binary version: 7

* Server OS: Win10

* Game client: MC:Win10 v1.1.5

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)
GenisysPro Crash Dump Tue Aug 8 00:29:28 AST 2017

Error: Call to a member function getChunkEntities() on integer
File: /src/pocketmine/Player
Line: 1073
Type: notice

Code:
[1064] 
[1065] 		$pk = new PlayStatusPacket();
[1066] 		$pk->status = PlayStatusPacket::PLAYER_SPAWN;
[1067] 		$this->dataPacket($pk);
[1068] 
[1069] 		$this->noDamageTicks = 60;
[1070] 
[1071] 		foreach($this->usedChunks as $index => $c){
[1072] 			Level::getXZ($index, $chunkX, $chunkZ);
[1073] 			foreach($this->level->getChunkEntities($chunkX, $chunkZ) as $entity){
[1074] 				if($entity !== $this and !$entity->closed and $entity->isAlive()){
[1075] 					$entity->spawnTo($this);
[1076] 				}
[1077] 			}
[1078] 		}
[1079] 
[1080] 		$this->teleport($pos);
[1081] 
[1082] 		$this->allowFlight = (($this->gamemode == 3) or ($this->gamemode == 1));
[1083] 		$this->setHealth($this->getHealth());

Backtrace:
#0 /src/pocketmine/Player(2095): pocketmine\Player->sendNextChunk(boolean)
#1 /src/pocketmine/Server(2829): pocketmine\Player->checkNetwork(boolean)
#2 /src/pocketmine/Server(2546): pocketmine\Server->tick(boolean)
#3 /src/pocketmine/Server(2424): pocketmine\Server->tickProcessor(boolean)
#4 /src/pocketmine/Server(1995): pocketmine\Server->start(boolean)
#5 /src/pocketmine/PocketMine(492): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\............\Desktop\LiteHub\, string C:\Users\............\Desktop\LiteHub\, string C:\Users\............\Desktop\LiteHub\plugins\)

GenisysPro version: 0000000000000000000000000000000000000000 [Protocol 113; API 3.0.1]
uname -a: Windows NT NOLIKTOP 10.0 build 15063 (Windows 10) AMD64
PHP version: 7.0.15
Zend version: 3.0.0
OS : WINNT, win

Server uptime: 16 seconds
Number of loaded worlds: 1
Players online: 1/20

Loaded plugins:
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
Core 0.1 by flabberfish for API(s) 1.12.0

```

**Comment by armagadon159753** [comment]
How did you get this bug.
How to reproduce it

**Comment by Leo3418** [comment]
You are not using an official build from GenisysPro. Please download an official build from [here](https://genisyspro.github.io/GenisysPro/GenisysPro.phar) and see if this issue still reproduces.

**Comment by xISRAPILx** [comment]
Ойденов не звали!

**Comment by DerddyDert** [comment]
@Nolik20 use latest commit then reopen issue and report your findings.
