### ISSUE TITLE
Crash mcpe

### ISSUE THREAD

**Issue by xRazvan9** [GenisysPro/GenisysPro#72]
#### Issue description

When I get into the server, my mcpe blocks and closes
#### Steps to reproduce the issue

When I get into the server, my mcpe blocks and closes
#### OS and versions

* Genisys: 1.1dev Starry
* PHP:7.0.3
* Server OS:Linux Ubuntu
* Game version: 1.1.0.9

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by DerddyDert** [comment]
Crashdump please @xRazvan9 we need to compare with the crashdump from the latest issue causing a similar error. @caspervanneck @SuperXingKong

**Comment by ObeyBeastJj23** [comment]
i am having the same issue as this, there is no chrash dump as it says that "When I get into the server, my mcpe blocks and crashes" and mine is the same. just joining and on the loading screen it will close my mc down but server will stay running

**Comment by xRazvan9** [comment]
No my server crash 
...my mcpe crash
