### ISSUE TITLE
Server Crashes 

### ISSUE THREAD

**Issue by BajanVlogs** [GenisysPro/GenisysPro#723]
Server thread/CRITICAL TypeError: "ord() expects parameter 1 to be string, boolean given" (EXCEPTION) in "/src/pocketmine/level/format/io/region/RegionLoader" at line 114

server crashes because of this

please fix it

**Comment by FienixEC** [comment]
Is that using latest build?

**Comment by DerddyDert** [comment]
Which commit was it? Also, its most likely cause by a plugin so what new plugin have you used when this started?

**Comment by DerddyDert** [comment]
RegionLoader hasn't been changed in a month and your error appears to be something going wrong with compression. What are all those hacks/fixes you talk about related to the chunk issues and lag? perhaps they messed something up when it went to get compressed. What I recommend is disable your compression and see if you still get errors then report your findings.

**Comment by xISRAPILx** [comment]
The region file was deleted. I do not think there is a mistake in the kernel.
