### ISSUE TITLE
region warning

### ISSUE THREAD

**Issue by Antique233** [GenisysPro/GenisysPro#728]
#### Platform information

* Git commit:

* PHP binary version:7.0

* Server OS:Ubuntu

* Game client:1.1
啥情况啊 我在一个使用genisyspro的服务器建造地图后 导入到另一个使用genisyspro的服务器
然后就炸了
I create a level from a server with GenisysPro to build buildings,then i move to another server with GenisysPro.After that i can't move to that level in that server
#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```
Warning: mkdir(): Permission denied in phar://jar/GenisysPro.phar/src/pocketmine/level/format/io/region/McRegion.php on line 264
Warning: file_put_contents(worlds/PVE-2/level.dat): failed to open stream: Permission denied in phar://jar/GenisysPro.phar/src/pocketmine/level/format/io/region/McRegion.php on line 291
```

**Comment by xISRAPILx** [comment]
pls use chmod...

**Comment by chadigos** [comment]
gpro版本是否一样？？

**Comment by SuperXingKong** [comment]
I agree with @xISRAPILx. It's not a src bug.

**Comment by SuperXingKong** [comment]
HOWTOFIX: 请使用chmod命令给予level.dat读写权限
