### ISSUE TITLE
Call to undefined method pocketmine\network\protocol\MovePlayerPacket::putEntityRuntimeId()

### ISSUE THREAD

**Issue by armagadon159753** [GenisysPro/GenisysPro#73]
![screenshot_2017-06-03-17-47-17](https://cloud.githubusercontent.com/assets/25569806/26754982/f2741f6e-4884-11e7-8b26-ffed36a449e4.png)

**Comment by ldliuzhen** [comment]
the same problem

**Comment by ChaostixZix** [comment]
Same Problem

There Is No putEntityRuntimeId Function On MovePlayerPacket.php
![screenshot at jun 03 09-49-25](https://cloud.githubusercontent.com/assets/19998246/26755436/12ec2504-4842-11e7-9bcb-6c584f1ee796.png)

**Comment by DerddyDert** [comment]
Feel free to make a commit and pull request to fix it @ChaostixZix Also, don't forget, we have a discord chat to discuss things in real-time @ https://discord.gg/WrKzRNn

**Comment by ChaostixZix** [comment]
@DerddyDert Oh, ok

**Comment by ChaostixZix** [comment]
@DerddyDert Thanks :D

**Comment by ChaostixZix** [comment]
@DerddyDert Sorry, i'm a litle new on github, how to make a commit on genisyspro branch?

**Comment by DerddyDert** [comment]
@ChaostixZix  make a fork. Update your fork. Then do a pull request. Then an owner will review it and add, modify or cancel it.

**Comment by SuperXingKong** [comment]
@DerddyDert Help me create a pull request to merge 'network/issue67' branch. I will give you write permission soon.

**Comment by DerddyDert** [comment]
Are they ready to merge?

**Comment by SuperXingKong** [comment]
Yep.

**Comment by SuperXingKong** [comment]
It can resolve this issue.

**Comment by DerddyDert** [comment]
@SuperXingKong it's checking now. Please review then merge or let me know here and I'll merge.

**Comment by SuperXingKong** [comment]
@DerddyDert Fixed now.

**Comment by DerddyDert** [comment]
I'm uploading src to test server now for live testing.   genpro.derddy.com  Port: 19132

**Comment by armagadon159753** [comment]
That no working ;(

**Comment by DerddyDert** [comment]
It's not updated yet. Sorry I uploaded src instead or merged. I'll let u know when it's up and running.

**Comment by DerddyDert** [comment]
Ok the testing server is up and running with the latest src

**Comment by armagadon159753** [comment]
When generating world client disconnect

**Comment by DerddyDert** [comment]
Well we still have other issues. But this one is resolved.
