### ISSUE TITLE
Server Freeze In Windows

### ISSUE THREAD

**Issue by ldliuzhen** [GenisysPro/GenisysPro#734]
#### Issue description

In Windows version,my server often freeze with no warning or error.Any command didn't work.But player can see server is online in server list.But they can into the server.If server without player,this problem not appear...I think this problem due to player connect to server cause.Because i found console is slow to react when they connect..

#### Platform information

* Git commit:

* PHP binary version:7

* Server OS:Windows Server 2008

* Game client:1.1.5

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by chadigos** [comment]
ram not enough?

**Comment by ldliuzhen** [comment]
No ram is enough
