### ISSUE TITLE
Client crash when player open anvil

### ISSUE THREAD

**Issue by armagadon159753** [GenisysPro/GenisysPro#735]
#### Issue description

When open anvil client crash whitout error un console

#### Platform information

* Git commit: 186e56c

* PHP binary version: 7.0.3

* Server OS: 32bit Android 5.1.1 

* Game client:
1.1.5.0

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by SuperXingKong** [comment]
Any ERRORS on console?

**Comment by armagadon159753** [comment]
Nope @SuperXingKong

**Comment by SuperXingKong** [comment]
Ok. I think server sent wrong packet to player. So your game crashed.
Before fixing it, we must find which packet was sent.

**Comment by armagadon159753** [comment]
I think this is LevelEventPacket

**Comment by MasterOfTheRealm** [comment]
i have no problems with anvils at all

**Comment by DerddyDert** [comment]
Reopen if you have the same error 0n latest src
