### ISSUE TITLE
Armor

### ISSUE THREAD

**Issue by vkolomiycev** [GenisysPro/GenisysPro#736]
If you put on armor and go back to the server, it visually disappears ...

* Git commit: 54b1210
* PHP binary version: 7.0
* Server OS:  Ubuntu 16.04 x64
* Game client: MC: PE v1.1.4

**Comment by DerddyDert** [comment]
@vkolomiycev what plugins do you use?

**Comment by TheFixerDevelopment** [comment]
It happens to me as well.

**Comment by DerddyDert** [comment]
@vkolomiycev @TheFixerDevelopment try now with latest commit

**Comment by DerddyDert** [comment]
@MasterOfTheRealm
