### ISSUE TITLE
Kicked by admin. Reason: Flying is not enabled on this server

### ISSUE THREAD

**Issue by jerryzooyoyo** [GenisysPro/GenisysPro#737]
#### Issue description

When players get in the server, they will be kicked due to the flight protection.
But actually... they are not flying...

#### Platform information

* Git commit: 8f1157e

* PHP binary version: 7.0.14

* Server OS: Windows Server 2016

* Game client: MCPE 1.1.5 (not just one client...)

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```
No crash dump, even I open debug mode, nothing shows up...
```
![1502281705793](https://user-images.githubusercontent.com/16357120/29121525-74bed680-7d41-11e7-912c-ac1416cab3ed.jpg)

**Comment by chadigos** [comment]
ok thank you provide bug

**Comment by SuperXingKong** [comment]
Your can disable this function in server.properties
This is an anti-cheat

**Comment by jerryzooyoyo** [comment]
@SuperXingKong well...same.

**Comment by DerddyDert** [comment]
What are they doing when kicked? Jumping on fence or Lily pad causes this.

**Comment by jerryzooyoyo** [comment]
@DerddyDert No...they just join, and be kicked. I use the console to teleport them to the spawn, same. Also, even a new player, same.

**Comment by Frago9876543210** [comment]
Yes, it kick my bots

**Comment by lightda104530** [comment]
Maybe the pack was wrong...

**Comment by bdeh0** [comment]
在我的服务器里也出现了这种情况，玩家说一次是在爬梯子的时候，一次是在跑酷的时候

**Comment by bdeh0** [comment]
刚才还有一位玩家说站在耕地上也会出现这种情况

**Comment by MasterOfTheRealm** [comment]
Yeah this has been happening a lot on my local server

**Comment by DerddyDert** [comment]
@MasterOfTheRealm if u jump on snow lilly and fence it happens. This is an old issue already in ToDo

**Comment by MasterOfTheRealm** [comment]
Yeah well the thing is...i was on grass
