### ISSUE TITLE
使用系統預設指令顯示：未知的指令

### ISSUE THREAD

**Issue by edwinyoo44** [GenisysPro/GenisysPro#739]
#### Issue description
普通玩家無法使用指令，例如：/kill
但若是OP權限的玩家則可以使用

#### Platform information

* Git commit: 22955fa

* PHP binary version: 7.0.14

* Server OS: Ubuntu 17

* Game client: MCPE 1.1.5

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

![image](https://user-images.githubusercontent.com/7691822/29128529-a8f40fd2-7d56-11e7-8ce3-4b1c84f7ae24.png)

**Comment by edwinyoo44** [comment]
附註：No install any plugins,

**Comment by xISRAPILx** [comment]
I'ts not bug))

**Comment by edwinyoo44** [comment]
SO?

**Comment by chadigos** [comment]
把kill的權限設成管理員了

**Comment by edwinyoo44** [comment]
所以現在玩家能使用這些指令了嗎?例如:/kill

**Comment by chadigos** [comment]
可以用了  下載最新版喔

**Comment by edwinyoo44** [comment]
Good

**Comment by chadigos** [comment]
可以了吧?

**Comment by edwinyoo44** [comment]
可以是可以，但是導致其他插件的指令也遇到相同狀況

**Comment by chadigos** [comment]
可以給個 例子嗎??

**Comment by edwinyoo44** [comment]
https://github.com/onebone/EconomyS

**Comment by chadigos** [comment]
你說玩家不能用圈地指令嗎?

**Comment by edwinyoo44** [comment]
/startp、/endp正常使用
只有/land 不能

**Comment by chadigos** [comment]
那是插件問題了吧?
加個line : 3026016 
👍

**Comment by edwinyoo44** [comment]
插件問題?那這個的更新用意是?
#2d5adfe

**Comment by chadigos** [comment]
kill是核心指令land是插件自己的

**Comment by edwinyoo44** [comment]
你們增加這行的用意是什麼?
https://github.com/GenisysPro/GenisysPro/commit/2d5adfed512fb69103257540d858dc47fb6fecca

**Comment by chadigos** [comment]
那是對核心指令的判斷
不是插件的
例如你說的land應該要去plugin.yml去改權

**Comment by edwinyoo44** [comment]
這是你們增加這行判斷後產生的問題
況且PMMP也沒新增此判斷，你們應該改善他的判斷規則

**Comment by chadigos** [comment]
..那麼先改回來應該是land內部用了核心的權限判斷
那我改kill就好

**Comment by chadigos** [comment]
----------------------------------------
+額  這就很多囉$player->isOp()

**Comment by edwinyoo44** [comment]
嗯，所以沒有先撤銷該更新了?

**Comment by chadigos** [comment]
有更新阿kill指令刪除了權限
普通玩家也可以用

**Comment by chadigos** [comment]
你可以試試

**Comment by edwinyoo44** [comment]
所以該權限判斷有何意義?
沒加玩家會越權用到op指令?
如果不，那判斷則是多餘的

**Comment by chadigos** [comment]
這別問我，不是我加的
應該是把玩家可以用的指令重新判斷

**Comment by edwinyoo44** [comment]
你們不應該新增無謂的東西，和PMMP相背而行

**Comment by chadigos** [comment]
並沒有相背而行，只是另一種判斷

**Comment by edwinyoo44** [comment]
當這第三方分支偏離的話，說真的就真的沒必要

**Comment by chadigos** [comment]
沒有分離阿  api都是在的只是內部的話用不同判斷
那這樣就沒有genisys

**Comment by edwinyoo44** [comment]
當你新增時，你有沒有想過這將會導致PocketMine插件失效?
而你可能會說，那就找作者更新啊

但現在重點作者當然會以PMMP為主，不會為了第三方分支而去更新

**Comment by chadigos** [comment]
額所以api沒變阿
插件是調用api
不是我們核心的寫法

**Comment by edwinyoo44** [comment]
所以啦，請問你們增加這條判斷的用意是什麼?

**Comment by chadigos** [comment]
@Frago9876543210 
我不清楚不是我加的

**Comment by chadigos** [comment]
foreach($this->server->getCommandMap()->getCommands() as $command){
-			if(($cmdData = $command->generateCustomCommandData($this)) !== null){
-				++$count;
-				$data->{$command->getName()}->versions[0] = $cmdData;

-----------------------------------------------------------------------------------------
+			if($this->hasPermission($command->getPermission()) or $command->getPermission() == null) {//應該是判斷有無權限
+				if (($cmdData = $command->generateCustomCommandData($this)) !== null){
+					++$count;
+					$data->{$command->getName()}->versions[0] = $cmdData;
+				}
 			}
 		}

**Comment by edwinyoo44** [comment]
那麼請你們給個合理的說明
新增一個不影響原運作且原PMMP也沒有新增的判斷
讓此第三方分支在這部分與PMMP偏離，導致遵循原PMMP編寫的插件失效

**Comment by edwinyoo44** [comment]
對了，請你打開這問題
待問題真的解決再關閉它

**Comment by chadigos** [comment]
恩...
好可能真的是錯了
 然而你的問題解決了阿

問題:kill無法執行??

**Comment by edwinyoo44** [comment]
@Leo3418 我需要你過來看看ww

**Comment by chadigos** [comment]
我想應該結束了
少了!

**Comment by edwinyoo44** [comment]
你 killcommond.php不恢復看看??

**Comment by chadigos** [comment]
如果還有那再來討論

**Comment by chadigos** [comment]
你可以再去試試=.=.
