### ISSUE TITLE
A weird glitch? Idk.

### ISSUE THREAD

**Issue by TheFixerDevelopment** [GenisysPro/GenisysPro#740]
#### Issue description

The issue I'm having, is when I join my server, it lags the server, like kinda crashes. And the other weird thing, is because I have two servers, the one I'm having issues on, has the default-format to pmanvil on the pocketmine.yml file, but on my second server (With no issues) it has anvil as the default-format on what worlds will use to create the levels. I was wondering if I change pmanvil to anvil, will that reset my worlds? Thank you.
Here: 
![img_0686](https://user-images.githubusercontent.com/30442910/29131854-16fb2be0-7d26-11e7-831f-cec988027046.PNG)

#### Platform information

* Git commit:
09.08 10:11:27 [Server] Server thread/INFO Protocol version: 113
09.08 10:11:27 [Server] Server thread/INFO Target client: Minecraft PE v1.1.0,v1.1.1,v1.1.2,v1.1.3,v1.1.4,v1.1.5
09.08 10:11:27 [Server] Server thread/INFO API: 3.0.1
09.08 10:11:27 [Server] Server thread/INFO PHP version: 7.0.19
09.08 10:11:27 [Server] Server thread/INFO This server is running GenisysPro-1.1dev [#54b1210 2017-08-07] (54b1210) LlamaSpit

* PHP binary version: 7.0.19

* Server OS:

* Game client: MC:PE v1.1.5, on iOS 10.3.1

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by SuperXingKong** [comment]
Actually not. If you change pmanvil to anvil, server will just generate new world with this format, not loading.

**Comment by TheFixerDevelopment** [comment]
So will the world reset or not? I mean the one I created with pmanvil.

**Comment by MasterOfTheRealm** [comment]
It won't reset if you are only changing pocketmine.yml...you are able to run MCRegion, Anvil and PMAnvil worlds on the same server...changing default-format will only affect the new worlds created.
