### ISSUE TITLE
Cannot remove Item after cancel PlayerDropItemEvent

### ISSUE THREAD

**Issue by diamond-gold** [GenisysPro/GenisysPro#746]
#### Issue description
 When you cancel PlayerDropItemEvent and try to remove the item $inv->removeItem(), the item stays in the inventory

#### Platform information

* Git commit:186e56c

* PHP binary version:7

* Server OS: Win8

* Game client: PE 1.1.4 on Android

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```
public function OnDropItem(PlayerDropItemEvent $event){
		$p = $event->getPlayer();
		$item = $event->getItem();
		if($item->getId() === 46){
			$event->setCancelled();
			$p->getFloatingInventory()->removeItem($item);
			$p->getInventory()->removeItem($item);
		}
```

**Comment by xISRAPILx** [comment]
Lol, easy to fix

**Comment by xISRAPILx** [comment]
Translate goods in inventory exists in the core

```
public function OnDropItem(PlayerDropItemEvent $event){
              $p = $event->getPlayer();
		$item = $event->getItem();
		if($item->getId() === 46){
			$p->getFloatingInventory()->removeItem($item);
			$p->getInventory()->removeItem($item);
                        $event->setCancelled();
		}
```

**Comment by diamond-gold** [comment]
I want to remove the item when the player drops the item, but I cannot do it, because the core just adds the item back anyway..

**Comment by KenMizz** [comment]
try $item=$event->getItem()->getItem();

**Comment by xISRAPILx** [comment]
Do you want to delete the item without dropping it? @diamond-gold

**Comment by diamond-gold** [comment]
@xISRAPILx  Yep

**Comment by ivan691** [comment]
Try remove item, then cancel event

**Comment by diamond-gold** [comment]
@ivan691 There is no difference..

**Comment by diamond-gold** [comment]
I've debugged it, it is because of this line, that adds the item and plugins dont have anyway to stop that
https://github.com/GenisysPro/GenisysPro/blob/master/src/pocketmine/Player.php#L3776

**Comment by TheAz928** [comment]
Use a delayed task to remove the item since it takes some time to update after cancelling an event

**Comment by diamond-gold** [comment]
But that way is just a hack.... doesn't solve the actual problem...

**Comment by DerddyDert** [comment]
@diamond-gold The core is as it is. You have 2 options. Change the way you make your plugin or change the core with a PR. If the PR is acceptable we can merge it. Also go to our discord for more help. https://discord.gg/WrKzRNn
