### ISSUE TITLE
Sponge doesn't absorb water

### ISSUE THREAD

**Issue by poustmal** [GenisysPro/GenisysPro#750]
![screenshot_2017-08-09-23-22-12](https://user-images.githubusercontent.com/22281205/29167020-79fe19cc-7dd1-11e7-9f64-9ea9b4dd9723.png)
And I have absorb-water to true

**Comment by DerddyDert** [comment]
@Frago9876543210

**Comment by armagadon159753** [comment]
@poustmal make sur set ##TRUE
`enchantment:
 #Choose if anvils are enabled
 enable-anvil: true
 #Choose if enchantment tables are enabled
 enable-enchanting-table: true
 #Choose if to count bookshelves (may cause server lag)
 #If this option is false, the server will use a random count (0~15)
 count-bookshelf: false`

**Comment by poustmal** [comment]
I have already enable-anvil to true and count bookshelf to false

**Comment by SuperXingKong** [comment]
@Frago9876543210

**Comment by DerddyDert** [comment]
@Frago9876543210 can you fix this please?

**Comment by Frago9876543210** [comment]
Fixed
