### ISSUE TITLE
Permission bug

### ISSUE THREAD

**Issue by Crypt97** [GenisysPro/GenisysPro#755]
#### Issue description
The problem is that sometimes the rights automatically turn off and allow players who would otherwise have no license to use them.

#### Platform information

* Git commit: latest

* PHP binary version: 7.0

* Server OS: Ubuntu

* Game client: 1.1.5

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```
[EssentialsPE] bencep is also known as HeroKnight
10.08 17:00:28 [Server] Server thread/CRITICAL Unhandled exception executing command 't bence d' in tell: Trying to get permissions of closed player
10.08 17:00:28 [Server] Server thread/CRITICAL InvalidStateException: "Trying to get permissions of closed player" (EXCEPTION) in "/src/pocketmine/Player" at line 686
```
 Error all plugins after change "get::Name" to "get::DiplayName"

**Comment by flayzer** [comment]
Show the code

**Comment by andris155** [comment]
This is a Ghost players bug. 
1.0.x - works.
1.1.x - randomly ghost players.

**Comment by xISRAPILx** [comment]
#748

**Comment by xISRAPILx** [comment]
@DerddyDert close it! fixed
