### ISSUE TITLE
IMPORTANT ISSU

### ISSUE THREAD

**Issue by armagadon159753** [GenisysPro/GenisysPro#761]
#### Issue description

https://youtu.be/t6sc4XT3Uvg
1:This video proves that thanks to my pull request the sponge works 
ISSSU 1: ChorusFlower When I put this block lanitation ñ does not appear
ISSU 2: ChorusPlant When I set this block it causes the sound as if the block does not exist
ISSY 3: SnowLayer The orca I remove snow on the ground, the one that causes the sound of a block

NOTE!!: SAME ISSU ON ANRDOID BUT POSSING ANIPATION WORK FOR CHORUSEFLOWER

#### Platform information

* Git commit:
c47625b

* PHP binary version: 7.0.3

* Server OS:
Android server 32bit

* Game client:
mcpe 1.1.5.0 Android 5.0.0 32bit
Windows 10: 1.1.5.0 64bit

**Comment by armagadon159753** [comment]
To understand this list of problems I invite you to reagrde my video:
@DerddyDert @SuperAdam47 @SamyR0 @Frago9876543210 
Already thx ^~^

**Comment by xISRAPILx** [comment]
I will try to fix it. Connect me.

**Comment by armagadon159753** [comment]
@xISRAPILx I was added as a collaborator in my fork
