### ISSUE TITLE
setKeepExperiens in PlayerDeathEvent

### ISSUE THREAD

**Issue by Donquih0te** [GenisysPro/GenisysPro#764]
#### Issue description
In PlayerDeathEvent when using setKeepExperience(true) need to reconnect to the server after death to the level of experience reappeared

#### Platform information

* Git commit:
This server is running GenisysPro-1.1dev2164fd9 LlamaSpit
API: 3.0.1
Target client: Minecraft PE v1.1.0,v1.1.1,v1.1.2,v1.1.3
Protocol version: 113

* PHP binary version: 7.0.6

* Server OS: Debian 8

* Game client: Minecraft Win10 Edition v.1.1.5

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```
Crush non
```

**Comment by xISRAPILx** [comment]
Hello, Dinor
