### ISSUE TITLE
что делать, если зашел на карту, а потом вышел в лобби, то оно не грузится так как больше

### ISSUE THREAD

**Issue by flayzer** [GenisysPro/GenisysPro#765]
#### Platform information

* Git commit:

* PHP binary version:

* Server OS:

* Game client:

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by xISRAPILx** [comment]
chunk not load

**Comment by flayzer** [comment]
@xISRAPILx как исправить то с:

**Comment by DerddyDert** [comment]
Anvil map?

**Comment by flayzer** [comment]
@DerddyDert mapa, lobby

**Comment by DerddyDert** [comment]
Cache chunks?

**Comment by flayzer** [comment]
@DerddyDert Pieces

**Comment by DerddyDert** [comment]
@flayzer did you get it fixed?
