### ISSUE TITLE
setDrops in PlayerDeathEvent

### ISSUE THREAD

**Issue by Donquih0te** [GenisysPro/GenisysPro#766]
#### Issue description
In if you are using PlayerDeathEvent $event->setDrops([Item::get(388, 0, 1, "Emerald")]); after the death of the item is not drops

#### Platform information

* Git commit:
This server is running GenisysPro-1.1dev2164fd9 LlamaSpit
API: 3.0.1
Target client: Minecraft PE v1.1.0,v1.1.1,v1.1.2,v1.1.3
Protocol version: 113

* PHP binary version: 7.0.6

* Server OS: Debian 8

* Game client: Minecraft Win10 Edition v.1.1.5

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```
Crush non
```

**Comment by xISRAPILx** [comment]
This is the conspiracy of the Masons!! @Donquih0te

**Comment by DerddyDert** [comment]
@Donquih0te you have a very old src

**Comment by Donquih0te** [comment]
@DerddyDert in new src it is fixed?

**Comment by DerddyDert** [comment]
Not sure as I can't replicate. However there have been so many commits since yours https://genisyspro.github.io/GenisysPro/GenisysPro.phar

**Comment by xISRAPILx** [comment]
@Donquih0te не исправило?

**Comment by NycuRO** [comment]
It's not like that.

**Comment by NycuRO** [comment]
event->getEntity()->getDrop()

**Comment by Donquih0te** [comment]
@NycuRO I use setDrops([]);

**Comment by Donquih0te** [comment]
@xISRAPILx новое не тестил

**Comment by DerddyDert** [comment]
This issue is invalid. We have many nice people that would be happy to help you in our discord chat. https://discord.gg/WrKzRNn
