### ISSUE TITLE
创造模式下可以打开工作台

### ISSUE THREAD

**Issue by bdeh0** [GenisysPro/GenisysPro#769]
创造模式下可以打开工作台
在物品栏是满着的时候，合成物品就会以掉落物的形式出现
这就可以让创造模式的玩家在物品栏装满的情况下利用工作台刷物品

**Comment by Leo3418** [comment]
原版就是这样的。再说创造模式下本来就可以想要什么要什么，“刷物品”一说没有任何意义。
如果需要创造模式下不允许使用工作台，请自行修改源代码。GenisysPro基于GPL授权，就是方便大家如果自己有特殊需求，可以自由地修改软件。
