### ISSUE TITLE
一直闪退，请问怎么解决？有Crash logs

### ISSUE THREAD

**Issue by zxl777** [GenisysPro/GenisysPro#770]
Crash logs

GenisysPro Crash Dump Sat Aug 12 12:54:09 CST 2017

Error: Call to a member function sendContents() on null
File: /src/pocketmine/Player
Line: 1117
Type: notice

Code:
[1108] 		if($this->getHealth() <= 0){
[1109] 			$pk = new RespawnPacket();
[1110] 			$pos = $this->getSpawn();
[1111] 			$pk->x = $pos->x;
[1112] 			$pk->y = $pos->y;
[1113] 			$pk->z = $pos->z;
[1114] 			$this->dataPacket($pk);
[1115] 		}
[1116] 
[1117] 		$this->inventory->sendContents($this);
[1118] 		$this->inventory->sendArmorContents($this);
[1119] 	}
[1120] 
[1121] 	/**
[1122] 	 * @return bool
[1123] 	 */
[1124] 	protected function orderChunks(){
[1125] 		if($this->connected === false or $this->viewDistance === -1){
[1126] 			return false;
[1127] 		}

Backtrace:
#0 /src/pocketmine/Player(2084): pocketmine\Player->sendNextChunk(boolean)
#1 /src/pocketmine/Server(2829): pocketmine\Player->checkNetwork(boolean)
#2 /src/pocketmine/Server(2546): pocketmine\Server->tick(boolean)
#3 /src/pocketmine/Server(2424): pocketmine\Server->tickProcessor(boolean)
#4 /src/pocketmine/Server(1995): pocketmine\Server->start(boolean)
#5 /src/pocketmine/PocketMine(497): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///root/pmmp/PocketMine-MP.phar/, string /root/pmmp/, string /root/pmmp/plugins/)
#6 (1): require_once(string phar:///root/pmmp/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

GenisysPro version: cb61a69d4ed7ec6ef917be8cdc718bcec3190d16 [Protocol 113; API 3.0.1]
uname -a: Linux iZt4ncs0fu03n78v5wilaiZ 4.4.0-85-generic #108-Ubuntu SMP Mon Jul 3 17:23:59 UTC 2017 x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 56 seconds
Number of loaded worlds: 5
Players online: 2/666

Loaded plugins:
Asign 1.4 by Kirt for API(s) 1.10.0
Opaving 1.0.0 by Orange for API(s) 1.0.0, 2.0.0, 3.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4
SimpleMarry 1.3.0 by Him188 for API(s) 1.0.0
db 1.0.0 by Benben for API(s) 1.1.0
essentialsTP 1.0.9 by  for API(s) 1.0.0
DisableFlow 1.0.0 by MUedsa for API(s) 1.8.0
SWorld 1.1.0 by 18WYJ2 & boybook for API(s) 1.0.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
QituShop 1.2.0 by qitu for API(s) 1.0.0
ld 流星优化 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
RealKeepInventory 0.0.1 by MUedsa for API(s) 1.8.0
AuthMePE 1.0.1 by hoyinm14mc, Edwardthedog2 for API(s) 3.0.0-ALPHA7
MagicWE 0.2.7 by thebigsmileXD for API(s) 3.0.0-ALPHA3
SmartSign_by腐竹CrainL 1.0.0 by CrainL for API(s) 1.0.0
MagicTelePortal 1.3.2 didou汉化 by aliuly for API(s) 1.10.0
ChestLocker 1.2 by EvolSoft for API(s) 1.8.0

**Comment by DerddyDert** [comment]
@ivan691

**Comment by xISRAPILx** [comment]
how to reproduce?

**Comment by Kazuko0310** [comment]
玩家進去才閃退嗎？

**Comment by ivan691** [comment]
idk i just removed useless code

**Comment by DerddyDert** [comment]
@ivan691 maybe it wasn't so useless? What was the purpose of that commit? 90d2715
