### ISSUE TITLE
Entity bug

### ISSUE THREAD

**Issue by SerezhaIvanov** [GenisysPro/GenisysPro#771]
![screenshot_2017-08-12-14-57-50](https://user-images.githubusercontent.com/12472255/29240592-f93ded02-7f70-11e7-8c3a-29f401a7dab6.png)

#### Issue description

I create a Crepeer and when i restart the server her yaw changes.

#### Platform information

* Git commit:

* PHP binary version: 7.0.3

* Server OS: Ubuntu

* Game client: PE

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```
No errors

```

**Comment by SerezhaIvanov** [comment]
![screenshot_2017-08-12-11-47-48](https://user-images.githubusercontent.com/12472255/29240614-493a4fb2-7f71-11e7-9213-3a25440ebd65.png)

After the restart

**Comment by xISRAPILx** [comment]
Так тебе и надо! XD

**Comment by SerezhaIvanov** [comment]
Заебись разрабы

**Comment by Dospoker** [comment]
©xISRAPILx
Угар

**Comment by NolikTop** [comment]
бля ахах

**Comment by ivan691** [comment]
лол

**Comment by An0ther1337** [comment]
Ну может в той стороне что-то интересное ))

**Comment by chadigos** [comment]
SO COOL

**Comment by DerddyDert** [comment]
Made a creeper? Like NPC? Slapper? Or spawned a mob? @SerezhaIvanov
