### ISSUE TITLE
armour glich

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [GenisysPro/GenisysPro#772]
https://youtu.be/J8yqHCJIBTQ

Video explain all.
1. I login and armour gone.
2. I did /kill and armour back
3. U can see 0 plugins.

**Comment by armagadon159753** [comment]
First thing getting bug happens it in PE version?
Third: Is the KeepInventory enabled?

**Comment by armagadon159753** [comment]
First thing getting bug happens it in PE version?
Third: Is the KeepInventory enabled?

**Comment by TDMidkwhatisxd** [comment]
I dont know.
I use keepinventory plugin by me.
But why ask that? I only have this problem after i updated genisys

**Comment by TDMidkwhatisxd** [comment]
on video, all was default, keepinv off

**Comment by armagadon159753** [comment]
dell KeppInv plugin avec try again with set true un .yml

**Comment by TDMidkwhatisxd** [comment]
you are noob. Wtf,didnt see in video no plugins?
Fake Dev. I will fix it in a free time, i have real life job you know? And is super hard.

**Comment by TDMidkwhatisxd** [comment]
If genisys keep adding fakedevs i quit it.

**Comment by TDMidkwhatisxd** [comment]
found the problem
https://github.com/GenisysPro/GenisysPro/commit/54b12109d6fd817cefac33e740a08035a2f9783f
