### ISSUE TITLE
Superadam47 logged out due to timeout

### ISSUE THREAD

**Issue by SuperAdam47** [GenisysPro/GenisysPro#774]
#### Issue description
What the bug

#### Platform information

* Git commit:

* PHP binary version: 7.0.14

* Server OS: CentOS 7

* Game client: 1.1.4

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by armagadon159753** [comment]
Which commit?

**Comment by MasterOfTheRealm** [comment]
Please elaborate @SuperAdam47 , we can't do much with what you said

**Comment by DerddyDert** [comment]
The turtle bug snap pop rimmed out too? :-p
