### ISSUE TITLE
Slapper not work.... (Human)

### ISSUE THREAD

**Issue by SuperKali** [GenisysPro/GenisysPro#776]
ISSUE:
Slapper no longer has this update,  I have assigned a command to the entity and not the teletravel in the various worlds!

GIF: https://giphy.com/gifs/26n6VlEfj1RFbEmn6

**Comment by xISRAPILx** [comment]
have any errors?

**Comment by SuperKali** [comment]
nope

**Comment by xISRAPILx** [comment]
In my plugin all nice...

**Comment by DerddyDert** [comment]
@SuperKali  which slapper are you using? What changed just before the issue started?

**Comment by SuperKali** [comment]
I use the version of slapper I took on GenisysPro Plugin,
The problem occurred from the version update.

**Comment by sc00scoc** [comment]
`
use slapper\entities\SlapperHuman;
public function onDamage(EntityDamageEvent $event) {
      switch ($event->getCause()) {
            case EntityDamageEvent::CAUSE_ENTITY_ATTACK:
                  if (!$entity instanceof SlapperHuman) {
                        $event->setCancelled(true);
                  }
      }
}`

**Comment by SuperKali** [comment]
@sc00scoc ??

**Comment by SuperKali** [comment]
Notice: Undefined index:  in C:\Users\Administrator\Documents\BackupMain#2\1\src\pocketmine\inventory\PlayerInventory.php on line 104

Notice: Undefined property: PocketEssential\BossBarAPI\UpdateAttributesPacket::$selectedSlot in C:\Users\Administrator\Documents\BackupMain#2\1\src\pocketmine\Player.php on line 2605

Notice: Undefined property: PocketEssential\BossBarAPI\UpdateAttributesPacket::$slot in C:\Users\Administrator\Documents\BackupMain#2\1\src\pocketmine\Player.php on line 2605

Notice: Undefined index:  in C:\Users\Administrator\Documents\BackupMain#2\1\src\pocketmine\inventory\PlayerInventory.php on line 104

Notice: Undefined index:  in C:\Users\Administrator\Documents\BackupMain#2\1\src\pocketmine\inventory\PlayerInventory.php on line 104

Notice: Undefined index:  in C:\Users\Administrator\Documents\BackupMain#2\1\src\pocketmine\inventory\PlayerInventory.php on line 104

**Comment by SuperKali** [comment]
http://giphy.com/gifs/3oEhmN7VuzrH2I81Hi

**Comment by SuperKali** [comment]
I removed BossBarAPI but the problem remains the same

**Comment by DerddyDert** [comment]
@SuperKali which commit did you update to?

**Comment by SuperKali** [comment]
https://github.com/GenisysPro/GenisysPro/commit/f8eb85272ce1e9ad2626d7b83c1640a6a4daa058

**Comment by MasterOfTheRealm** [comment]
@SuperKali Slappers should work now...don't forget to change folder paths!

**Comment by SuperKali** [comment]
Ok I do the tests

**Comment by DerddyDert** [comment]
@SuperKali did it work?

**Comment by DerddyDert** [comment]
Does it work on latest src?

**Comment by MasterOfTheRealm** [comment]
Technically it should be working fine now.
