### ISSUE TITLE
Im trying to play on my windows 10 but when i try to connect to my server it says unable to connect to world

### ISSUE THREAD

**Issue by moneymill2400** [GenisysPro/GenisysPro#777]
It will say syncing pack with server then stop and say unable to connect to world but I can join on my iphone

**Comment by xISRAPILx** [comment]
local server?

**Comment by MasterOfTheRealm** [comment]
@moneymill2400 need more info please

**Comment by DerddyDert** [comment]
This issue is invalid. We have many nice people that would be happy to help you in our discord. https://discord.gg/WrKzRNn
