### ISSUE TITLE
PlayerItemHeldEvent not working correctly

### ISSUE THREAD

**Issue by KenMizz** [GenisysPro/GenisysPro#781]
#### Issue description
PlayerItemHeldEvent not working correctly

#### Platform information

* Git commit:88a745e

* PHP binary version:7.0.8

* Server OS:Windows Server 2016 Datacenter

* Game client:MC:Win10 v1.1.5

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```
`use pocketmine\event\player\PlayerItemHeldEvent;
public function HeldItem(PlayerItemHeldEvent $ev){
		$itemid=$ev->getItem()->getId();
		$Player=$ev->getPlayer();
		if(itemid==2){
			$ev->setCancelled(true);
			$Player->sendMessage("you are unable to use this item");
		}
	}`
I can still hold it even i setcancelled to true
```

**Comment by DerddyDert** [comment]
How to recreate this issue?

**Comment by DerddyDert** [comment]
This issue is invalid. We have many nice people that would be happy to help you in our discord chat. https://discord.gg/WrKzRNn
