### ISSUE TITLE
FloatingParticle bug :(

### ISSUE THREAD

**Issue by oGalatico** [GenisysPro/GenisysPro#782]
#### Platform information

* Git commit:

* PHP binary version:

* Server OS:

* Game client:

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by oGalatico** [comment]
When I add a floating text after a few minutes it some ...

**Comment by DerddyDert** [comment]
So a few minute delay before it works?

**Comment by DerddyDert** [comment]
@CortexPE didn't you mention something about this the other day?

**Comment by oGalatico** [comment]
E mais uma coisa voçes vao adicionar SpoonDetector ?

**Comment by oGalatico** [comment]
Will you add Spoon Detector?

**Comment by oGalatico** [comment]
I do not know what's really just know that I need it for BlockPet to work :(

**Comment by MasterOfTheRealm** [comment]
Spoon Detector is nothing but a cheap tactic by people who don't understand what open source means

**Comment by MasterOfTheRealm** [comment]
@oGalatico give me the github link for that plugin please

**Comment by CortexPE** [comment]
@oGalatico No offence, but you don't even know what SpoonDetector does.
And yes, @DerddyDert I told you (and @MasterOfTheRealm ) to change FloatingTextParticle from spawning an ItemEntity to spawning an invisible player instead...
I might make a PR for it...

**Comment by CortexPE** [comment]
Take a look here:
https://github.com/LeverylTeam/Leveryl/blob/master/src/pocketmine/level/particle/FloatingTextParticle.php#L89-L108

**Comment by MasterOfTheRealm** [comment]
Will be helpful if you can make the PR ...been busy with some stuff that happened while i was away lol

**Comment by CortexPE** [comment]
ight.

**Comment by MasterOfTheRealm** [comment]
Thanks!

**Comment by CortexPE** [comment]
Works!
![image](https://user-images.githubusercontent.com/17762324/29399737-05907d68-82f0-11e7-9452-7dd13fad6242.png)
Lemme just make the PR

**Comment by CortexPE** [comment]
https://github.com/GenisysPro/GenisysPro/pull/798

**Comment by CortexPE** [comment]
Here's the PR:
https://github.com/GenisysPro/GenisysPro/pull/798

**Comment by oGalatico** [comment]
@MasterOfTheRealm https://github.com/BlockHorizons/BlockPets
