### ISSUE TITLE
commands bug

### ISSUE THREAD

**Issue by Crypt97** [GenisysPro/GenisysPro#785]
#### Issue description
The time command does not work for players who are not operators but have the right (PurePerms)
This bug is in the EconomyLand plugin

1. Download src
2. Download Pureperms,PureChat
3. add pureperms permission: pocketmine.command.time
4. start game
5. type: /time set day

Operators only :/

#### Platform information

* Git commit: latest

* PHP binary version: 7.0

* Server OS: Ubuntu

* Game client: 1.1.5

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by VoliPlays** [comment]
Reinstall the plugin and configure it again.

**Comment by DerddyDert** [comment]
Come get help in our discord chat.

**Comment by DerddyDert** [comment]
https://discord.gg/WrKzRNn
