### ISSUE TITLE
在告示牌上输入中文时，屏幕前的牌子不会随着写字的位置移动

### ISSUE THREAD

**Issue by bdeh0** [GenisysPro/GenisysPro#791]
在一个告示牌上输入中文时，屏幕前的牌子不会随着写字的位置移动
因此只能看到牌子上前两行的字
如果输入英文或数字，就不会出现这个问题

**Comment by bdeh0** [comment]
![Uploading IMG_1227.PNG…]()

**Comment by Leo3418** [comment]
Duplicate of #181
Before you submit any issue, please have a look at all other existing issues, and make sure your issue does not duplicate any other issue. Thank you!
