### ISSUE TITLE
Don't Forget To Update Your Plugins! (Important)

### ISSUE THREAD

**Issue by MasterOfTheRealm** [GenisysPro/GenisysPro#793]
Due to the latest commits please remember that the protocol folder path has been changed to 
`pocketmine\network\mcpe\protocol` from `pocketmine\network\protocol`

Please update all your plugins accordingly!

Also you can now use PMMP plugins without modifications to the folder path now!

**Comment by SourSmirnoff** [comment]
Hmm, has it not been added to the releases/downloads yet? I havent been able to successfully compile the source, but i downloaded the latest .phar and after converting my plugins it gave me the error 
Server thread/CRITICAL ClassNotFoundException: "Class pocketmine\network\mcpe\protocol\AddItemEntityPacket not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

Let me know if its just not added yet or what please

**Comment by DerddyDert** [comment]
@SourSmirnoff  try this link https://genisyspro.github.io/GenisysPro/GenisysPro.phar let me know

**Comment by SourSmirnoff** [comment]
Uploading now

**Comment by MasterOfTheRealm** [comment]
@SourSmirnoff https://github.com/GenisysPro/GenisysPro/blob/master/src/pocketmine/network/mcpe/protocol/AddItemEntityPacket.php

**Comment by MasterOfTheRealm** [comment]
that packet exists

**Comment by DerddyDert** [comment]
Maybe he used the wrong link

**Comment by DerddyDert** [comment]
I don't know if all commits build the phar by default still? @Leo3418

**Comment by SourSmirnoff** [comment]
Okay, That one's working. Here is the Link that is "incorrect"
![screenshot 22](https://user-images.githubusercontent.com/29271449/29399150-e76e834c-82dc-11e7-802c-f26c4cd827c9.png)

**Comment by MasterOfTheRealm** [comment]
Oh must be outdated

**Comment by SourSmirnoff** [comment]
Thanks for the help. Also, {off topic i srry} am i doing something wrong or are mobs not currently Added/Working?

**Comment by MasterOfTheRealm** [comment]
Mobs are added...but with no AI

**Comment by MasterOfTheRealm** [comment]
https://github.com/RevivalPMMP/PureEntitiesX use this for mobs with AI

**Comment by SourSmirnoff** [comment]
Okay, thats what i had in the past but they use the network\mcpe\protocol and it would have been a lot to fix haha

**Comment by SourSmirnoff** [comment]
Thanks Guys!

**Comment by MasterOfTheRealm** [comment]
lol now it should work fine, if not just post it here https://github.com/GenisysProPlugins/PluginRequests/issues/new

**Comment by junkdude** [comment]
u realize packets arent the only thing u have to change right, the entity folder needs to be updated, commands, etc

**Comment by MasterOfTheRealm** [comment]
they already were changed all thanks to @CortexPE

**Comment by mote166** [comment]
Does the 1.1.2 - 1.1.5 release have these changes ?
