### ISSUE TITLE
Cannot execute binary file

### ISSUE THREAD

**Issue by PetteriM1** [GenisysPro/GenisysPro#794]
Server not start. Cannot execute binary file: The format of the file to be started is invalid* when I run start.sh.

*Google translated

* Git commit: I don't know
* PHP binary version: 7.0.21
* Server OS: Lubuntu 32-bit
* Game client: Win10 1.1.5

user@EliteBook6930p:~$ cd /home/user/GenisysPro
user@EliteBook6930p:~/GenisysPro$ ./start.sh
./start.sh: rivi 72: /home/user/GenisysPro/bin/php7/bin/php: cannot execute binary file: Käynnistettävän tiedoston muoto virheellinen
./start.sh: rivi 72: /home/user/GenisysPro/bin/php7/bin/php: Onnistui
user@EliteBook6930p:~/GenisysPro$

**Comment by Takesikaityo** [comment]
Maybe GenisysPro doesn't support 32bit bin

**Comment by TreatHacker** [comment]
HEY @Takesikaityo YOU MUST REVIEW [THIS](https://github.com/GenisysPro/GenisysPro/pull/779) PR FIRST INSTEAD OF THIS THREAD RIGHT? EH?    
**COME ON NOW AND REVIEW NOW!!!**

**Comment by DerddyDert** [comment]
Run  `./start.sh`

**Comment by DerddyDert** [comment]
Oh y0u set it up wrong. Come to the discord chat for help

**Comment by PetteriM1** [comment]
I set it up like wiki say and not worked.
