### ISSUE TITLE
block bug

### ISSUE THREAD

**Issue by Nerahikada** [GenisysPro/GenisysPro#795]
#### Issue description

https://youtu.be/IUIowhi5PLw
I think that the processing to break the block is not done.
(BlockBreakEvent wasn't called.)

#### Platform information

* Git commit: https://github.com/GenisysPro/GenisysPro/commit/462c4dd0e96a7751edc9a0444e43671789500e34

* PHP binary version: 7.0.17

* Server OS: Windows 10 (64-bit)

* Game client: Minecraft: Windows 10 Edition

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by MasterOfTheRealm** [comment]
any errors on console?

**Comment by MasterOfTheRealm** [comment]
unable to reproduce...please use the latest version of GenisysPro and if you are then try without any plugins you might have

**Comment by Nerahikada** [comment]
I'm very very sorry...
I tried it again, no bugs...
