### ISSUE TITLE
Compatibility with PHP 7.2 TO-DO

### ISSUE THREAD

**Issue by SuperKali** [GenisysPro/GenisysPro#796]
Can you make the version with PHP 7.2?

**Comment by SuperKali** [comment]
![screenshot_20170817-031833](https://user-images.githubusercontent.com/19473898/29391999-46e4e7f8-82fb-11e7-834f-e93d24b12636.jpg)

**Comment by DerddyDert** [comment]
Maybe later. Talk about this in discord
