### ISSUE TITLE
Spawn monster mobs,animals and monster

### ISSUE THREAD

**Issue by dolibalen** [GenisysPro/GenisysPro#799]
version:GenisysPro-1.1dev
can't spawn mobs,animals and monster.

**Comment by DerddyDert** [comment]
use latest src. Where did you get your src?

**Comment by dolibalen** [comment]
-----Server information-----
This server is running GenisysPro-1.1dev (424b5c5) LlamaSpit
PHP version: 7.0.3
API: 3.0.1
Target client: Minecraft PE v1.1.0,v1.1.1,v1.1.2,v1.1.3,v1.1.4,v1.1.5
