### ISSUE TITLE
Warning!

### ISSUE THREAD

**Issue by armagadon159753** [GenisysPro/GenisysPro#800]
#### Issue description
 warning if i use this code(back trace)
![screenshot_2017-08-17-20-05-29](https://user-images.githubusercontent.com/25569806/29426849-37db86a8-8388-11e7-8a67-b130e2f43a66.png)

#### Platform information

* Git commit:462c4dd

* PHP binary version:
7.0.3

* Server OS:
Android 5.1.1 

* Game client:
1.1.5.0
#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```
$player->setMotion(new Vector3(0, 2, 0));
```

**Comment by DerddyDert** [comment]
@armagadon159753 you are very smart. Make a PR or change how you made your plugin.
