### ISSUE TITLE
silk touch & spawners dupe

### ISSUE THREAD

**Issue by VCraftMCPE** [GenisysPro/GenisysPro#801]
#### Issue description

  DUPE (named)  Spawners using silk touch enchant
 i have a protected area  that disable block break event
place a spawner 
 try to break spawner with a Silk Touch enchanted pickaxe and magic happens

#### Platform information

* Git commit:This server is running GenisysPro-1.1dev (0000000) LlamaSpit

* PHP binary version:7.0.2.1

* Server OS:Ubuntu Server 16.0.4.2

* Game client:1.1.4

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by VCraftMCPE** [comment]
im not sure if only workes in named spawners

**Comment by MasterOfTheRealm** [comment]
I've had the EXACT same issue

Spawners  dupe when broken even when the event is cancelled. weird thing is it happens like 35000 blocks away from x 0, y 0...but the event is cancelled fine within that radius. just weird

**Comment by VCraftMCPE** [comment]
@MasterOfTheRealm  how u did fix it?

**Comment by MasterOfTheRealm** [comment]
i didn't i just stopped the spawners from dropping till i have time to properly look into it...which i didnt yet

**Comment by TheAz928** [comment]
I'll take a look whenever I can

**Comment by VCraftMCPE** [comment]
@DerddyDert i think this isnt Genisys bug its Spawner plugin bug https://github.com/karanpatel567/Spawner/blob/master/Spawner-MASTER/src/Karanpatel567/Main.php#L385 the plugin didnt check if event is canceled

**Comment by MasterOfTheRealm** [comment]
i set the event to be cancelled and still had the problem

**Comment by TheAz928** [comment]
use $event->set drops([]);

**Comment by MasterOfTheRealm** [comment]
Hmmm couldn't hurt to try
