### ISSUE TITLE
无法在局域网中找到服务器 Can not find the server in the local area network

### ISSUE THREAD

**Issue by lowingly** [GenisysPro/GenisysPro#804]
Version: 1.1dev (0000000)
Client Version: v1.1.0,v1.1.1,v1.1.2,v1.1.3,v1.1.4,v1.1.5
PHP Version: 7.0.8
3bc7a7e 
WINDOWS 8

使用自家电脑开服，无法通过局域网找到服务器，所以局域网无法进服。但是通过VPS使用外网IP进服是可以的。
我觉得不是我手机和电脑的问题，因为我使用Tesxxxxxx和Bluxxxxx开服都是可以局域网进服的。。。
希望修复，因为我需要在自己电脑上测试插件。。。
如果是我打开的方式不对希望能指正。我英文不好不献丑了。

**Comment by Leo3418** [comment]
您可能没有使用GenisysPro官方构建版本。请从GitHub[下载](https://genisyspro.github.io/GenisysPro/GenisysPro.phar)官方生成的PHAR并重试。

**Comment by xISRAPILx** [comment]
It don't core error.

**Comment by DerddyDert** [comment]
https://discord.gg/WrKzRNn for more help. This is not a GenisysPro issue.
