### ISSUE TITLE
Not working resource pack

### ISSUE THREAD

**Issue by amon28** [GenisysPro/GenisysPro#805]
#### Issue description
When I put my resource pack in the folder named pm.zip and run the server it says this
![screenshot_2017-08-19-14-45-31](https://user-images.githubusercontent.com/22851168/29484268-88e0dbb4-84ed-11e7-8a5e-a77d193eee8d.png)

**Comment by xISRAPILx** [comment]
blame bin

http://fi2.php.net/manual/en/zip.installation.php

**Comment by amon28** [comment]
How can fix it?

**Comment by xISRAPILx** [comment]
http://php.net/manual/en/zip.installation.php @amon28

**Comment by amon28** [comment]
Thanks

**Comment by amon28** [comment]
I don't get the "compile php with zip support using --enable-zip"

**Comment by DerddyDert** [comment]
@amon28 he gave you the proper resource to resolve this issue. If you want to run a MCPE server you need to at least understand the basics of windows/linux server management. For more help go to our discord chat as im closing this issue: https://discord.gg/WrKzRNn
