### ISSUE TITLE
FIX THAT ENCHANCEMENT LABEL!! xD

### ISSUE THREAD

**Issue by Borduni** [GenisysPro/GenisysPro#809]
It's enchancement, not enhancement :D

**Comment by Leo3418** [comment]
That label was intended to be "enhancement".

**Comment by AppleDevelops** [comment]
enchancement isn’t a word genius

**Comment by DerddyDert** [comment]
LOL! @AppleDevelops

**Comment by Borduni** [comment]
Sorry I mean enchantment
