### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by moneymill2400** [GenisysPro/GenisysPro#811]
Unhandled exception executing command 'slapper spawn player title' in slapper: Class pocketmine\network\protocol\AddPlayerPacket not found
[17:17:51] [Server thread/CRITICAL]: ClassNotFoundException: "Class pocketmine\network\protocol\AddPlayerPacket not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

**Comment by DerddyDert** [comment]
Which version of slapper do you use?

**Comment by SuperXingKong** [comment]
Change all packet import to "network\mcpe\protocol" or use old version of GenisysPro (@DerddyDert How about creating a branch for old network API?)

**Comment by moneymill2400** [comment]
jojoe77777/Slapper this is what i used

**Comment by Leo3418** [comment]
@SuperXingKong all users who want to the old network API can download an archived PHAR from https://github.com/GenisysPro/GenisysPro/releases/tag/1.1.5-legacy

**Comment by MasterOfTheRealm** [comment]
@moneymill2400 use this version https://github.com/GenisysProPlugins/Slapper
