### ISSUE TITLE
Player cannot see their own chat

### ISSUE THREAD

**Issue by DerddyDert** [GenisysPro/GenisysPro#813]
Player cannot see their own chat while flying. Once they land then all the chat they sent shows up immediately as if they just said it.

**Comment by Leo3418** [comment]
😕 ❓ 
![ezgif-3-875c2ef800](https://user-images.githubusercontent.com/14175175/29501923-075563b8-85e1-11e7-8222-2e73f07f0e17.gif)

**Comment by DerddyDert** [comment]
@Leo3418 i just updated and tested on the server.

**Comment by erkam2002** [comment]
???

**Comment by TDMidkwhatisxd** [comment]
maybe was lag? =)) + i dont see reproduced on that gif.

**Comment by MasterOfTheRealm** [comment]
@DerddyDert and i found out what causes this, This happens while wearing the Elytra and flying in gmc.

**Comment by DerddyDert** [comment]
Wow

**Comment by optimusprime338** [comment]
omg thats what I was saying .. thanks for fixing!

**Comment by DerddyDert** [comment]
@optimusprime338  you may have been saying that but since you couldn't see what ya said...  :-p
