### ISSUE TITLE
Crafting problems.

### ISSUE THREAD

**Issue by ZloyNick** [GenisysPro/GenisysPro#822]
#### Issue description

Something items can not be craftable, but i have all ingridients. Look at image.

I need in help.

#### Platform information

* Git commit: its my modificated core from Tesseract 1.0.4 version, i take some files from GenisysPro

* PHP binary version: 7.0.6 optimized for x86_64

* Server OS: Debian 7 x86_64 minimal

* Game client: 1.1.5

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by ZloyNick** [comment]
Img:
![screenshot_20170818-231003](https://user-images.githubusercontent.com/23015694/29551341-af87f780-872b-11e7-94ec-1bb3753c5b55.png)

**Comment by erkam2002** [comment]
USE offical GenisysPro if you modificate it is it our problem..

**Comment by ZloyNick** [comment]
My fork more stable, and generator have too many biomes from single.

**Comment by erkam2002** [comment]
your fault

**Comment by erkam2002** [comment]
You say more fault but crafting isnt working ,-.

**Comment by TDMidkwhatisxd** [comment]
so, you make fork and then report bugs here. Best dev ever 👍, should we report bugs to pmmp too?

**Comment by erkam2002** [comment]
xD

**Comment by MasterOfTheRealm** [comment]
Lol that was fixed in Official GenisysPro a while ago

**Comment by MasterOfTheRealm** [comment]
@ZloyNick https://github.com/GenisysPro/GenisysPro/commit/0ea7db45f32db04ad8a04463d480ffb500d8386d
Check It Out ^~^
