### ISSUE TITLE
My plugins arent running correctly

### ISSUE THREAD

**Issue by moneymill2400** [GenisysPro/GenisysPro#834]
I know my plugins should work but when i go to do them on my server it lets me run the command and everything but it just doesnt work like i think its the version of genisys im using And its not giving me an error or nothing

**Comment by InspectorGadget** [comment]
Please check your code. If you can't identify it, please post it here so we can identify together.

**Comment by MasterOfTheRealm** [comment]
@moneymill2400  Try Using The Latest Version

**Comment by InspectorGadget** [comment]
Yes, use the latest version of Genisys or post your code here to be reviewed and be helped.

**Comment by edwinyoo44** [comment]
#739

**Comment by edwinyoo44** [comment]
@chadigos

**Comment by edwinyoo44** [comment]
@chadigos 我是不懂你們後來怎麼又搞回來了

**Comment by chadigos** [comment]
不是我更的

**Comment by edwinyoo44** [comment]
@chadigos  你們是一個Team 說一聲不是我更的就不用負責處理?

**Comment by MasterOfTheRealm** [comment]
Closing due to no response from @moneymill2400
