### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by armagadon159753** [GenisysPro/GenisysPro#835]
![_20170823_231924](https://user-images.githubusercontent.com/25569806/29639050-aafcd86e-8859-11e7-8e22-54455b16c375.JPG)

Commit: c4f5695

**Comment by MasterOfTheRealm** [comment]
@armagadon159753 Try Using The Latest Version

**Comment by armagadon159753** [comment]
@MasterOfTheRealm i use last src now.
I have this warning if i connecter with mcpe Android
I try on windows 10 ans nothing

**Comment by MasterOfTheRealm** [comment]
Any steps on how to reproduce this? @armagadon159753

**Comment by armagadon159753** [comment]
https://github.com/GenisysPro/GenisysPro/commit/c4f5695a105c129fe9b12395b32ba2cea76c939c

1: join server with Android device and console say this warning
2: join server with Windows 10 device and console say nothing 

That all

**Comment by MasterOfTheRealm** [comment]
Oh weird...
