### ISSUE TITLE
Add messages

### ISSUE THREAD

**Issue by SuperAdam47** [GenisysPro/GenisysPro#837]
#### Issue description
 Invalid name! Message not sending and server closed message not to send

#### Platform information

* Git commit:

* PHP binary version:

* Server OS:

* Game client:

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by armagadon159753** [comment]
Wath did  you do?

**Comment by SuperAdam47** [comment]
Nothing

**Comment by erkam2002** [comment]
lol

**Comment by MasterOfTheRealm** [comment]
Duplicate of #604
