### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by amon28** [GenisysPro/GenisysPro#839]
#### Issue description
I just updated the phar and ran my server and I got this I thought this is a plug in problem I remove my plugins but It's showing
![screenshot_2017-08-24-21-29-23](https://user-images.githubusercontent.com/22851168/29668687-aba26c4c-8913-11e7-81d4-fbbf6b85c600.png)

**Comment by InspectorGadget** [comment]
It's their issue, looks like the correct parameter isn't sent [`here`](https://github.com/GenisysPro/GenisysPro/blob/master/src/pocketmine/Server.php#L339)

**Comment by KenMizz** [comment]
same issues here,lol

**Comment by MasterOfTheRealm** [comment]
@amon28 Try Using The Latest Version.

**Comment by amon28** [comment]
It works now Thanks!
