### ISSUE TITLE
update network.php !

### ISSUE THREAD

**Issue by armagadon159753** [GenisysPro/GenisysPro#84]
![screenshot_2017-06-04-17-07-12](https://cloud.githubusercontent.com/assets/25569806/26762825/ddc12264-4948-11e7-80da-1a837f0ffca3.png)

**Comment by caspervanneck** [comment]
just wait

**Comment by caspervanneck** [comment]
or go to pmmp

**Comment by CookieCode** [comment]
I also have this problem. Please fix it!

**Comment by ChaostixZix** [comment]
so the player force close bug has been fixed? @caspervanneck

**Comment by DerddyDert** [comment]
Im not getting this issue
