### ISSUE TITLE
Server is stable enough to start & logon. Now to troubleshoot...

### ISSUE THREAD

**Issue by DerddyDert** [GenisysPro/GenisysPro#85]
#### Issue description
 
- Now we are back to the issue of player being spawned in blocks.(**FIXED**)
- Player cannot break blocks as they didn't spawn.(**FIXED**)
- If you set generation to **flat** then they are **not** spawning in blocks but no blocks spawn and everything is red and dark during the day and clear and stary at night.(**FIXED**)
- After testing PVP one chunk managed to spawn and was breakable. (See pics)(**FIXED**)
- Cannot type in commands as it says cheats are not enabled.(**FIXED**)
- Players being spawned **sideways** as if they are flying. (See pics)(**FIXED**)
- When near another player you hear the Elytra flying sound.(**FIXED**)
- If player clicks inventory, client crashes. (**WIP**)
- If player joins server again after that the client crashes right away. And sometimes after a few cinnctions with the same name it crashes client. (unless player.dat is deleted. Something is getting corrupt in the dat?)(**WIP**)
- Bubble bar always shows. (See pics)(**FIXED**)
- When typing only / the commands do not show.(**FIXED**)

**You can test for yourself on genpro.derddy.com default port. Let us know if it's not up.**
(If you test on this server please write issues you find in a comment below and do **not** start a new issue)

![screenshot_20170604-165444](https://cloud.githubusercontent.com/assets/18636275/26765317/90d12ea0-4947-11e7-83d5-ba99845f7e63.jpg)
![screenshot_20170604-165751](https://cloud.githubusercontent.com/assets/18636275/26765319/9be49426-4947-11e7-88b7-3cea45dd4677.jpg)
![screenshot_20170604-165807](https://cloud.githubusercontent.com/assets/18636275/26765324/a7593cee-4947-11e7-9dcd-ec40da8336dc.jpg)
![screenshot_20170604-171209](https://cloud.githubusercontent.com/assets/18636275/26765381/086d9ed4-4949-11e7-8e50-7f48df8c075a.jpg)
![screenshot_20170604-172334](https://cloud.githubusercontent.com/assets/18636275/26765506/4251b1ec-494b-11e7-8d57-9987c6410af8.jpg)
![screenshot_20170604-172232](https://cloud.githubusercontent.com/assets/18636275/26765515/67b21d3c-494b-11e7-9632-7f1c12c11d54.jpg)

**Comment by DerddyDert** [comment]
You can see for yourself on genpro.derddy.com  default port. If it's up.

**Comment by caspervanneck** [comment]
Wow that is very buggy

**Comment by DerddyDert** [comment]
@caspervanneck did u go on the test server?

**Comment by caspervanneck** [comment]
nope not yet

**Comment by DerddyDert** [comment]
I got it setup on genpro.derddy.com 19132 @caspervanneck

**Comment by SuperXingKong** [comment]
What's the situation now?

**Comment by SuperXingKong** [comment]
By the way, the pictures are interesting xD

**Comment by DerddyDert** [comment]
@SuperXingKong all issues posted above are current. I'll update them as things change. So just use this post to find the latest testing results.

**Comment by SuperXingKong** [comment]
Fixed a lot xD.

**Comment by lightda104530** [comment]
@SuperXingKong  Remember to look at your Discord:D

**Comment by DerddyDert** [comment]
I'll do some tests sun as I can

**Comment by DerddyDert** [comment]
GREAT JOB EVERYONE! All but one issue is left on this list. I will close this issue as I have made separate reports for all current issues.
