### ISSUE TITLE
Add check-movement option in genisys.yml

### ISSUE THREAD

**Issue by SuperAdam47** [GenisysPro/GenisysPro#852]
#### Platform information

* Git commit:

* PHP binary version:

* Server OS:

* Game client:

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by poustmal** [comment]
movement-check option already exists on pocketmine.yml

**Comment by SuperAdam47** [comment]
No not @poustmal @DerddyDert

**Comment by erkam2002** [comment]
look at pocketmine.yml

**Comment by SuperAdam47** [comment]
Looked, not found please add
