### ISSUE TITLE
Server using only one core of 8 cores in processor

### ISSUE THREAD

**Issue by Newmcpe** [GenisysPro/GenisysPro#872]
Server using only one core of 8 cores in processor and tps can be 1.0. How to fix it?
Server OS : Ubuntu Server 16.04.2 LTS (64-bit)

**Comment by erkam2002** [comment]
?

**Comment by Newmcpe** [comment]
i want to use all cores

**Comment by Donquih0te** [comment]
не сможешь

**Comment by erkam2002** [comment]
haha lol that is automatic

**Comment by MasterOfTheRealm** [comment]
try increasing async-workers on pocketmine.yml
