### ISSUE TITLE
RakLib Stopped

### ISSUE THREAD

**Issue by SuperKali** [GenisysPro/GenisysPro#873]
![img_20170831_152251](https://user-images.githubusercontent.com/19473898/29925334-5091bc84-8e60-11e7-8172-bdcdef1120ed.jpg)
I've updated the new version, but the server sometimes crashes

**Comment by MasterOfTheRealm** [comment]
any steps to reproduce this?

**Comment by SuperKali** [comment]
I don't know

**Comment by erkam2002** [comment]
Bruh

**Comment by SuperKali** [comment]
please solve it @MasterOfTheRealm

**Comment by SuperKali** [comment]
what, why?

**Comment by SuperKali** [comment]
@Leo3418 ..... what you delete my comment? I am unpleasant? if you can answer, you would do me a favor

**Comment by MasterOfTheRealm** [comment]
@SuperKali i noticed that you don't bother to block out your players ip addresses... which is never a good thing to show everyone.

**Comment by SuperKali** [comment]
@MasterOfTheRealm and so? do you have a solution to this problem?

**Comment by SuperXingKong** [comment]
Could you please set debug level to 3 or higher?(pocketmine.yml)
