### ISSUE TITLE
How to install php 7.2? Help

### ISSUE THREAD

**Issue by oGalatico** [GenisysPro/GenisysPro#877]
#### Platform information

* Git commit:

* PHP binary version:

* Server OS:

* Game client:

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

**Comment by oGalatico** [comment]
Help ;-;

**Comment by Leo3418** [comment]
For questions, please post them in our [forums](https://genisys.pro/forums) or [Discord chat](https://discord.gg/WrKzRNn), not here on GitHub Issues. Thank you!

**Comment by HipsterAF** [comment]
https://t.co/WHxPNcqIAZ
