### ISSUE TITLE
BLOCK GLITCH

### ISSUE THREAD

**Issue by HipsterAF** [GenisysPro/GenisysPro#879]
#### Issue description

Okay, take a diamond shovel, enchant it to efficiency 3, try to break dirt or gravel etc, the block doesnt break, only after some tries it break.

#### Platform information

* Git commit: e52d41c

* PHP binary version: 7.2

* Server OS: Linux

* Game client: MCPE v1.1

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```
None
```

**Comment by MasterOfTheRealm** [comment]
set `allow-instabreak: true` in pocketmine.yml

**Comment by HipsterAF** [comment]
holy shit youre a legend, you got kik? or discord?
