### ISSUE TITLE
Server doesn't stop

### ISSUE THREAD

**Issue by ivan691** [GenisysPro/GenisysPro#882]
Please see screenshot, i need help very much! Thank you
https://pp.userapi.com/c638621/v638621656/5ba8e/d5CVB13XCHE.jpg

**Comment by ivan691** [comment]
:(

**Comment by ivan691** [comment]
someone help me please its very important... downloaded core yesterday

**Comment by TDMidkwhatisxd** [comment]
for me it stops. Is something at your end for sure.

**Comment by ivan691** [comment]
where you downloaded bin 7.2

**Comment by InspectorGadget** [comment]
PHP 7.2 Binary

Windows: https://t.co/WHxPNcqIAZ
Linux: https://t.co/KjFKW49DAZ
Original Post: https://twitter.com/dktapps/status/903359889791213568

**Comment by SuperXingKong** [comment]
Use the latest src :)
