### ISSUE TITLE
what is faster??/

### ISSUE THREAD

**Issue by bettystopban** [GenisysPro/GenisysPro#884]
pmmp or genisyspro ?

**Comment by mal0ne-23** [comment]
PMMP

**Comment by HimbeersaftLP** [comment]
[Fukkit](https://github.com/Fukkit/Fukkit) and [Sukkit](https://github.com/Sukkit/Sukkit) of course :D

**Comment by DerddyDert** [comment]
@HimbeersaftLP  sukkit is da best
