### ISSUE TITLE
Crops not growing

### ISSUE THREAD

**Issue by PragaKart67z** [GenisysPro/GenisysPro#894]
#### Issue description

Crops like wheat, cactus, sugarcane, etc aren't growing at normal speeds if they grow at all. Only wheat will grow. To reproduce this issue plant any of the above crops and watch them not grow.

#### Platform information

* Git commit:
Travis #1098

* PHP binary version:
7.0.21

* Server OS:
Ubuntu 64-bit

* Game client:
MCPE 1.1.4 on Android 6.0
#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```
No plugins and or crash dumps
```

**Comment by CortexPE** [comment]
they do.
![image](https://user-images.githubusercontent.com/17762324/30060665-f26a0992-9209-11e7-88e7-4237e868355a.png)
