### ISSUE TITLE
Mcpe crash upon building terrain

### ISSUE THREAD

**Issue by Pizzahaet** [GenisysPro/GenisysPro#90]
#### Issue description

 Mcpe client crashes upong building terrain
#### Steps to reproduce the issue

Not sure exactly
#### OS and versions

* Genisys: latest commit 
* PHP: 7
* Server OS: Linux Centos7
* Game version: 1.1.0.0.55

#### Crashdump, backtrace, memory dumps, plugins list or other files

``` WorldEdit+ v0.01, PurePerms v1.4.0-INDEV, DevTools v1.11.0, NoHungerInWorld v0.2, MSpawns v1.4, NoAdvertisingPE v1.0.1, SimpleKits v0.5.1, Pets v1.0.0, SafeFly v1.0.0, SlapperRotation v1.0.1, Broadcaster v1.16, Kohi1v1 v0.0.5, Slapper v1.3.3, Elo v1.0.0, AlwaysSpawn v2.2.2, BlockCmdPE v1.0.1, CombatLogger v1.2.1, InventoryClear v1.3, SW_svile v0.6dev, EconomyAPI v2.0.9, BuyCraft v1.2.2, iProtector v3.1b, ServerAuth v2.13, 2vs2 v1.0.5, ChatLogin v1.4, AntiSpam v1.3, CustomAlerts v1.5, LuckyBlock v3.1.0, PureChat v1.4.1, SimpleWarp v2.1.1

```

**Comment by Pizzahaet** [comment]
WorldEdit+ v0.01, PurePerms v1.4.0-INDEV, DevTools v1.11.0, NoHungerInWorld v0.2, MSpawns v1.4, NoAdvertisingPE v1.0.1, SimpleKits v0.5.1, Pets v1.0.0, SafeFly v1.0.0, SlapperRotation v1.0.1, Broadcaster v1.16, Kohi1v1 v0.0.5, Slapper v1.3.3, Elo v1.0.0, AlwaysSpawn v2.2.2, BlockCmdPE v1.0.1, CombatLogger v1.2.1, InventoryClear v1.3, SW_svile v0.6dev, EconomyAPI v2.0.9, BuyCraft v1.2.2, iProtector v3.1b, ServerAuth v2.13, 2vs2 v1.0.5, ChatLogin v1.4, AntiSpam v1.3, CustomAlerts v1.5, LuckyBlock v3.1.0, PureChat v1.4.1, SimpleWarp v2.1.1

**Comment by DerddyDert** [comment]
Hey @Pizzahaet how have you been? I cannot duplicate this error? Please delete your player .dat file and try to join using the latest src.

**Comment by xRazvan9** [comment]
This error is and in my server

**Comment by DerddyDert** [comment]
Can you explain more? @xRazvan9

**Comment by DerddyDert** [comment]
@Pizzahaet did you mean as chunks load or actually when player places blocks/builds?

**Comment by xRazvan9** [comment]
If i enter to server my mcpe case

**Comment by xRazvan9** [comment]
Stoped*

**Comment by DerddyDert** [comment]
That happens if you touch your inventory. Please delete the player .dat and try again. Then let me know here.

**Comment by DerddyDert** [comment]
I'm closing this as it's a duplicate already brought up. To resolve this for now please delete player.dat.

**Comment by Pizzahaet** [comment]
deleting player data didnt work
