### ISSUE TITLE
Mcpe Crash

### ISSUE THREAD

**Issue by xRazvan9** [GenisysPro/GenisysPro#91]
#### Issue description

When I enter the server, my mcpe stops working and closes automatically
#### OS and versions

* Genisys:1.1dev
* PHP:7.0.3
* Server OS:Linux
* Game version: 1.1

#### Crashdump, backtrace, memory dumps, plugins list or other files

```
```

**Comment by caspervanneck** [comment]
delete the player data @xRazvan9

**Comment by Pizzahaet** [comment]
@caspervanneck I just tried that it doesn't work

**Comment by DerddyDert** [comment]
We know about this bug. This is a duplicate issue.
