### ISSUE TITLE
SetEntityDataPacket not found"

### ISSUE THREAD

**Issue by BexiPE** [GenisysPro/GenisysPro#93]
I cant Join whit 1.1

**Comment by BexiPE** [comment]
Its not work ^^ xD

**Comment by BexiPE** [comment]
5:11] [RakLibServer thread/NOTICE]: Blocked 77.21.248.126 for 5 seconds
[17:45:18] [Server thread/CRITICAL]: ClassNotFoundException: "Class pocketmine\n
network\protocol\SetEntityDataPacket not found" (EXCEPTION) in "/src/spl/BaseClas
ssLoader" at line 144

**Comment by SuperXingKong** [comment]
Check your files,it's existing.
Look at this https://github.com/GenisysPro/GenisysPro/blob/master/src/pocketmine/network/protocol/SetEntityDataPacket.php

**Comment by BexiPE** [comment]
Yes its Work , but mc crahes when I join :/
