### ISSUE TITLE
PHP 7.2

### ISSUE THREAD

**Issue by Newmcpe** [GenisysPro/GenisysPro#954]
Please give url to new php 7.2 for genisys pro

**Comment by armagadon159753** [comment]
Maybe that can you save  you https://jenkins.pmmp.io/job/PHP-7.2-Linux-x86_64/

**Comment by Newmcpe** [comment]
i want windows bin

**Comment by poustmal** [comment]
pmmp has a 7.0 php branch,it should be good if was exist.

**Comment by Leo3418** [comment]
For questions, please post them in our [forums](https://genisys.pro/forums) or [Discord chat](https://discord.gg/WrKzRNn), not here on GitHub Issues. Thank you!

**Comment by DerddyDert** [comment]
We will be moving php7.2 to a branch shortly as there are to many issues for it to be in the master branch.
