### ISSUE TITLE
syntax error on /src/pocketmine/Player.     

### ISSUE THREAD

**Issue by armagadon159753** [GenisysPro/GenisysPro#97]
GenisysPro Crash Dump Tue Jun 6 10:26:53 CDT 2017

Error: syntax error, unexpected 'public' (T_PUBLIC)
File: /src/pocketmine/Player
Line: 1443
Type: notice

Code:
[1434] 	public static function getClientFriendlyGamemode(int $gamemode) : int{
[1435] 		$gamemode &= 0x03;
[1436] 		if($gamemode === Player::SPECTATOR){
[1437] 			return Player::CREATIVE;
[1438] 		}
[1439] 
[1440] 	/**
[1441] 	 * Sends all the option flags
[1442] 	 */
[1443] 	public function sendSettings(){
[1444] 		$pk = new AdventureSettingsPacket();
[1445] 		$pk->flags = 0;
[1446] 		$pk->worldImmutable = $this->isAdventure();
[1447] 		$pk->autoJump = $this->autoJump;
[1448] 		$pk->allowFlight = $this->allowFlight;
[1449] 		$pk->noClip = $this->isSpectator();
[1450] 		$pk->isFlying = $this->flying;
[1451] 		$pk->userPermission = ($this->isOp() ? AdventureSettingsPacket::PERMISSION_OPERATOR : AdventureSettingsPacket::PERMISSION_NORMAL);
[1452] 		$this->dataPacket($pk);
[1453] 	}

Backtrace:
#0 /src/pocketmine/Server(526): spl_autoload_call(string pocketmine\Player)
#1 /src/pocketmine/Server(2317): pocketmine\Server::getGamemodeString(integer 0)
#2 /src/pocketmine/Server(1922): pocketmine\Server->start(boolean)
#3 /src/pocketmine/PocketMine(470): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /storage/emulated/legacy/Genisys/, string /storage/emulated/legacy/Genisys/, string /storage/emulated/legacy/Genisys/plugins/)

Genisys version: 0000000000000000000000000000000000000000 [Protocol 113; API 3.0.1]
uname -a: Linux localhost 3.10.49-g1ae94df #1 SMP PREEMPT Tue Oct 18 20:01:12 IST 2016 armv7l
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, android

Server uptime: 10 seconds
Number of loaded worlds: 2
Players online: 0/20

Loaded plugins:
![_20170606_172821](https://user-images.githubusercontent.com/25569806/26837373-9496cc42-4add-11e7-8740-3a399f4629b3.JPG)

**Comment by andris155** [comment]
same problem

**Comment by ChaostixZix** [comment]
@armagadon159753 @andris155 I Think There is am MissType

i Dont Have Acces To GenisysPro Repository.
So, Could You Find This On src/pocketmine/player.php
![screenshot at jun 06 09-40-42](https://user-images.githubusercontent.com/19998246/26840843-61cad146-4a9c-11e7-943e-999c8ff14178.png)

**Before**

> public static function getClientFriendlyGamemode(int $gamemode): int
    {
        $gamemode &= 0x03;
        if ($gamemode === Player::SPECTATOR) {
            return Player::CREATIVE;
        }

**Please Change It To**

> public static function getClientFriendlyGamemode(int $gamemode): int
    {
        $gamemode &= 0x03;
        if ($gamemode === Player::SPECTATOR) {
            return Player::CREATIVE;
        }
    }

**There Is An Error Because Someone Forget To Add }**

**Comment by SamyR0** [comment]
@armagadon159753 with @andris155  now works ?

**Comment by andris155** [comment]
yes, work

**Comment by DerddyDert** [comment]
Someone fix this or wait till I get a chance to jump on my computer.

**Comment by SamyR0** [comment]
lol =))

**Comment by DerddyDert** [comment]
Sorry for the long wait buddy.
