### ISSUE TITLE
Crash On Join

### ISSUE THREAD

**Issue by ChaostixZix** [GenisysPro/GenisysPro#98]
I Used Latest Genisys Branch

When The Player Join The Server, The Client Crashed.
**I Got This On Console**
![screenshot at jun 06 09-48-05](https://user-images.githubusercontent.com/19998246/26841076-467688a8-4a9d-11e7-89d9-4ee8d4b29278.png)

**MC WIN 10**
**PHP 7.0.3**
**Mac Os X**

**Comment by armagadon159753** [comment]
Sale problème i think  the error from LoginPacket.php  ( maybe )

**Comment by DerddyDert** [comment]
Try again now with new src.

**Comment by andris155** [comment]
I confirmed this bug.

**Comment by DerddyDert** [comment]
@andris155 Please test with the NEW source.

**Comment by andris155** [comment]
Tested. Client crashed on join. 
![kepkivagas](https://user-images.githubusercontent.com/8324198/26852054-25d29f2c-4b0d-11e7-8d55-bff2cb7da300.PNG)

**Comment by ChaostixZix** [comment]
@DerddyDert Still Crashing

**Comment by DerddyDert** [comment]
I confirmed this. This is the same bug already reported in #85 I believe it has to do with player position, inventory as well as the creation of player.dat. Main suspects are Player.php, LoginPacket.php, StartGamePacket.php. I still think we need more work in MovePlayerPacket.php as this bug has happened the whole time since switch to 1.1.x and well before the last few commits. It just happens right away now. @caspervanneck @SuperXingKong

**Comment by SuperXingKong** [comment]
How long has it happened? (Since which commit?)

**Comment by ChaostixZix** [comment]
@SuperXingKong Before The Red Sky Bug i think

**Comment by ChaostixZix** [comment]
Its happen when genisys upgraded to 1.1

**Comment by AppleDevelops** [comment]
Enable debugging

**Comment by ChaostixZix** [comment]
![screenshot at jun 07 08-18-05](https://user-images.githubusercontent.com/19998246/26886357-f64e27f6-4b59-11e7-9682-94fb55ec4485.png)

Howefer, I Fixed It By Deleting int $gamemode 

**BEFORE**
![screenshot at jun 07 08-20-43](https://user-images.githubusercontent.com/19998246/26886474-5461b948-4b5a-11e7-9821-bc836c64577c.png)

**AFTER**
![screenshot at jun 07 08-20-37](https://user-images.githubusercontent.com/19998246/26886482-5a240a70-4b5a-11e7-8722-24a82a880309.png)

And Now I Got This Error
![screenshot at jun 07 08-20-49](https://user-images.githubusercontent.com/19998246/26886459-49eae930-4b5a-11e7-8add-3bf9af9a4a1c.png)


I Dont Know Why $gamemode is an Empty Variable

@SuperXingKong  @DerddyDert  @AppleDevelops

**Comment by ChaostixZix** [comment]
@SuperXingKong  @DerddyDert  @AppleDevelops 
**Im Just Trying To Guest, But This Fixed The Problem**

![screenshot at jun 07 08-43-50](https://user-images.githubusercontent.com/19998246/26887671-78a7abe8-4b5d-11e7-87bd-9c0ee8a16784.png)
**HAHA** :D
 ![screenshot at jun 07 08-45-17](https://user-images.githubusercontent.com/19998246/26887730-a74f9b40-4b5d-11e7-8e06-f66ada2ae6f2.png)

**But We Got Another Problem**
![screenshot at jun 07 08-46-00](https://user-images.githubusercontent.com/19998246/26887768-c3aa2814-4b5d-11e7-9866-b253eccc2875.png)



Since I Have No Acces To Genisys Repo, I'll Make A Pull Request

**Comment by ChaostixZix** [comment]
#102
